### ISSUE TITLE
Bundling PEX file for Python applications with pinned dependencies

### ISSUE THREAD

**Issue by hiboo** [pantsbuild/pex#1005]
Hello there,

I'm currently using PEX to bundle my Python applications (API, workers, ...) to be deployed easier on different machines.
I want my PEX to bundle pinned version of each of my application dependencies (as well as my application source code) so I'm sure the behavior of the application is the same as the one I developed locally.

However, when running `pex -o myapp.pex .` or `python setup.py bdist_pex`, I suppose that PEX resolve the requirements from the `setup.py` file `install_requires` argument. Again, I suppose that this may result in different builds if dependencies are not pinned (for example requirement: `flask>=1.0.0` could lead pex to resolve flask with the latest released version while I could develop and test locally my application with flask 1.0.1,  leading to a difference between my application and the built one with potential issues).

To fix this I generate a `requirements.txt` file containing my application pinned dependencies then I run:
`pex -r requirements.txt -o myapp.pex .`

However, I'm wondering if this is fine as it may cause pex to have to resolve dependencies twice (one time from requirements.txt and one another from setup.py).

Is it ok ? Is there any better practice to generate a Python application PEX file using pinned dependencies ? Am I wrong about PEX or application bundling ?

Thanks for reading and this awesome tool

**Comment by stuhood** [comment]
Hey @hiboo ! For context, `pants` does support using lock/constraints files when invoking pex: https://www.pantsbuild.org/docs/python-third-party-dependencies#using-a-lockfile-recommended ... and that support is implemented using a post-2 feature of pex. So on the latest version of pex, you should see:
```
  --constraints=FILE    Add constraints from the given constraints file.  This
                        option can be used multiple times.
```

**Comment by hiboo** [comment]
Thank you @stuhood for your answer !

Indeed, I found the `--constraints` solution pretty ideal to solve this kind of issues. I tried it and it worked like a charm. However, I could not notice any build time difference using `--requirements` vs `--constraints`. I'm wondering if, in the end it does change anything... I don't know well enough how *pex* exactly packages deps to know if one way is actually better than the other.

I keep the topic open in case of someone got better/different ideas

**Comment by stuhood** [comment]
My understanding of the constraints files is that they are more for reproducibility and determinism than they are for performance... but you could check with the PIP folks about whether there are any optimizations that could be implemented there?

**Comment by Eric-Arellano** [comment]
Yeah, I doubt constraints files would result in much better performance. Pip will still need to execute `setup.py` to figure out dynamically what distributions the library has, and only then can it consult your constraints file to see if it should use the version you provided for that distribution.

But, constraints files are important for reproducibility, so we recommend using them.

Going to close as answered, but please feel free to ask any more questions about this or Pex :) Also check out https://www.pantsbuild.org/docs/community for a slack group. While it's mostly for Pants, there is a #pex channel.
