### ISSUE TITLE
Allow constraining the interpreter search path directly.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1012]
Right now the Pex API allows this:
https://github.com/pantsbuild/pex/blob/b51b340bea8a585a246997071a815d008986d6e3/pex/interpreter.py#L278-L288

Neither the CLI (buildtime) nor runtime via PEX-INFO / ENV vars does however forcing manipulation of the PATH to acheive the desired effect. This is problematic at buildtime since during wheel building tools may need to be invoked by subprocesses (think gcc). This could also be problematic at runtime for any PEX housing user code that needs to shell out to tools expected to be on the PATH.

See https://github.com/pantsbuild/pants/issues/9760 for the motivating issue.

**Comment by stuhood** [comment]
Echoing a comment from the other ticket: Pants' API for this is: https://github.com/pantsbuild/pants/blob/e328b58af917440dc98c8aa88dbd49a9355c5e8d/src/python/pants/python/python_setup.py#L87-L99, which is implemented here:
https://github.com/pantsbuild/pants/blob/e328b58af917440dc98c8aa88dbd49a9355c5e8d/src/python/pants/python/python_setup.py#L178-L205

**Comment by jsirois** [comment]
OK - Lies above. Both buildtime and runtime support PEX_PYTHON_PATH which is a path-like env var that accepts both directory entries and paths to interpreter binaries:
1. Build time:
https://github.com/pantsbuild/pex/blob/5fd9b1527691f3efb42a469a563a7653a3a1594d/pex/bin/pex.py#L722-L725
2. Run time:
https://github.com/pantsbuild/pex/blob/b51b340bea8a585a246997071a815d008986d6e3/pex/pex_bootstrapper.py#L203-L215

This fully suffices for the Pants motivating use case. It still may make sense to add a CLI flag / PexInfo metadata slot for this to bake in a "corporate" interpreter path without resorting to ~/.pexrc or /etc/pexrc, but that resort has been working? for Twitter at least as an example of corporate.

**Comment by Eric-Arellano** [comment]
Closed by https://github.com/pantsbuild/pex/pull/1077. https://github.com/pantsbuild/pex/issues/1075 tracks removing `PEX_PYTHON_PATH` from build time.
