### ISSUE TITLE
Pex skipping pandas activation

### ISSUE THREAD

**Issue by blackstardlb** [pantsbuild/pex#1017]
Running `pex pandas==1.0.5 -v` using python 3.6.2 outputs.
 ``pex: Skipping activation of `pandas==1.0.5; python_version >= "3.6.1"` due to environment marker de-selection``
Thus `import pandas` results in :
`Traceback (most recent call last):
  File "<console>", line 1, in <module>
ModuleNotFoundError: No module named 'pandas'`

**Comment by blackstardlb** [comment]
It works if i use pex==2.1.6

**Comment by jsirois** [comment]
In pex 2.1.7 we started honoring python_requires metadata in #923 fixing #898 which explains your observation that this problem does not exist in pex 2.1.6.

It looks like that fix has a bug when converting `Requires-Python` wheel metadata into an equivalent environment marker:
https://github.com/pantsbuild/pex/blob/e5b62caddbf4070521980f54984a01ed55251bf9/pex/resolver.py#L103-L117

Whereas [`Requires-Python`](https://packaging.python.org/specifications/core-metadata/#requires-python) allows for full version specifiers as per [PEP-440](https://www.python.org/dev/peps/pep-0440/), The `python_version` environment marker just uses the major and minor versions (https://www.python.org/dev/peps/pep-0508/#environment-markers) so converting all `Requires-Python` constraints to `python_version` constraints is incorrect. For any constraint that includes a patch level in the version constraint the `python_full_version` environment marker should be used.

Thanks for pinning down the Pex version where things went wrong, that was helpful pinpointing this.
