### ISSUE TITLE
Readthedocs documentation site showing outdated pex version

### ISSUE THREAD

**Issue by jriddy** [pantsbuild/pex#1085]
The doc site https://pex.readthedocs.io/en/stable/index.html has "pex 0.7.0-rc0" as the page title. Either that's false and needs to be fixed because it's worrying to the reader, or that's true and these docs need to be taken down and replaced with new ones :D

**Comment by jsirois** [comment]
Taken down. Since the doc generation process just got fixed after the latest stable release (2.1.19) there will be no stable link until Pex 2.1.20 is released. So, for now, the default doc is latest.

**Comment by jriddy** [comment]
Cool, looks fixed. I'll give it a few days until the search engines re-index this. I found this by searching "pex docs" btw
