### ISSUE TITLE
Support dependency lock files to save the results of package resolution

### ISSUE THREAD

**Issue by jriddy** [pantsbuild/pex#1086]
This is feature request to support _lock files_ to save and re-use the results of a package resolution. 

Having to resolve packages each time pex is executed is time consuming and difficult, especially if you end up in workflows that call pex a lot (like in pants). And this is kinda unfortunate, because the results of resolutions can be fairly easily saved, which could in turn save users a lot of time.

### What are lockfiles?

Lockfiles save important data about the exact dependency packages needed to reproduce an environment deterministically. This is more than just a pinned version. This is an exact match, with checksums and source information. Many, many packaging solutions use these (cargo, npm, [pipfile](https://github.com/pypa/pipfile), poetry, gradle, gem) to gain true determinism in builds.

It's easy to see why pex has never done this because it could be argued that the pex format is itself a kind of lockfile, and you can re-use its resolutions as with `--requirements-pex`. Pants seems to use pex like this, but this is kind of inefficient, and results in fairly coarse-grained caching effects.

If instead we saved the resolution as a json/toml/yaml lockfile of some kind, caching could be based purely on questions like "does what i have in my cache for this name match the checksum in the lockfile." 

### What about constraints files?

These are not lockfiles, and were never intended to be. The only difference between them and requirements files is that they don't force the installation of what's inside them, but [only constrain the versions](https://pip.pypa.io/en/stable/user_guide/#constraints-files) of packages _if they are installed_.

In contrast, a lockfile demands that its _exact set of sources_ get installed, and doesn't allow for any deviation or decision making beyond that. That the [pants documenation](https://www.pantsbuild.org/docs/python-third-party-dependencies#using-a-lockfile-strongly-recommended) calls `constraints.txt` a lockfile is a bit misleading, especially in light of how pex will attempt to perfom resolutions with it. A lockfile is the result of a resolution, not an input to one.

### What should lockfiles contain?

At the base, there should be metadata about the platform and implementation it was generated on, and then a list of packages with their checksums and urls they were downloaded from. 

### How would we use this?

I could see a workflow like this...

```
pex --generate-lockfile pex.lock -r requirements.txt --no-output-file  # Generate the lockfile and exit
pex -L pex.lock -r requirements.txt -O  # same thing with short options

pex --from-lockfile pex.lock --output-file app.pex  # create the pex using the exact dependencies as specified in the lock file
pex -l pex.lock -o app.pex  # same thing with short options
```

I'm well aware that this is a big feature request, and I'm willing to help make it happen, but I would need some guidance on where to start.

**Comment by kaos** [comment]
I guess this is being implemented by  the work under the #1400 umbrella..

**Comment by thejcannon** [comment]
@jsirois can this be closed?

**Comment by jsirois** [comment]
Yeah. This is now implemented even though there are missing bits I'd personally like to see; namely, support for lock file updates (`pex3 lock update -p just_this_dep -p and_this_one`).
