### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas'

### ISSUE THREAD

**Issue by vnkesarwani** [pantsbuild/pex#1092]
I tried all the version above >2.1.6 with python version 3.6.9. I am getting issue for pandas binaries as of now. I am not getting any clue though.

This issue is raised earlier by others too. Do we have any plan to fix this bug in future??

Thanks,
Vinay

**Comment by jsirois** [comment]
@vnkesarwani is your issue exactly as described in #1017? If not, please re-open this issue and provide at least an equivalent amount of detail as in #1017 so I can try to reproduce the problem.

As to fixing #1017, That should go out in the Pex 2.1.21 release tracked by #1078 next week.
