### ISSUE TITLE
Pex discards the current interpreter's PATH entry when it is a directory entry.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1109]
This means no other interpreters in the current interpreter's directory (sibling interpreters) can be found. This is an egregious problem since interpreters are commonly installed to /usr/bin; i.e.: /usr/bin/python2.7, /usr/bin/python3.6, ... etc will all be siblings and if a PEX is run with any one of them, the others won't be discoverable.

N.B.: Pex only encounters this condition when `PEX_PYTHON_PATH` / `--python-path` are used, populating the `path` function parameter below:
https://github.com/pantsbuild/pex/blob/93b0442c9574a0bba018249d842dc2ac29dc1e27/pex/pex_bootstrapper.py#L40-L45

And the bug is here where we remove both the interpreter binary path (which is ok) and the interpreter binary directory (which is the bug):
https://github.com/pantsbuild/pex/blob/93b0442c9574a0bba018249d842dc2ac29dc1e27/pex/pex_bootstrapper.py#L83-L89

**Comment by rcuza** [comment]
Can this fix be cherry-picked into 2.0.0? If I have to upgrade to 2.1.0, I will have to add refactoring our `python_requirement_library` entries to my sub-task list.
