### ISSUE TITLE
building from tox: unknown environment 'package' 

### ISSUE THREAD

**Issue by mtd321** [pantsbuild/pex#113]
Following the installation notes:

    % tox -e package      
    ERROR: unknown environment 'package'

What am I missing?

    % git show --oneline           
    366a2a3 Merge pull request #104 from wickman/wickman/103
    % tox --version
    1.8.0 imported from /usr/lib/python3/dist-packages/tox/__init__.pyI

**Comment by wickman** [comment]
Good catch.  The docs are out of date.  You need to specify the default interpreter class now: tox -e py27-package or tox -e py34-package.  Will update README.

**Comment by wickman** [comment]
Fixed at 7afaa637.
