### ISSUE TITLE
Python 3.9.1 release reverts pex to 2.0.3

### ISSUE THREAD

**Issue by kti-richard** [pantsbuild/pex#1141]
Should 
```
requires-python = ">=2.7,<=3.9,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*"
```
be 
```
requires-python = ">=2.7,<3.10,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*"
```

or is 3.9.1 (patch levels) actually to be blocked?

**Comment by jsirois** [comment]
Your suggestion is correct, we should have been using `<3.10`.

**Comment by jsirois** [comment]
Thanks for the report - there is a bit of churn dealing with the 2.1.23 release and https://github.com/pypa/pip/issues/9283 but I'll get this fix in the next release here today.

**Comment by mjuarez** [comment]
I'm encountering a similar issue with Python 3.8 but I'm seeing you've been building for 3.8 successfully. Is 3.8 also unsupported?

**Comment by seerickcode** [comment]
> I'm encountering a similar issue with Python 3.8 but I'm seeing you've been building for 3.8 successfully. Is 3.8 also unsupported?

I was using 3.8 without issue.  I was then using 3.9 without issue, but a few days ago, deadsnakes repo (debian/ubuntu) packaged 3.9.1 (which I got from updates), and I just happened to be building a new virtual environment, and the issue came up.

**Comment by mjuarez** [comment]
I'll move to a separate issue

**Comment by jsirois** [comment]
@mjuarez 3.8 has been supported for quite some time. Definitely file a new issue if you are having problems installing or running modern Pex in a Python 3.8 environment.
