### ISSUE TITLE
test suite creates tmpJIMMEH directories in $HOME

### ISSUE THREAD

**Issue by wickman** [pantsbuild/pex#117]
cc @Yasumoto

**Comment by jsirois** [comment]
@jamesmeador this could really use some love

**Comment by Yasumoto** [comment]
@jasonsims @rbwhite @dmw7752 @jaguilar might be able to pitch in as well

**Comment by Yasumoto** [comment]
This is almost assuredly some mis-mocking at https://github.com/pantsbuild/pex/blob/28e03d2f221fe2ee3273900e74a45c50862d5a9f/tests/test_util.py#L118

**Comment by jaguilar** [comment]
Some o dat. Seems like we just need to create the dir in some place the test suite or so cleans up automatically, rather than in $HOME.
