### ISSUE TITLE
Pex does not use the pip 2020-resolver when resolving for Python 2.7

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1179]
It turns out Pip defaults to the legacy resolver under Python 2.7 and the 2020 resolver under anything else. As such, we need to actively pass --use-feature=2020-resolver when our resolve target is a Python 2.7 interpreter.

**Comment by butlern** [comment]
👍 

Nit: I think in pip parlance it would be --use-feature=2020-resolver.

**Comment by jsirois** [comment]
Fixed.
