### ISSUE TITLE
Add --prefer-binary to pip

### ISSUE THREAD

**Issue by butlern** [pantsbuild/pex#1202]
I recently encountered an issue with pex trying to download an unfortunate package from the pypi ecosystem: boilerpipe. boilerpipe sets an unbounded dep on JPype1. The most recent JPype1 is py3 only. But there appear to only be sdists on pypi. This results, when running pex with py2 interpreter, in pip downloading the latest JPype sdist and the wheel building fails because JPype1 uses pathlib in its setup.py :(

We have run our own cheeseshop in the past to workaround these unfortunate problems with the pypi ecosystem, but we'd like to not have to maintain our cheeseshop as much and move to pypi more and more. With our cheeseshop in place for special case pre-built wheel packages, we could specify both it and pypi if pex supported --prefer-binary.

The proposed option can be off by default, just plumbed through so that we can access it from the cli and then i can issue a seperate pants ticket to add that option in pants.

**Comment by Thrameos** [comment]
Unfortunately JPype has been py3 only for a while.  Older versions used mostly Python code with a hidden backend so it was fairly version agnostic.  Once py2 was retired we could finally switch to most of the machinery in C for speed.   But the object model is tied to py3.  Unfortunately the means no way to support older versions.  Some early 0.7.x series will still run on py2.  

I generally recommend moving to py3 if possible.

**Comment by jsirois** [comment]
@butlern that sounds like a reasonable flag to plumb, but also can;t you take complete control over this sort of situation by using a constraints file? Pex has supported that for a while and its less chancy than --prefer-binary which may not work for all situations like this.

**Comment by butlern** [comment]
Ah, excellent point. I will try that out.

**Comment by butlern** [comment]
And yes @thrameos. We definitely want to migrate off py2 asap. There's unfortunately some legacy code that will take some time to complete (such as the one using boilerpipe/JPype). If you have any sway over the JPype community, it would be useful for them to publish wheels instead of just sdists. I might be incorrect but I believe pip excludes wheels that don't match the interpreter version. I don't think it can do so for sdists though.

**Comment by Thrameos** [comment]
@butlern We publish about 20 different whl files with each dist and the sdist.  The sdist is intended for architectures we missed or newer versions of Python.  But py2 must look see there is no whl and try to build.  Perhaps there is a missing specification in the setup.py?

https://pypi.org/project/JPype1/#files

**Comment by jsirois** [comment]
@Thrameos 
yeah, you should be using `python_requires`: https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

This won't help @butlern since you would have had to have been using it at least for all your past python 3 only releases, but it's a good idea to add in going forward anyhow.

**Comment by Thrameos** [comment]
Okay we should send a notice to the maintainer with an issue on Jpype.  He doesnt monitor issues outside of JPype usually.  I am the developer so I dont control the distribution channels.  We can issue a patch release so going forward it will be correct and perhaps pull the older sdist files.  That would hurt pinned versions though so not sure if we can.

**Comment by jsirois** [comment]
@butlern, from your recent Pants Slack report, it sounds like the need for this feature is ameliorated for you at the current time (via a constraints file workaround). Is that correct?

**Comment by butlern** [comment]
Yah, we dont technically need it for our purposes. If you dont feel like
this would be a good general purpose idea then i’m fine with closing.

**Comment by jsirois** [comment]
Great, thanks @butlern

**Comment by jsirois** [comment]
Although the `boilerpipe` root example is now unuseable (googlecode 404s when its setup.py tries to fetch tgzs), the JPype1 example using python2.7 still repros. I'll go with that as the integration test for the new `--prefer-binary` feature.
