### ISSUE TITLE
PexInfo.pex_hash does not include metadata

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1218]
Generally a PEX file is uniqued by a combination of its user code and dependencies. Currently, this is what the `pex_hash` is comprised of:
https://github.com/pantsbuild/pex/blob/d205e2db713ce30d70cd2df9704468f8a3b3f9e0/pex/pex_builder.py#L508-L512

This scheme is foiled by PEX files with the same code and deps but different entry points (or any other metadata for that matter). This sort of thing comes up frequently in Pants with the BUILD file pattern:
```
pex_library()
pex_binary(...)
pex_binary(...)
```
Due to the vagaries of how `./pants run` happens to work today, all `pex_binary` targets here share the same code (none) and deps but each has a different entrypoint.

**Comment by Eric-Arellano** [comment]
Hm, they should not have the same code in build-support/bin. You're seeing differently? (I haven't tested now, afk)

**Comment by jsirois** [comment]
Clarified its `./pants run ` that's the problem. In that case no code is added to the PEX file. Its adjoined loose.
