### ISSUE TITLE
pex can't handle environment markers in requirements file

### ISSUE THREAD

**Issue by chassing** [pantsbuild/pex#122]
I have following requirements.txt:

```
path.py==5.0; python_version < '3.0'
```

pex raises following exception:

```
... pex/requirements.py",> line 78, in requirements_from_lines ...
UnsupportedLine: Could not resolve line: path.py==5.0; python_version < '3.0' (Unknown requirement type: path.py==5.0; python_version < '3.0')
```

**Comment by burrows-labs** [comment]
+1

**Comment by jsirois** [comment]
> 3 years later, environment markers are still unsupported.
Some good attitude in an OSS setting goes a  long way. If 3 years was truly a burden you might have chipped in!

That said, see #592 / #593. The support added in 1.5.0 mistakenly only covered trnasitive requirements, not top-level. #592 fixes that.

**Comment by ironfoot** [comment]
Sorry, I didn't mean to sound passive aggressive.
I started using Pants/PEX recently and just realized this issue was opened 3 years ago.
Thanks for the update. I'll check out the new releases.
