### ISSUE TITLE
Allow duck-typing of Requirement in resolvable.py?

### ISSUE THREAD

**Issue by benjyw** [pantsbuild/pex#124]
https://github.com/pantsbuild/pex/commit/8b7bb05c5ecef5db61ef4f49189d4ecae07a3a70 adds explicit type-checking in function resolvables_from_iterable() in resolver.py: a requirement must be a Resolvable, Requirement, Package or string. 

However Pants uses this method and passes in a PythonRequirement, which is a Pants-specific class that wraps Requirement and duck-types to it. 

So we should consider allowing this method to accept duck types, or change Pants appropriately.

**Comment by jsirois** [comment]
I've already got this fixed up in the upgrade to pex 1.0.0 branch that's waiting on my fix to https://github.com/pantsbuild/pex/issues/120 so I'll take this.

**Comment by jsirois** [comment]
The `resolvable.py` module no longer exists and Pex now accepts only lists of strings or requirement files for requirements so closing this issue as obsolete / fixed.
