### ISSUE TITLE
Allow command-line arguments to be read from a file

### ISSUE THREAD

**Issue by jjhelmus** [pantsbuild/pex#1271]
Various tools, including [gcc](https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html#Overall-Options) and [clang](https://llvm.org/docs/CommandLine.html#response-files), allow command-line arguments to be read from a file.  This is typically done by designating a special character (@) to indicate that the argument is to be interpreted as a file of arguments.  This behavior is helpful when the command-line length may become greater than the maximum size allowed by the system.

Would there be interest in adding the ability to pass command-line argument from a file to pex?  I would be happy to submit a pull request with the needed changes if there is interest. I suspect the needed changes would be minimal as ArgumentParser supports this behavior with its [`fromfile_prefix_chars`](https://docs.python.org/3/library/argparse.html#fromfile-prefix-chars) parameter.  

I know I occasionally have the need to pass a large number of resource directories to the pex command and worry about reaching the limits of my systems command-line length.

**Comment by jsirois** [comment]
SGTM! Thanks @jjhelmus.
