### ISSUE TITLE
Modules import with and without entry point

### ISSUE THREAD

**Issue by Semyazz** [pantsbuild/pex#129]
at the beginning I want to say, I'm new to PEX, but it looks brilliant to me, however I'm struggling with one thing, which will be probably obvious to you.

I want to pack multiple modules in a single PEX to create something like busybox-like. For instance some libraries with execs like `mkdocs` from `mkdocs`, so I generate PEX using

    pex pex mkdocs -c pex -o all-in-one.pex

then I can run all executables from modules by:

    all-in-one.pex -c mkdocs mkdocs

but when I simply run `all-in-one.pex`, I will be in a bare python interpreter and I cannot `import mkdocs`. When I add all modules after that, so `all-in-one.pex mkdocs <other modules>` then I see it's loaded at the beginning (verbose mode with modules listed) and it's available in the interpreter. But I don't want to type all modules always. I'd like all of them to be pre-loaded automatically or use a wildcard to load some of them or just import them at will in that interpreter.

On the other hand, when I generate PEX without an entry point

    pex pex mkdocs -o all-in-one.pex

and when I run it, all modules seems to be pre-loaded automatically, even without verbose message  which indicates which (all) were loaded and I can `import` all of them in python interpreter which is spawned when it's executed, but then I can't run execs from modules :-( or I don't know how to run them..

Is it designed this way? or am I doing something wrong when I try to generate it with `pex` as entry point and try to import modules in the interpreter without explicitly listing all required modules.

**Comment by wickman** [comment]
I think there's a little bit of confusion.  Since you made '-c pex' the default entry point for all-in-one.pex, the "drop-into-interpreter" behavior is that of pex creating an empty environment, not dropping into the environment of all-in-one.pex.

For example, you can do the following instead:

```bash
$ pex pex mkdocs -o all-in-one.pex

$ PEX_SCRIPT=mkdocs ./all-in-one.pex --help
Usage: all-in-one.pex [OPTIONS] COMMAND [ARGS]...

  MkDocs - Project documentation with Markdown.

Options:
  -V, --version  Show the version and exit.
  -q, --quiet    Silence warnings
  -v, --verbose  Enable verbose output
  -h, --help     Show this message and exit.

Commands:
  build      Build the MkDocs documentation
  gh-deploy  Deply your documentation to GitHub Pages
  json       Build the MkDocs documentation to JSON files...
  new        Create a new MkDocs project
  serve      Run the builtin development server

$ PEX_SCRIPT=pex ./all-in-one.pex --help
Usage: all-in-one.pex [-o OUTPUT.PEX] [options] [-- arg1 arg2 ...]

all-in-one.pex builds a PEX (Python Executable) file based on the given specifications: sources, requirements, their dependencies and other options.

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -o PEX_NAME, --output-file=PEX_NAME
                        The name of the generated .pex file: Omiting this will
                        run PEX immediately and not save it to a file.
```
etc.

**Comment by wickman** [comment]
I think this one was answered sufficiently.  Please reopen if there is still any confusion.
