### ISSUE TITLE
Support a direct execution entry point mode.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1305]
Currently Pex does not support `python my/file.py` style execution. Instead you would tell pex `--entry-point "my.file"`. This almost always is fine, but in the important case of Django apps, importing `my.file` as a module can cause load order issues that cause Django to crash; whereas, executing `my/file.py` directly does no module importing up front, avoiding issues.

A sketch might be:
1. `pex --entrypoint my/file.py -o my.pex`
2. `pex --entrypoint my/file.py -D src/ -o my.pex`
3. `pex --entry-point src/my/file -D src/ -o my.pex`

In case 1 the file must exist at `$PWD/my/file.py` and will be added to the pex as `my/file.py`.
In case 2 ... a few different semantics could be chosen.
In case 3 the file must exist at `$PWD/src/my/file.py` and will be added to the pex as `my/file.py` along with the rest of the content in `src/`.

At runtime - Pex would ensure at least the file to execute was extracted to disk so that a `python my/file.py` execution could be done.

**Comment by kaos** [comment]
Related to #1379 
If all scripts from `setuptools.setup()` where executed as a subprocess, this would work right away.

**Comment by jsirois** [comment]
How about scripts with a python shebang and 3rdparty deps in the PEX file?

**Comment by kaos** [comment]
Hrrrm. Right, my comment came out wrong, my bad, apologies. It should've been phrased more like an suggestive question rather than a statement claiming that I know all there is on this topic, which I don't.

So, I take it from your come back question, that those 3rdparty files will be inaccessibly trapped in the PEX archive. Is this always the case, or would it be possible to unpack the archive before executing the script, with an environment setup so that those files are discoverable?

**Comment by jsirois** [comment]
The appropriate front-end for this was added in #1807 with the introduction of the `--exe EXECUTABLE, --executable EXECUTABLE, --python-script EXECUTABLE` option. The backend though still uses the entrypoint import execution method. It should be both backwards compatible and solve this issue to instead use the existing PEX script execution method behind the scenes.

**Comment by jsirois** [comment]
Actually, I think #1807 fixed this since the `--exe` option takes whatever the pointed-to script is and stores it as the `__pex_executable__.py` top-level module. Importing this to execute it then imports no surrounding package code since there is no package.

**Comment by jsirois** [comment]
I'm marking this as (unwittingly) closed by #1807.
