### ISSUE TITLE
pex fails with uwsgi

### ISSUE THREAD

**Issue by lsmag** [pantsbuild/pex#132]
Hi,

I tried `pex -r requirements/production.txt -c uwsgi -o myapp.pex` and got the following error:

    Traceback (most recent call last):
      File "/home/user/.virtualenvs/mypackage/bin/pex", line 11, in <module>
        sys.exit(main())
      File "/home/user/.virtualenvs/mypackage/lib/python3.4/site-packages/pex/bin/pex.py", line 509, in main
        pex_builder = build_pex(reqs, options, resolver_options_builder)
      File "/home/user/.virtualenvs/mypackage/lib/python3.4/site-packages/pex/bin/pex.py", line 486, in build_pex
        pex_builder.set_script(options.script)
      File "/home/user/.virtualenvs/mypackage/lib/python3.4/site-packages/pex/pex_builder.py", line 209, in set_script
        raise self.InvalidExecutableSpecification('Could not find script %s in PEX!' % script)
    pex.pex_builder.InvalidExecutableSpecification: Could not find script uwsgi in PEX!

In that case uwsgi is `uWSGI==2.1.10`, the most recent version at this date. I assume I must use `-c executable` in order to deploy a web application, right? So then I call my PEX passing my wsgi file.

**Comment by kwlzn** [comment]
`-c uwsgi` would imply that running `python setup.py install` in an uwsgi sdist would provide a `uwsgi` executable. it does not. uwsgi is actually a C project and the `uwsgi` binary is an artifact of the project compilation. the bit provided by uwsgi's setup.py is simply a helper library for use within the uwsgi runtime context.

**Comment by lsmag** [comment]
That's sad, is there any way to work around this limitation?

Anyway, even though uwsgi isn't a typical Python project, it is served by PyPI and used regularly by other python projects, wouldn't it be nice if PEX allows it as an entrypoint? (I don't know the complexity of this, of course).

**Comment by sixninetynine** [comment]
By the very nature of entry points ([a script wrapper for a python callable](https://pythonhosted.org/setuptools/setuptools.html#automatic-script-creation])) this would be impossible, since (as stated) uwsgi is a compiled C binary. 

I don't know much about uwsgi, but wouldn't the proper way to run a pex'd webapp with uwsgi be something like:

    uwsgi --http :9090 --wsgi-file foobar.pex

where `foobar.pex` is the result of pex'ing a python webapp with -e <entrypoint of webapp>

**Comment by jwestboston** [comment]
@sixninetynine The --wsgi-file foobar.pex method doesn't work as uwsgi is attempting to load foobar.pex as if it is a normal .py script.  It doesn't run/execute foobar.pex.

I'm also interested in a way to run a pex bundled app with uwsgi.  Would be incredibly useful.

**Comment by kwlzn** [comment]
to run a pex'd application in uwsgi, you can globally inject pex bootstrapping code via uWSGI's import (e.g. `--import bootstrap.py`) option. you need some way to pass the path of the target pex(es) to the bootstrapper such as an environment variable etc (tho uwsgi may offer a cleaner alternative to this via one of its many options). from there, you you can simply pass in an application module (e.g. `--module your.import.namespace:app`) and uWSGI will load and run the given app from within the pex.

here's an example bootstrapper: https://github.com/kwlzn/pyuwsgi_pex/blob/master/pyuwsgi/resources/bootstrap.py

and fwiw https://github.com/kwlzn/pyuwsgi_pex bundles this all up into a tidy python module that embeds uwsgi and the bootstrap bit. this allows for a single-artifact deployable that can bootstrap uwsgi and run an entrypoint within itself - tho it does not provide a uwsgi execution example.

**Comment by jwestboston** [comment]
@kwlzn Wow very cool.  I will hopefully be able to test out the first option (bootstrap.py) tonight.

Hope some day UWSGI natively supports pex so we don't have to use any workarounds.

**Comment by jwestboston** [comment]
@kwlzn So, this *almost* works.  I'm only running into an issue because my pex file has a newer version of the "six" python module.  OS has six 1.3.0 and the pex has six 1.9.0 installed.  For some reason when using the bootstrap script, the OS's site-packages has precedence and six 1.3.0 gets imported.  But when running the .pex file manually, and importing six, then I see 1.9.0.

And... unfortunately I need the newer version of the six module.  (I'm using the falcon framework if you're curious, which wants a newer six).

**Comment by jwestboston** [comment]
@kwlzn This reminds me of virtualenvs and how one can specify to ignore the site-packages, so basically any/every module one is able to use must be contained in the virtualenv.  Is there a way to do this with pex?  Or trick pex into doing this with the bootstrap.py?

**Comment by jwestboston** [comment]
@kwlzn Is the right way to handle this to just put this at the bottom of the bootstrap.py script:

sys.path.remove('/usr/lib/python2.7/site-packages')

^ maybe I'm getting close??

**Comment by wickman** [comment]
The code to scrub sys is in the PEX class:

```python
from pex.pex import PEX
sys.path, sys.path_importer_cache, sys.modules = PEX.minimum_sys()
```

This is somewhat dangerous as it might pull things out of your environment that you expect (e.g. uwsgi) but if your pex file is complete maybe it will work fine.

**Comment by jwestboston** [comment]
@wickman Thanks for the tip(s).  I was indeed seeing issues with your first suggestion but your edit with patch_dict() and patch_all is working.  Great!

I'm guessing there's something special about the sys modules attributes to Python, in that they are referenced elsewhere, so just making a new variable containing those values will cause oddball behavior, yeah?

I'm thinking pex should support this type of operation natively ... the abillity to easily specify whether a pex environment should include site-packages or not include site-packages, like how virtualenv has this feature.

**Comment by jwestboston** [comment]
@kwlzn and @wickman   Many, many, many thanks for your help!

**Comment by jwestboston** [comment]
@wickman My bad regarding making this a pex feature.  Looks like pex already removes site-packages.  This is just an affecting bootstrapping, for use with stuff like uwsgi.
