### ISSUE TITLE
Is there overlap between pex & py3.5's zipapp?

### ISSUE THREAD

**Issue by sixninetynine** [pantsbuild/pex#133]
https://docs.python.org/3.5/whatsnew/3.5.html#zipapp

I've been out of the loop on python 3+ for a while, but this zipapp feature seems to be almost completed lifted from pex, or is there some difference that I'm missing?

**Comment by wickman** [comment]
zipapp doesn't actually construct or manipulate the contents of the application directory for you; that's what pex does.  however, you could in theory do something like:

```bash
$ pex ipython -c ipython -o ipython.pex
$ unzip -q -d ipython ipython.pex
$ python3.5 -m zipapp ipython
$ python3.5 ipython.pyz
```

zipapp is an acknowledgement that shebang zips are interesting.  pex could use zipapp for the final step of actually zipping up the pex archive, but why bother when zipapp only supplants ~10 lines of code in pex and is 3.5-only?

**Comment by sixninetynine** [comment]
Roger that, I figured there was some deficit around the fact that pex understands and works with setuptools products. zipapp seems to be less intelligent about what you are trying to package.

Cool!

**Comment by oxf1** [comment]
@wickman  I want to konw if python3.5 zipapp can package all the dependency 3party module automatically?  like java fat exectuable jar that include all needed 3party jars.

**Comment by meoyawn** [comment]
> @wickman I want to konw if python3.5 zipapp can package all the dependency 3party module automatically? like java fat exectuable jar that include all needed 3party jars.

yes I use https://github.com/linkedin/shiv for that
