### ISSUE TITLE
Python pex pex.environment.ResolveError

### ISSUE THREAD

**Issue by aishvarya** [pantsbuild/pex#1362]
I was trying to bundle my application into pex file for deployment. Using the following command to bundle it;
`pex . -v --disable-cache -r requirements.txt -o app.pex`
Running the pex locally works fine for me
`./app.pex -m app.main  # this works fine on my shell`

But when I am trying to run pex when trying to create a Docker image it throws the following error; stack trace

> #13 3.214 Traceback (most recent call last):
#13 3.214   File "/app.pex/.bootstrap/pex/pex.py", line 483, in execute
#13 3.214   File "/app.pex/.bootstrap/pex/pex.py", line 139, in activate
#13 3.214   File "/app.pex/.bootstrap/pex/pex.py", line 126, in _activate
#13 3.214   File "/app.pex/.bootstrap/pex/environment.py", line 428, in activate
#13 3.214   File "/app.pex/.bootstrap/pex/environment.py", line 784, in _activate
#13 3.214   File "/app.pex/.bootstrap/pex/environment.py", line 608, in resolve
#13 3.214   File "/app.pex/.bootstrap/pex/environment.py", line 629, in resolve_dists
#13 3.214   File "/app.pex/.bootstrap/pex/environment.py", line 573, in _root_requirements_iter
#13 3.214 pex.environment.ResolveError: A distribution for pyyaml could not be resolved in this environment.Found 1 distribution for pyyaml that do not apply:
#13 3.214 1.) The wheel tags for PyYAML 5.4.1 are cp38-cp38-macosx_10_9_x86_64 which do not match the supported tags of DistributionTarget(interpreter=PythonInterpreter('/usr/local/bin/python3.8', PythonIdentity('/usr/local/bin/python3.8', 'cp38', 'cp38', 'manylinux_2_28_x86_64', (3, 8, 5)))):

In my requirements.txt, I have added a requirement for 'PyYAML==5.4.1'. Looks like it's unable to find the wheel tag 'cp38-cp38-macosx_10_9_x86_64' in the distribution targets. My guess is because I bundled my pex package locally on macos, and the docker is trying to create the image on linux vm it's causing some issues? How can I get around it? Tried passing along the argument `--platform linux-x86_64-cp-37-cp37m` while building the pex but same issue.

My Dockerfile looks something like this

> RUN apt update && apt install -y \
>     python3 \
>     python3-dev \
>     python3-pip \
>     python3-wheel \
>     vim \
>     less \
>     && rm -rf /var/lib/apt/lists/*
> 
> COPY requirements.txt /tmp/requirements.txt
> RUN pip3 install -r /tmp/requirements.txt
> 
> COPY target /opt/app/target
> WORKDIR /opt/app
> 
> RUN target/app.pex -m app.main

**Comment by aishvarya** [comment]
So I was able to get it to work by creating the pex build in a linux VM and then using that to create the docker image. Not really sure if/how can I do it from mac os.

**Comment by jsirois** [comment]
Yeah - Pex does no magic (cross-building), so you need to supply it pre-built wheels when you use a foreign `--platform`. So, to build a multiplatform Pex for macOS and Linux from a mac you need to 1st pre-build all the required distributions on a Linux box / vm / container and then make those available to PEX via --repo or --index (--repo is usually easier since it can just point to a directory containing all the wheels on the filesystem or else served up by an HTTP(s) server that can generate an index.html for a directory.

**Comment by jsirois** [comment]
@aishvarya I'm going to close this as answered, but please speak up if you have further questions.
