### ISSUE TITLE
the command 'python setup.py bdist_pex --bdist-dir=dist --bdist-all' does not work with pex 2.1.43

### ISSUE THREAD

**Issue by s-binetruy-criteo** [pantsbuild/pex#1382]
Hello,

It seems the -bdist-all is not supported by the latest version '2.1.43', the following command generates only the pex for the first entry_point.

`python setup.py bdist_pex --bdist-dir=dist --bdist-all --pex-args='--disable-cache --index-url=https://xxxxx/repository/pypi/simple'`
Can you confirm it is bug or the issue on my side.
Thanks

**Comment by s-binetruy-criteo** [comment]
Hello I suggest to change the line 138 in commands/bdist_pex.py
'print" instead of 'die'

**Comment by jsirois** [comment]
Fixed by #1396.

**Comment by s-binetruy-criteo** [comment]
Hello Folks
Sorry I was off for a few days,
Thanks for the fx
