### ISSUE TITLE
Running a pex from a cron job

### ISSUE THREAD

**Issue by sureshjoshi** [pantsbuild/pex#1399]
I'm currently running into a strange problem, easily worked around - but I was curious if anyone else was having this problem. 

I have the following cronjob on Debian 10.10

`*/2 * * * * /usr/local/sbin/myapp.pex >> /var/log/myapp/mylog.log 2>&1`

The only entries I see, every 2 minutes are:

`/usr/bin/env: ‘python3.9’: No such file or directory`

I've done an altinstall of python3.9, so it's located at `/usr/local/bin/python3.9` and when I login as root and manually run the .pex files, everything works as expected. It only fails in the cronjob.

Running this works perfectly (unsurprisingly):

`*/2 * * * * /usr/local/bin/python3.9 /usr/local/sbin/myapp.pex >> /var/log/myapp/mylog.log 2>&1`

**Comment by sureshjoshi** [comment]
Just realized that by default, cron's PATH is basically empty - closing, but leaving this ticket in for posterity... and shame...

**Comment by Eric-Arellano** [comment]
No shame here, we've all been stumped by things like this :) I'm glad it's working now.
