### ISSUE TITLE
Reproducibility of `pex-tools extract`

### ISSUE THREAD

**Issue by stuhood** [pantsbuild/pex#1408]
`pex-tools $file extract -f $dest` currently creates output wheels with internal timestamps tied to their creation time, rather than zeroed or cloned from the producing PEX.

**Comment by jsirois** [comment]
> or cloned 

Since a PEX does not contain wheels but, instead, installed wheels, the wheels produced by extract cannot be cloned.

**Comment by jsirois** [comment]
The fix is exporting `SOURCE_DATE_EPOCH` when packing the wheel:
https://github.com/pypa/wheel/blob/41b375ef33e3368f6f58c13f9649491d01c2ba5e/src/wheel/wheelfile.py#L24-L28
