### ISSUE TITLE
pex pip resolver fails if a dependency is specified differently for different platforms

### ISSUE THREAD

**Issue by vitalihs** [pantsbuild/pex#1415]
Hello there,

We recently bumped pex from 2.1.24 to 2.1.45 and now we observe problem with the following requirements file:

```
$ cat requirements.txt
https://<internal hostname>/pip/ray-0.8.4-cp37-cp37m-linux_x86_64.whl; sys_platform == 'linux'
ray==0.8.4; sys_platform == 'darwin'
```

when we call pex like this:

```
$ pex -r requirements.txt
Traceback (most recent call last):
  File "/Users/vitali/.pyenv/versions/pex-bug/bin/pex", line 8, in <module>
    sys.exit(main())
  File "/Users/vitali/.pyenv/versions/3.7.9/envs/pex-bug/lib/python3.7/site-packages/pex/bin/pex.py", line 1149, in main
    pex_builder = build_pex(options.requirements, options, cache=ENV.PEX_ROOT)
  File "/Users/vitali/.pyenv/versions/3.7.9/envs/pex-bug/lib/python3.7/site-packages/pex/bin/pex.py", line 1045, in build_pex
    ignore_errors=options.ignore_errors,
  File "/Users/vitali/.pyenv/versions/3.7.9/envs/pex-bug/lib/python3.7/site-packages/pex/resolver.py", line 1055, in resolve_multi
    ignore_errors=ignore_errors, workspace=workspace, max_parallel_jobs=max_parallel_jobs
  File "/Users/vitali/.pyenv/versions/3.7.9/envs/pex-bug/lib/python3.7/site-packages/pex/resolver.py", line 727, in install_distributions
    for index, direct_req in enumerate(direct_reqs)
AssertionError: More than one direct requirement is satisfied by ray 0.8.4:
0. ray
1. ray==0.8.4; sys_platform == "darwin"
This should never happen since Pip fails when more than one requirement for a given project name key is supplied and applies for a given target interpreter environment.
```

Let me provide details around our specifiers for `ray` package. For the linux environments (production installations run on linux) we use an internally built wheel, because we fixed a bug in ray which is still not fixed in their official version.
For local development on MacOS we're fine to work with the stock ray package, because this bug has only performance implications.

The workaround which I applied is to change our requirements file to download the ray package for both linux and darwin from a https url, something like this:

```
$ cat requirements.txt
https://<internal hostname>/pip/ray-0.8.4-cp37-cp37m-linux_x86_64.whl; sys_platform == 'linux'
https://<internal hostname>/pip/ray-0.8.4-cp37-cp37m-macosx_10_13_intel.whl; sys_platform == 'darwin'
```

Thank you,
Vitali

**Comment by jsirois** [comment]
Thanks for reporting this @vitalihs - the issue is in Pex's requirement parser. It does not retain the environment marker for requirements of the form `https?://...; <marker>` like you're using here. This is easy to repro so I'll get a fix up today.

**Comment by vitalihs** [comment]
Hey @jsirois,

Thank you for the quick fix and for the new release!

Vitali
