### ISSUE TITLE
How to include .so files (shared libaries) 

### ISSUE THREAD

**Issue by delijati** [pantsbuild/pex#1429]
Hi is there a way to include *.so files (the one that come with libasound2-dev libjpeg-turbo8-dev zlib1g-dev libpq-dev). Can i just copy them somewhere and set LD_LIBRARY_PATH ?

**Comment by jsirois** [comment]
@delijati you may be able to do that as a manual step to prepare the target environment to run a PEX file in when the PEX file contains platform specific code that is not fully contained in a wheel / not [multilinux compliant](https://www.python.org/dev/peps/pep-0600/). Currently PEX has no built-in facility to help you do this.

**Comment by jsirois** [comment]
@delijati I'm going to close this as answered, but please feel free to re-open / ask more questions if things aren't clear.
