### ISSUE TITLE
"Exec format error" when invoking a script after building pex with v2.1.51 

### ISSUE THREAD

**Issue by juanitosvq** [pantsbuild/pex#1484]
Hi there,

We recently upgraded the version of pex that we use to build our pex files from `v2.1.42` to the most recent `v2.1.51`.

After building a new pex file with the new version, our application is failing to execute the entry point script:

```
Could not invoke script /udata/root/.pex/installed_wheels/applicationX-0.0.4-py3-none-any.whl/bin/__main__.py: OSError(8, 'Exec format error') while trying to execute `['/udata/root/.pex/installed_wheels//applicationX-0.0.4-py3-none-any.whl/bin/__main__.py', '-vvv', '-c', '/etc/config-file.json']
``` 

I don't think anything else has changed in our side other than the version of pex used to build.

Is this a known breaking change? 

Many thanks in advance, let me know if you need further details.

**Comment by jsirois** [comment]
@juanitosvq can you provide the contents of `/udata/root/.pex/installed_wheels/.../applicationX-0.0.4-py3-none-any.whl/bin/__main__.py` or else have a look inside that file and report what looks off? I suspect the shebang line - 1st line - is not right, but it would help to be able to see what you're seeing.

**Comment by juanitosvq** [comment]
Hi @jsirois thanks for the quick response. 

The first line of our entrypoint script `__main__.py` is actually a triple quote that we are using as multiline comment.

```
"""
Created on Oct 28, 2017
```

Looks like we missed the shebang there. We can just add it, but is it expected that an older version of pex would be able to handle this?

**Comment by jsirois** [comment]
How are you building your pex? Can you provide a command line? The more information you can dump - the better.

**Comment by juanitosvq** [comment]
We are running the following command:
```
pex . -r requirements.txt -c __main__.py -o /home/jenkins/example.pex --disable-cache
```

There is nothing in the output when running this command in either of the two versions of pex.

The content of our `requirements.txt` is:
```
marshmallow==2.13.5
Flask==0.12.2
Flask-API==1.0
Flask-HTTPAuth==3.2.3
tinydb==3.7.0
apispec==0.29.0
PyYAML==3.12
boto3==1.4.7
requests==2.18.4
APScheduler==3.8.0
backoff==1.5.0
werkzeug==1.0.1
```

We are running `setuptools==58.2.0` and `pip==21.2.4` in `python3.6`. 

Not sure if relevant, but our `setup.py` looks something like:
```
setup(
    name='app',
    version=__version__,
    description='description',
    url='http://some_url',

    packages=find_packages(exclude=['docs']),
    include_package_data=True,

    install_requires=['marshmallow==2.13.5', 'Flask==0.12.2', 'Flask-API==1.0', 'Flask-HTTPAuth==3.2.3',
                      'tinydb==3.7.0', 'apispec==0.29.0', 'PyYAML==3.12', 'boto3==1.4.7',
                      'requests==2.18.4', 'APScheduler==3.8.0', 'backoff==1.5.0', 'werkzeug==1.0.1'],
    python_requires='>=3.4',

    extras_require={
        'build': ['wheel', 'make-deb', 'pex'],
        'test': ['pylint', 'nose2', 'moto==1.1.24']
    },
    data_files=[('', ['README.md'])],
    entry_points={
        'console_scripts': [
            'app = app.__main__:main'
        ]
    },
    scripts=['app/__main__.py']
)

```

Our `__main__.py` looks something like:
```
"""
Created on Oct 28, 2017
This is the entry point 

"""
import argparse

def main():
    parser = argparse.ArgumentParser(prog='app')
    # ...


if __name__ == "__main__":
    main()
```

Le me know if there is anything else I can provide you with. 
Thanks!

**Comment by juanitosvq** [comment]
I am okay with adding the shebang in our end, just wanted to make sure that this wasn't an unexpected change. It makes sense that pex is expecting the shebang :+1: 

Thanks for the quick reply, I'll close this.
