### ISSUE TITLE
https://pex.readthedocs.io/ is broken.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1508]
```
$ $ curl -sSL -D- https://pex.readthedocs.io/
HTTP/2 302 
date: Wed, 03 Nov 2021 04:10:09 GMT
content-type: text/html; charset=utf-8
content-length: 0
location: https://pex.readthedocs.io/en/v2.1.54/
x-rtd-redirect: system
x-rtd-domain: pex.readthedocs.io
x-rtd-project: pex
x-rtd-project-method: subdomain
x-rtd-version-method: path
strict-transport-security: max-age=31536000; includeSubDomains; preload
permissions-policy: interest-cohort=()
referrer-policy: no-referrer-when-downgrade
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
vary: Accept-Language, Cookie
content-language: en
x-served: Django-Proxito
x-backend: web-i-0037f2ac8061301b6
cf-cache-status: HIT
age: 94
expires: Wed, 03 Nov 2021 06:10:09 GMT
cache-control: public, max-age=7200
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 6a82c0533a0c525d-LAX

HTTP/2 404 
...
```

**Comment by jsirois** [comment]
Although as @benjyw found https://pex.readthedocs.io/en/v2.1.52/ works. Just 2.1.5{3,4} are broken.

**Comment by benjyw** [comment]
Docs build OK with `tox -e docs`. So this is an upload problem.

**Comment by benjyw** [comment]
Error here: https://readthedocs.org/projects/pex/builds/15144385/

**Comment by benjyw** [comment]
This still works (points to 2.1.52): https://pex.readthedocs.io/en/latest/

**Comment by benjyw** [comment]
Attempting to reproduce locally.

**Comment by benjyw** [comment]
Interestingly, it fails locally when I run on 2.1.52, which succeeded on readthedocs in the past.

**Comment by jsirois** [comment]
Its a docutils issue. I'll pin low.

**Comment by benjyw** [comment]
Yep, docutils 0.18 was released in between the successful and failing runs.

**Comment by jsirois** [comment]
I've re-set the default to latest which un-borks the default re-direct (was still pointing at the broken 2.1.54 docs). I've hidden and deactivated the 2.1.5{3,4} docs. All looks good now.
