### ISSUE TITLE
Support for using cli tools for libraries in pex env

### ISSUE THREAD

**Issue by lcerkovnik** [pantsbuild/pex#1519]
Is there an easy way to use cli tools from a library installed in pex without a separate venv.  an example would be using something like a cookiecutter template https://github.com/drivendata/cookiecutter-data-science where the cookiecutter is installed inside pex and accepts cli arguments with pex?

**Comment by jsirois** [comment]
I'm not sure what you mean by "...and accepts cli arguments with pex...", but here is some toying on the CLI:

1. A Pex of cookiecutter:
```console
$ pex cookiecutter -c cookiecutter -o cookiecutter.pex
$ ./cookiecutter.pex -h
Usage: python -m cookiecutter [OPTIONS] TEMPLATE [EXTRA_CONTEXT]...

  Create a project from a Cookiecutter project template (TEMPLATE).

  Cookiecutter is free and open source software, developed and managed by
  volunteers. If you would like to help out or fund the project, please get in
  touch at https://github.com/audreyr/cookiecutter.

Options:
  -V, --version              Show the version and exit.
  --no-input                 Do not prompt for parameters and only use
                             cookiecutter.json file content
  -c, --checkout TEXT        branch, tag or commit to checkout after git clone
  --directory TEXT           Directory within repo that holds
                             cookiecutter.json file for advanced repositories
                             with multi templates in it
  -v, --verbose              Print debug information
  --replay                   Do not prompt for parameters and only use
                             information entered previously
  -f, --overwrite-if-exists  Overwrite the contents of the output directory if
                             it already exists
  -s, --skip-if-file-exists  Skip the files in the corresponding directories
                             if they already exist
  -o, --output-dir PATH      Where to output the generated project dir into
  --config-file PATH         User configuration file
  --default-config           Do not load a config file. Use the defaults
                             instead
  --debug-file PATH          File to be used as a stream for DEBUG logging
  -h, --help                 Show this message and exit.
$ ./cookiecutter.pex --version
Cookiecutter 1.7.3 from /home/jsirois/.pex/installed_wheels/44a833e149b29f82796f419a5752aee2524dbbbe/cookiecutter-1.7.3-py2.py3-none-any.whl (Python 3.9)
```

2. A bit of custom code that calls the cookiecutter CLI via subprocess:
```console
$ mkdir src
$ cat <<EOF > src/my_entrypoint.py
> from __future__ import print_function
>
> import subprocess
> import sys
> 
> 
> print(">>> Forwarding {} to cookiecutter...".format(" ".join(sys.argv[1:])), file=sys.stderr)
> sys.exit(subprocess.call(["cookiecutter"] + sys.argv[1:]))
> EOF
$ pex cookiecutter -D src -e my_entrypoint --venv append -o my.pex
$ ./my.pex --version
>>> Forwarding --version to cookiecutter...
Cookiecutter 1.7.3 from /home/jsirois/.pex/venvs/s/c09482b9/venv/lib/python3.9/site-packages (Python 3.9)
```

I think you were looking for item 2?

**Comment by jsirois** [comment]
Assuming 2 is what you're looking for, the key is `--venv`. That causes the PEX file to install itself in a venv on 1st execution under `~/,pex/venvs/...` (Or whatever you have the `PEX_ROOT` consifured as) and the `append` argument to `--venv` appends all scripts in that venvs `bin/` to the `$PATH`, which is why the `subprocess.call` works.

**Comment by lcerkovnik** [comment]
Thanks for the detailed and fast response, I think option 1 will actually work for what I am looking for.  I didn't realize that most of the cli entrypoint for a python cli on $PATH in the terminal map over that way into python -m mostly and therefore with pex.   I am trying to add separate pants submodules for different cli tool environments like separate cookiecutter or aws cdk env  as a part of a broader pants monorepo.   That being said, the option 2 is very helpful for understanding how to add pex env to $PATH with --venv and append.

**Comment by Eric-Arellano** [comment]
For Pants integration, you'll want to use 2.8.0+. It added a new `script` field on `pex_binary` to set the `-c` option with PEX. https://www.pantsbuild.org/docs/python-package-goal#the-entry_point-and-script-fields
