### ISSUE TITLE
Requirements list in PEX-INFO does not contain transitive dependencies

### ISSUE THREAD

**Issue by nateagr** [pantsbuild/pex#1531]
Hello there!

While debugging something, I've realized that the list of requirements (values associated to the key "requirements") in PEX-INFO only contains direct dependencies but not transitive dependencies.
For example, when creating the following pex `pex tensorflow==2.4.0 -o test.pex`, only tensorflow==2.4.0 is in the list of requirements in its PEX-INFO:
`... "pex_path": null, "requirements": ["tensorflow==2.4.0"], "strip_pex_env": true ...`
Transitive dependencies of Tensorflow==2.4.0, like Kera_Preprocessing, GRPC, Tensorboard ..., are missing. I'm using PEX==2.1.54.
Is it expected ?

Thanks in advance!

**Comment by jsirois** [comment]
Yes.

**Comment by jsirois** [comment]
Should I lose this as answered @nateagr or did you mean to ask more?

**Comment by nateagr** [comment]
Thanks @jsirois . You can close the topic.
