### ISSUE TITLE
Pex does not support mac universal2 wheels

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1587]
A Pants user [reported](https://github.com/pantsbuild/pants/issues/14244) cryptography being built by Pex instead of its published wheel being used: https://pypi.org/project/cryptography/36.0.1/#files. That wheel is `cryptography-36.0.1-cp36-abi3-macosx_10_10_universal2.whl`.

This was fixed in Pip 21.0.1 here via a packaging upgrade: https://github.com/pypa/pip/commit/00fb5a0b224cde08e3e5ca034247baadfb646468 That is the last version of packaging to support Python 2.7 so we're in luck and can just merge the patch in our fork.

**Comment by thor** [comment]
If necessary, I can test this locally with an M1 device for `pex`. We've recently stumbled into this while trying to make `universal2` compatible executables.

**Comment by jsirois** [comment]
@thor that would be great. The fix is in Pex 2.1.64 to test: https://pypi.org/project/pex/2.1.64/

**Comment by jsirois** [comment]
Missed upgrading Pex's vendored copy: https://github.com/pantsbuild/pants/issues/14244#issuecomment-1021386040
