### ISSUE TITLE
Collisions with README/LICENSE when creating venv

### ISSUE THREAD

**Issue by lcerkovnik** [pantsbuild/pex#1594]
On MacOS and linux ubuntu 18.04 for pex release v2.1.63 there is a false collision error created when creating venv for README.md and LICENSE files of certain dependencies.  This can be worked around with the --collisions-ok argument currently 

pex pex awswrangler==2.13.0 requests-aws4auth==1.1.1 rsa==4.8 pyclustering==0.10.1.2 -c pex -o ~/test.pex
pex-tools ~/test.pex venv testenv --collisions-ok

Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pex/tools/commands/venv.py:137: PEXWarning: Encountered collisions building venv at /Users/logan/Documents/ml_3t/testenv from /Users/logan/test.pex:
1. /Users/logan/Documents/ml_3t/testenv/lib/python3.8/site-packages/README.md was provided by:
        /Users/logan/.pex/installed_wheels/3c1dbbc0882cb6280ff0f73f7ccccd2c3e744a42/awswrangler-2.13.0-py3-none-any.whl/README.md
        /Users/logan/.pex/installed_wheels/3eaa4a3fc57327cab84de285c4557a35408c476d/requests_aws4auth-1.1.1-py2.py3-none-any.whl/README.md
        /Users/logan/.pex/installed_wheels/e7b932d182bccf08c91a10a166624329a5e92bc1/rsa-4.8-py3-none-any.whl/README.md
2. /Users/logan/Documents/ml_3t/testenv/lib/python3.8/site-packages/LICENSE was provided by:
        /Users/logan/.pex/installed_wheels/3eaa4a3fc57327cab84de285c4557a35408c476d/requests_aws4auth-1.1.1-py2.py3-none-any.whl/LICENSE
        /Users/logan/.pex/installed_wheels/43a5f8c9c4453dc0eee792c8383af998491fc7df/pyclustering-0.10.1.2-py3-none-any.whl/LICENSE
        /Users/logan/.pex/installed_wheels/e7b932d182bccf08c91a10a166624329a5e92bc1/rsa-4.8-py3-none-any.whl/LICENSE

**Comment by jsirois** [comment]
> false collision

It is not false. It looks like you don't actually have [v2.1.63](https://github.com/pantsbuild/pex/releases/tag/v2.1.63) which changed the collision detection to check contents and improved the output to show the contents were in fact different:
```
$ pex -V
2.1.65
$ pex-tools -V
2.1.65
$ pex pex awswrangler==2.13.0 requests-aws4auth==1.1.1 rsa==4.8 pyclustering==0.10.1.2 -c pex -o ~/test.pex
$ pex-tools ~/test.pex venv testenv --collisions-ok
/home/jsirois/.venv/pex/lib/python3.10/site-packages/pex/tools/commands/venv.py:230: PEXWarning: Encountered collisions building venv at /home/jsirois/dev/pantsbuild/pants/testenv from /home/jsirois/test.pex:
1. /home/jsirois/dev/pantsbuild/pants/testenv/lib/python3.10/site-packages/README.md was provided by:
	sha1:6fae6b688ab1c4d82342f044685b15e4aed12068 -> /home/jsirois/.pex/installed_wheels/3c1dbbc0882cb6280ff0f73f7ccccd2c3e744a42/awswrangler-2.13.0-py3-none-any.whl/README.md
	sha1:d3b2e6c8edaf5ec69e4a10340ace30c9d9b8de6e -> /home/jsirois/.pex/installed_wheels/50017212094a9dd36d1919f0ac52bc9de0e1769d/requests_aws4auth-1.1.1-py2.py3-none-any.whl/README.md
	sha1:72aad144e976ac1623c8f45f2cf6ca42134ad4b2 -> /home/jsirois/.pex/installed_wheels/2f763a76650991e33049ad828e99b80d41384631/rsa-4.8-py3-none-any.whl/README.md
2. /home/jsirois/dev/pantsbuild/pants/testenv/lib/python3.10/site-packages/LICENSE was provided by:
	sha1:de05ddf9341b56b9c0eee2110eb8ef048d13f96b -> /home/jsirois/.pex/installed_wheels/50017212094a9dd36d1919f0ac52bc9de0e1769d/requests_aws4auth-1.1.1-py2.py3-none-any.whl/LICENSE
	sha1:c524aa1f633ec4f2710ec9d6cc0797f21c3ab668 -> /home/jsirois/.pex/installed_wheels/1f659cea1d46715d54dfd95ff6726859e3486897/pyclustering-0.10.1.2-py3-none-any.whl/LICENSE
	sha1:a4466bfd6f8b645aebdf508c1b7ede0bc018f694 -> /home/jsirois/.pex/installed_wheels/2f763a76650991e33049ad828e99b80d41384631/rsa-4.8-py3-none-any.whl/LICENSE
  pex_warnings.warn(message)
```

In this sort of case there is not much I can see that Pex can do except to offer `--collisions-ok`. Do you have any ideas?

**Comment by lcerkovnik** [comment]
Ah you are correct the wrong pex version was being used and its a warning now in the 2.1.65 instead of an error.  One idea might be to have a black list of filenames to ignore/exclude in the collision detection starting with README.md and LICENSE.  Another alternative would be to whitelist .py , pyx and other python-related files in the collision detection.  I think the blacklist approach might be easier to do.

**Comment by jsirois** [comment]
Well, for LICENSE that actually sounds license violating - in spirit anyway. Certain licenses require you provide the license when distributing and by silently stomping we'll just present the MIT license (for example) and not the GPLv2 license it trampled.

README.md seems much more likely fine to trample, but things get pretty hairy. There is much more than just `.py*`s that are important for dists to function. There could be resource files or `.so`s, etc. I'm pretty loathe to auto-break an application or library in a silent over-write way; so I'm very hesitant here. It's really a few very strange, badly behaved distributions at play here. No one should be including files like those in their binary wheels.

**Comment by jsirois** [comment]
@lcerkovnik I'm going to close this since silently trampling is so troubling for LICENSE and those other cases that might crop up that I'm not anticipating. It truly is the wild west out there in the real packaging ecosystem.

**Comment by lcerkovnik** [comment]
@jsirois  Ok, I think that's a reasonable way to proceed as I originally didn't consider trampling the wild west packaging during collision detection to be so significant.  At least now there is a record of this type of behavior for the future.  Thanks!
