### ISSUE TITLE
doc += a pex can contain artifacts from mult platforms, can work on mult platforms

### ISSUE THREAD

**Issue by lahosken** [pantsbuild/pex#16]
At the risk of revealing how dense I can be: I didn't know you could build a pex that contained both foo-macosx.egg and foo-linux.egg that would work on both osx and linux. I assumed you built a pex per platform. 

The excellent @Yasumoto on the thread https://groups.google.com/forum/#!topic/pants-devel/9yeI4h9xu7k says "Ideally you'll have one pex, which includes dependencies for each of the platforms you need to support..." and I was enlightened.

**Comment by kwlzn** [comment]
this should now be covered by the help output in pex.
