### ISSUE TITLE
Be able to see what .pex file is run from the list of system processes

### ISSUE THREAD

**Issue by alexey-tereshenkov-oxb** [pantsbuild/pex#1604]
**Is your feature request related to a problem? Please describe.**

When running a PEX file:

```
$ python3 dist/project/bar.pex --input="baz"
```

you don’t see much helpful information on `ps ww` command:

```
46131 s010  S+     0:00.78 /usr/bin/python3 /Users/user-name/.pex/unzipped_pexes/e9eb91dcb789973ca601f8bfb4401555f188d841 --input=baz
```

That is, you don't know what `.pex` file is being run by looking at this process.

**Describe the solution you'd like**

The use case is that at a given point of time there may be multiple PEX files running, and it would be handy to see which ones are running from the `ps` output (or somehow else). Perhaps it would be possible to give the unzipped pex a less obscure name. So instead of `unzipped_pexes/2312ebcec214434cf2349791389503f03e1033a7` the PEX could possibly unpack it to `unzipped_pexes/2312ebcec214434cf2349791389503f03e1033a7/bar.pex`.

**Describe alternatives you've considered**

One can inspect the `/Users/user-name/.pex/unzipped_pexes/e9eb91dcb789973ca601f8bfb4401555f188d841/PEX-INFO` file's `entry_point` property to see what module is being run, but this is not visible from the `ps` output directly. This is tedious.

**Additional context**

It's possible that user may have a few long running tasks (started from `.pex` files) and it would be handy to see if any of them are running by doing `ps` and `grep`.

It is possible to set the process title using a 3rd party package (https://pypi.org/project/setproctitle) as well, however, this implies setting it for each `main()` in all the PEXed programs.

https://github.com/pantsbuild/pants/blob/4b335cdccfebcbd1f92caaa5fef7d5ca161c7226/src/python/pants/pantsd/pants_daemon.py#L173-L174

**Comment by jsirois** [comment]
I think the `<PEX_ROOT>/unzipped_pexes/<PEX hash>/<PEX file basename>` idea is good for standard execution mode PEXes. The other case to handle is `<PEX_ROOT>/venvs/<PEX hash>/<interpreter hash>/pex` for `--venv` execution mode PEXes. That should go to `<PEX_ROOT>/venvs/<PEX hash>/<interpreter hash>/<PEX file basename>/pex` to provide the same `<PEX file basename` clue. The venv case is more delicate though since the venv interpreter (`<PEX_ROOT>/venvs/<PEX hash>/<interpreter hash>/<PEX file basename>/bin/python`) gets embedded in the venv `bin/` scripts where it can run into shebang length limits on Mac and Linux.

The arguably better alternative is to add an option to the Pex CLI that allow the user to choose adding an extra platform-specific dependency to their PEX ([setproctitle](https://pypi.org/project/setproctitle)) to get a crisp process name that reflects the path to the PEX file and not the re-execed unzipped or venv PEX.

**Comment by jsirois** [comment]
@alexey-tereshenkov-oxb adding best-effort `setproctitle` use is straight forward. If you add `setproctitle` as a dependency of your PEX you'd then get:
```
$ pex -Dsrc -mapp -o new.pex setproctitle
$ ./new.pex bob jones &
$ ps -ef | grep pex
jsirois    56997    2256  8 10:45 pts/8    00:00:00 /home/jsirois/.pyenv/versions/3.10.2/bin/python3.10 /home/jsirois/dev/pantsbuild/jsirois-pex/new.pex bob jones
```

Versus the current:
```
$ pex -Dsrc -mapp -o old.pex
$ ./old.pex bob jones &
$ ps -ef | grep pex
jsirois    56935    2256 10 10:45 pts/8    00:00:00 /home/jsirois/.pyenv/versions/3.10.2/bin/python3.10 /home/jsirois/.pex/unzipped_pexes/94790b07dc3768a9926dab999b41a87e399e0aa9 bob jones
```

Would that work for you? The only complication I can see is building a multi-`--platform` PEX on Linux for Mac. In that case, there are no Mac wheels published for setproctitle on PyPI and the PEX build would fail. The other way around (building a multi-`--platform` PEX for Linux on Mac) would work just fine. To be able to build a multi-`--platform` PEX on Linux for Mac you'd need to pre-build the Mac wheel(s) for `setproctitle` by hand and host them in a custom `--index` or `--find-links` repo.

Either way, I'll add this feature, but if it doesn't work for your case, I'll also add the `<PEX_ROOT>/unzipped_pexes/<PEX hash>/<PEX file basename>` feature you suggested.

**Comment by alexey-tereshenkov-oxb** [comment]
Thanks @jsirois, this is great. I think using `setproctitle` should work for us. Thanks so much for looking into this; this is arguably a convenience only thing -- it's still possible to look into the unpacked directory entry point. So please don't add any of this if this will add unnecessary complexity, it's not worth it!

**Comment by jsirois** [comment]
Ok - execllent. The setproctitle path is actually simpler and with no impact to any existing use-cases since it's best-effort. IFF `setproctitle` is part of your PEX requirements (directly or indirectly), is this convenience activated. The hardest bit is the test!
