### ISSUE TITLE
Cannot execute wheel

### ISSUE THREAD

**Issue by nickbreen** [pantsbuild/pex#1635]
Expected to be able to execute pex via it's wheel package.

Given:

    PEX_WHEEL=pex-2.1.67-py2.py3-none-any.whl

Executing `--help` fails:

    python3.6 $PEX_WHEEL/pex --help

> ModuleNotFoundError: No module named 'pex.common'; 'pex' is not a package

Adding the wheel to the `PYTHONPATH` works for `--help`:

    PYTHONPATH=$PEX_WHEEL python3.6 -m pex --help
    
But not when attempting to execute it proper:

    PYTHONPATH=$PEX_WHEEL python3.6 -m pex -o pex.pex -m pex --no-pypi --repo $PEX_WHEEL pex
    
> Failed to spawn a job for /usr/bin/python3.6: Expected the `pex` module to be available via an installed distribution or else via an installed or loose PEX.
> Loaded the `pex` module from [PEX_WHEEL]/pex and argv0 is [PEX_WHEEL]/pex/__main__.py.
    
Unpacking the wheel first appears to work though:

    WHEEL_WHEEL=wheel-0.37.1-py2.py3-none-any.whl
    python3.6 $WHEEL_WHEEL/wheel unpack $PEX_WHEEL
    PYTHONPATH=pex-2.1.67 python3.6 -m pex --help
    PYTHONPATH=pex-2.1.67 python3.6 -m pex -p pex.pex -m pex --no-pypi --repo $PEX_WHEEL pex

**Comment by jsirois** [comment]
@nickbreen if any wheel is executable, it is so by luck. See: https://www.python.org/dev/peps/pep-0427/#is-it-possible-to-import-python-code-directly-from-a-wheel-file

Unlike eggs (https://www.python.org/dev/peps/pep-0427/#comparison-to-egg), which were both a distribution and execution format, wheels are only intended for distribution. They must be installed once distributed to the target machine, for example, with `pip install my.whl`. Once you install the Pex wheel, the environment you install it in will have a `pex` script also installed. You run that:
```
$ python -mvenv pex.venv
$ source pex.venv/bin/activate
(pex.venv) $ pip install pex
(pex.venv) $ pex --version
2.1.68
```

If you'd like to be able to run `pex` directly without an install step, you can download a Pex PEX from our releases and run that:
```
$ curl -sSL -O https://github.com/pantsbuild/pex/releases/download/v2.1.67/pex
$ chmod +x ./pex
$ ./pex -V
2.1.67
```

If I've overstepped my bounds and you understood  that wheels were not generally usable this way, but Pex had worked that way for you in the past, my apologies. In short though, this was unsupported behavior.

**Comment by jsirois** [comment]
@nickbreen I'm going to close this as answered, but please continue with any more questions if you need further clarification.

**Comment by nickbreen** [comment]
Thanks! I'm new to python and "you're doing it wrong" is entirely acceptable ;-)
