### ISSUE TITLE
Clarify `pex3 lock export` command.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#1645]
Both #1404 and #1405 are difficult problems to solve in order to have a `pex3 lock export` command that works without caveats (i.e.: that exports a universal lock as a universal requirements.txt). The `pex3 lock export` command should be better documented and possibly modified to explicitly support only exporting to one (or maybe more) explicit local interpreters or foreign platforms.

**Comment by Eric-Arellano** [comment]
+1. `lock export` would be neat and useful if future readers are motivated to solve it (requiring https://github.com/pantsbuild/pex/issues/1404 and https://github.com/pantsbuild/pex/issues/1405). In the meantime, I agree it's not worth it.

Thanks!

**Comment by jsirois** [comment]
@Eric-Arellano can you explain how it would be useful? IIUC it would be useful only if you are not using Pex. IOW this would be Pex stepping for Pip to ~support `pip lock`. It wouldn't actually though since its a very specific vendored version of Pip only and with #1404 and #1405 solved it would _still_ lack support for VCS and local projects. So it would be a half-baked hack fwict.

**Comment by Eric-Arellano** [comment]
To be clear, I am not lobbying at all for keeping `pex3 lock export`. That's a great idea to get rid of it and simplify things. +1.

I'm only offering for any future readers that if they are really motivated to solve these hard problems, we'd at least welcome a discussion about whether the project would add back an export command.

--

> can you explain how it would be useful? 

For the same reason that Poetry and pipenv have export commands: interop with the rest of Python ecosystem. Not mission-critical, but convenient.

I believe this would essentially make Pex's lockfile generation a direct competitor to `pip-tools`, which indeed is not a priority for the project.

>  it would still lack support for VCS and local projects. 

True. Fwit, Poetry has the option to strip hashes, and we could possibly do that so to work around the `--hash` problem for VCS requirements fwict. But of course, that's a less secure lock.

**Comment by jsirois** [comment]
> For the same reason that Poetry and pipenv have export commands: interop with the rest of Python ecosystem.

This is pretty vague. Fwict the lingua franca of interop is the venv and Pex already has tools to create those. It would be great to have a 1st party use case report of where a requirements.txt format file is what is needed and not a venv created from it. Maybe you have one of those use cases but I have none. Every tool I use understands venv no matter who creates it, Poetry, Pipenv or Pex. If there is actually a case where interop is furthered by a requirements.txt format file and not a venv created from it it would be good to know if that requirements.txt format file needed to be faithful to the lock; i.e.: for a universal lock a complicated "universal" requirements.txt acheived through environment markers and thus necessitating #1404 and #1405 or just a requirements.txt that worked for a specific local interpreter. That latter is tractable.

**Comment by thejcannon** [comment]
As a datapoint I'm using Pants and incrementally going from Bazel to Pants. The Python Bazel rules don't (and likely never will) support PEX's lockfile, but does support `requirements.txt`. So until I'm fully on Pants, I 100% need both files to exist. But more importantly **they need to have the exact same versions**, otherwise I'm opening Pandora's Box.

So I'm either going to have to convert from `requirements.txt` to PEX lockfile, or vice-versa. The former involves running `pip-tools` then running `pex lock`, whereas the latter  only requires `pex`.

**Comment by Eric-Arellano** [comment]
Can you use pants export to create  venv, then use pip freeze?

**Comment by thejcannon** [comment]
There's tons of "other ways" I could solve this. `pex export` was simply the easiest :smile:

**Comment by Eric-Arellano** [comment]
pex export doesn't attempt to handle environment markers so it often won't work, like if a dep should only be used for macOS

**Comment by jsirois** [comment]
@thejcannon to sharpen this up a bit more - the only issue with export is `--style universal` locks. These are the most "convenient" and what people have been trained to use by tools like Poetry, but they are otherwise problematic (they are insecure since they include source distributions). Pex can perform perfect fidelity export for `--style strict` and `--style sources`; so I could imagine keeping the feature for those styles. As Eric points out though, to support `--style universal` requires gymnastics using environment markers that might not even be possible in any reasonable way given Pex's role as a bystander controlling Pip and not a resolver itself.

**Comment by jsirois** [comment]
I'm going to modify the OP to narrow to dropping support for exporting universal locks as universal requirements.txt. Simply exporting for one (or possibly more) explicit interpreters regardless of the style the lock was originally created in - which is what is basically done now - makes sense.
