### ISSUE TITLE
Release 1.1

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#165]
Planning on doing this Friday afternoon 10/9

**Comment by jsirois** [comment]
Grab #128 and #162, possibly take a stab at #28, but push back to next release milestone otherwise.

**Comment by rouge8** [comment]
Any chance an updated #61 could get in? I've been keeping that up to date on our fork: https://github.com/pantsbuild/pex/compare/master...redjack:native-libs

**Comment by jsirois** [comment]
Yes - just make sure its showing no merge conflicts before Friday am.  I'll try to give a close review before then though.

**Comment by rouge8** [comment]
Awesome, thanks! (#166)

**Comment by jsirois** [comment]
OK - #128 and #162 are in.  I've punted #28 to https://github.com/pantsbuild/pex/milestones/1.2 after some investigation.  Wickman put the brakes on #166 so I'm not going to include that.

**Comment by jsirois** [comment]
Released: https://pypi.python.org/pypi/pex/1.1.0
