### ISSUE TITLE
Write a small release script

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#172]
There are currently 3 bits, it would be nice to have 1 script:
1. Tagging the release, eg: `git tag -am 'Release 1.1.0' v1.1.0`
2. `python setup.py sdist bdist_wheel upload --sign`
3. Hand crafting the github release and uploading the results of
   
   ```
   tox -e py27-run -- . wheel requests -cpex -opex27
   tox -e py34-run -- . wheel requests -cpex -opex34
   ```
   
   The end-product being one of these: https://github.com/pantsbuild/pex/releases/tag/v1.1.0

**Comment by Eric-Arellano** [comment]
Releases are now automated via GitHub
