### ISSUE TITLE
`Failure to resolve compatible distributions` with requirements file generated by pip-tools

### ISSUE THREAD

**Issue by Djailla** [pantsbuild/pex#1726]
Hello fellow PEX maintainers,

First a big thank for your project that is widely used in `Criteo` company to distribute our Python applications :)

Let me present you the issue I'm facing when using both PEX and pip-tools on some projects.
It did create a dummy project to highlight my issue and to allow to reproduce my bug : https://github.com/Djailla/pex_bug

Env :
- python 3.9
- latest pex release
- latest pip-tools release

Thanks in advance for the support

Bastien (alias @Djailla)

**Comment by jsirois** [comment]
Hrmph. Jaroco is just having fun flouting quirks of the rules for package names. Note the dash vs dot:
```
jaraco-functools==3.5.0 but jaraco.functools
```

I'll dig a bit more to see exactly how Pex is getting this wrong. I think it deals with `[_.-]` normalization in project names at least some places.

**Comment by jsirois** [comment]
@Djailla to work around you can pass `--ignore-errors`, but this also looks like a quick fix. I'm pretty sure I can get out a 2.1.81 release with the proper fix today.

**Comment by Djailla** [comment]
@jsirois my local fix was to replace `.` by `-` for the jaroco related packages, there is no rush, I can wait for a future release. Thanks a lot for the quick answer !
