### ISSUE TITLE
Error when parsing a .netrc file with a possibly nonstandard token

### ISSUE THREAD

**Issue by benjyw** [pantsbuild/pex#1762]
My ~/.netrc file has 

```
machine github.com
  login benjyw
  password <redacted>
  protocol https
```

The `protocol` token isn't mentioned in any netrc documentation that I can find, but it is mentioned in some github-specific snippets online. I presumably have it there for that reason, by cargo-culting.   

Anyway, our netrc parsing chokes on this with:

```
  File "pex/auth.py", line 67, in iter_entries
    for machine, (login, _, password) in netrc(netrc_path).hosts.items():
  File "/Users/benjyw/.pyenv/versions/pypy3.7-7.3.9/lib-python/3/netrc.py", line 30, in __init__
    self._parse(file, fp, default_netrc)
  File "/Users/benjyw/.pyenv/versions/pypy3.7-7.3.9/lib-python/3/netrc.py", line 111, in _parse
    file, lexer.lineno)
netrc.NetrcParseError: bad follower token 'protocol' (/Users/benjyw/.netrc, line 4)
```

Removing that `protocol https` line fixes this, and I have yet to see that this has caused any issues accessing github. 

I'm not sure how widespread this sort of issue might be, and therefore whether we want to somehow deal with it or just recommend that people fix up their netrc.

So I suggest that for now we don't do anything, and wait and see how many early adopters hit this. I'm filing this issue just so we have it tracked prior to stabilizing Pants 2.13, which uses this functionality.

**Comment by jsirois** [comment]
Since its likely you won't even need the netrc credentials anyhow (your case), Pex should at most warn and move on. If you do need the credentials, things will fail when they should and you'll have the warning to look back at.
