### ISSUE TITLE
Preserve PEX_ env variables after calling pex

### ISSUE THREAD

**Issue by digwanderlust** [pantsbuild/pex#180]
https://github.com/pantsbuild/pex/blob/master/pex/pex.py#L48

Currently we delete all env variables from os.environ that start with PEX_.  If pex is called from another process as a library this will override the parent scripts env variables.  If the env variables are reset back to their original state at the end of execution the behavior would be less confusing when using pex as a library.

For example in pants if we try to override the PEX_ROOT every time we call pex to build a target PEX_ROOT is reset.

**Comment by jsirois** [comment]
If you haven't kibbutzed with @baroquebobcat you might want to.

**Comment by jsirois** [comment]
This is actually a bug. The `Pex.clean_environment` helper directly mutates `os.environ`. This is OK for `Pex._execute` which is expected to be the last invocation in the current interpreter but it is not OK for `Pex.run`.
