### ISSUE TITLE
`zipapp` mode drops tail log lines

### ISSUE THREAD

**Issue by thejcannon** [pantsbuild/pex#1802]
**Describe the bug**
`./pants run dropped.py` with the following file (using `absl-py==0.10.0`)
(Then try `python dropped.py` in a ve with `absl-py==0.10.0`)
The `python` invocation has the log line ("HELP ME"), and Pants invocation doesn't.

```python
import sys
import logging
import atexit
import logging.handlers
import queue
import sys
import faulthandler

import absl.app as absl_app
import absl.logging as absl_logging
from absl.flags import FLAGS


def run():
    print("hello")
    absl_logging.error("HELP ME")


def init_sys_logging():
    root_logger = logging.getLogger()

    FLAGS.alsologtostderr = True

    # No limit on queue size.
    log_queue = queue.Queue(-1)
    queue_forwarder = logging.handlers.QueueHandler(log_queue)
    root_logger.addHandler(queue_forwarder)

    queue_handlers = []

    # If absl logging is enabled; re-parent it to the queue.
    absl_handler = absl_logging.get_absl_handler()
    if absl_handler in root_logger.handlers:
        root_logger.handlers.remove(absl_handler)
        queue_handlers.append(absl_handler)

    queue_log_listener = logging.handlers.QueueListener(
        log_queue, *queue_handlers, respect_handler_level=True
    )
    queue_log_listener.start()

    atexit.register(queue_log_listener.stop)

    FLAGS.mark_as_parsed()


if __name__ == "__main__":
    absl_logging.set_verbosity(0)
    absl_logging.use_absl_handler()
    absl_logging.get_absl_handler().use_absl_log_file()

    faulthandler.enable()

    init_sys_logging()

    def run_wrapper(fn) -> int:
        absl_app._run_main(lambda args: fn(), sys.argv)
        return 0

    sys.exit(run_wrapper(run))
```

**Pants version**
2.11.0

**OS**
Linux

**Additional info**
N/A

**Comment by jsirois** [comment]
https://github.com/pantsbuild/pex/blob/825706c2cf6345c2ec494817080729c498d637cf/pex/pex.py#L531-L536

**Comment by jsirois** [comment]
For clarity, is using venv mode acceptable for you @thejcannon? I'm not sure whether or not PEX teardown code can be re-worked without breaking other use cases. This is very old code going back to 2011 or so; so it will take some spelunking.

**Comment by thejcannon** [comment]
I can't say I understand the nuance between the modes well enough to give a thorough answer. The short answer is "most likely", since I'm only using `zipapp` because its the default.

Really though on the Pants side, it'd be nice to be able to set this in `pex-binary-defaults` so I know all my binaries will be consistent. I'll open a separate ticket for that in pantsbuild.

I'll let you decide to leave the ticket open or close it.

**Comment by jsirois** [comment]
It's pretty simple, venv gives you a traditional venv. You pay a price for the 1st invocation. After that, native speed. So this comes down to measuring the cold 1st run startup overhead of the two modes (if you care about that), and picking your tradeoff.

**Comment by jsirois** [comment]
The origination commit is 19ae10a4 and the RB was https://rbcommons.com/s/twitter/r/253/.
I've copied the "Testing Done" notes here - they are the only record of the style of issue this was solving:
```
mba=science=; cat /tmp/foo.py
import atexit

def foo():
  raise Exception()

atexit.register(foo)

-----

old pex:

mba=science=; pex -- /tmp/foo.py 
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/wickman/Python/CPython-2.6.9/lib/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/tmp/foo.py", line 4, in foo
    raise Exception()
Exception
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/Users/wickman/Python/CPython-2.6.9/lib/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/tmp/foo.py", line 4, in foo
    raise Exception()
Exception


--

new pex:

mba=commons=; dist/pex.pex -- /tmp/foo.py
mba=commons=; PEX_TEARDOWN_VERBOSE=1 dist/pex.pex -- /tmp/foo.py
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/wickman/Python/CPython-2.7.6/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/tmp/foo.py", line 4, in foo
    raise Exception()
Exception
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/Users/wickman/Python/CPython-2.7.6/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/tmp/foo.py", line 4, in foo
    raise Exception()
Exception
```

And a screenshot capturing all discussion:
![image](https://user-images.githubusercontent.com/157586/174497407-d022e8f3-3d76-4523-933a-75059d1fba79.png)

**Comment by jsirois** [comment]
Ok, it looks like we no longer have the issue this was solving. I'll whip up a red PR.
