### ISSUE TITLE
PEX warns about missing `setuptools` for `matplotlib` but it seems like it's not required

### ISSUE THREAD

**Issue by georgipopovhs** [pantsbuild/pex#1815]
PEX warns about missing `setuptools` for `matplotlib`: 
```
$ pip install pex
$ pex --version
2.1.92
$ pex matplotlib==3.5.2
/private/var/folders/t0/zb49xf010cq4mqzwwxw8f31h0000gp/T/tmpbwxjl1xt/.bootstrap/pex/environment.py:657: PEXWarning: The `pkg_resources` package was loaded from a pex vendored version when declaring namespace packages defined by:

1. matplotlib==3.5.2 namespace packages:
  mpl_toolkits

These distributions should fix their `install_requires` to include `setuptools`
  "should fix their `install_requires` to include `setuptools`".format(dists=dists)
Python 3.7.9 (default, Mar 12 2021, 20:11:13)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>>
```

However, a docker container without `setuptools` is able to install matplotlib and import from the namespace package `mpl_toolkits`:
```
$ cat Dockerfile
FROM ubuntu:18.04

# install python
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    python3.7 python3-pip python3.7-dev

RUN python3.7 -m pip install -U pip
RUN python3.7 -m pip install matplotlib
$ docker build -t check-container .
...
$ docker run --rm check-container pip list
Package           Version
----------------- -------
cycler            0.11.0
fonttools         4.33.3
kiwisolver        1.4.3
matplotlib        3.5.2
numpy             1.21.6
packaging         21.3
Pillow            9.1.1
pip               22.1.2
pyparsing         3.0.9
python-dateutil   2.8.2
six               1.16.0
typing_extensions 4.2.0
$ docker run --rm check-container python3.7 -c 'from mpl_toolkits import mplot3d; print(dir(mplot3d))'
['Axes3D', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'art3d', 'axes3d', 'axis3d', 'proj3d']
```

I should acknoledge that without upgrading pip in the Dockerfile, it uses pip version 9, which is unable to install matplotlib because numpy and pillow fail to build and complain about missing `setuptools` and `gcc`. However with pip version 20.0.3+ there aren't any issues.

**Comment by jsirois** [comment]
I'm not sure there is much I can do. Here's the real import the PEX runtime encounters: https://github.com/matplotlib/matplotlib/blob/v3.5.x/lib/mpl_toolkits/__init__.py

Now, as you say, in this case things work out, matplotlib plans ahead and wraps the import in a try / except after all. Generally though, this is not the case and the library does the wrong thing. The warning has helped us find and fix some 3rd party libraries.

So I guess your prompt in this case is whether the warning should exist at all, even when it's generally accurate.

About that I'm not sure.

**Comment by jsirois** [comment]
To work around the warning being emitted, you could set `PEX_EMIT_WARNINGS=False` in the environment (see `pex --helo-variables`), or, if you have control of the PEX file build process, pass `--no-emit-warnings`.

**Comment by georgipopovhs** [comment]
I find the PEX warnings useful in general, so I wouldn't want to disable them completely.

My question was for this specific case with `matplotlib`.
So it seems like it's using some strange workaround?
I couldn't find a mention of this looking at [packaging guides](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/), or at setuptools documentation for [Legacy Namespace Packages](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#legacy-namespace-packages).

I guess the only clue I found was a the following [transitional note](https://setuptools.pypa.io/en/latest/setuptools.html#transitional-note):
 > Setuptools automatically calls declare_namespace() for you at runtime, but future versions may not. This is because the automatic declaration feature has some negative side effects, such as needing to import all namespace packages during the initialization of the pkg_resources runtime, and also the need for pkg_resources to be explicitly imported before any namespace packages work at all. In some future releases, you’ll be responsible for including your own declaration lines, and the automatic declaration feature will be dropped to get rid of the negative side effects.
> 
> During the remainder of the current development cycle, therefore, setuptools will warn you about missing declare_namespace() calls in your __init__.py files, and you should correct these as soon as possible before the compatibility support is removed. Namespace packages without declaration lines will not work correctly once a user has upgraded to a later version, so it’s important that you make this change now in order to avoid having your code break in the field. Our apologies for the inconvenience, and thank you for your patience.

Not an expert on namespace packages by any means, though it sounds like setuptools is dropping support for this case?

Just trying to understand what't the better line of action here - should I request matplotlib to update their install_requires, or should I silence pex..

**Comment by jsirois** [comment]
I think you should silence Pex in this case. As I pointed out, `matplotlib` wraps the namespace declaration in a try/except. Any import wrapped like that is, by definition, optional - the code author knows how to deal with the missing import / package it comes from. As such, they need not declare the dependency as an `install_requires` since they just opportunistically use it if present.

**Comment by georgipopovhs** [comment]
Thanks!
