### ISSUE TITLE
sh_boot script has wrong $INSTALLED_PEX path in certain circumstances.

### ISSUE THREAD

**Issue by hrfuller** [pantsbuild/pex#1881]
Problem:
Value of pex_root inside PEX-INFO of sh_boot-ed pex can vary from the value used in the sh_boot header script. This happens because the pex needs to be frozen prior to the sh_boot script being generated (so PexInfo.pex_hash is set, and the PEX-INFO file is written).

1. If the value of PexInfo.raw_pex_root is *not writable* during build time (common in a sandboxed build environment) the sh_boot script will change the value of raw_pex_root to a temp directory, and assume that a venv pex will be installed on the runtime host relative to this tmp_dir. But when the sh_boot-ed script runs for the first time the value of pex_root in PEX-INFO will be used as the pex_root meaning the low startup overhead of sh_boot cannot be accomplished because the sh_boot script will never see the INSTALLED_PEX exist.
2. The sh_boot-ed pex is run in an environment with a different $HOME value than build time. The user expansion of the pex_root at build time is different than the location of the pex_root at runtime. The mechanics of this discrepancy are the same as above when the $INSTALLED_PEX location is never created.

Possible Solution:
Don't try to infer the tilde-expansion of INSTALLED_PEX at build time. Embed the $INSTALLED_PEX location relative to the PexInfo.raw_pex_root. Trying to use the fully qualified PexInfo.pex_root property at build time is what causes the discrepancy between the sh boot header and PEX-INFO.

**Comment by jsirois** [comment]
I guess `pexrc` wouldn't help, the sh boot header doesn't parse those. But it does look like `--runtime-pex-root` should do the job.

**Comment by jsirois** [comment]
@hrfuller I'm going to start this off as a "qestion" and upgrade to "bug" if there is actually something Pex can do here to both preserve sh boot perf hacks and not be aware of the final runtime PEX_ROOT at the same time. It's not clear to me yet the latter is even possible to robustly in the sh script, but it may be.

**Comment by hrfuller** [comment]
Yeah I know about --runtime-pex-root and PEX_ROOT. I'm setting PEX_ROOT to a writable path inside the build sandbox, and --runtime-pex-root to ~/.pex/ so it doesn't inherit PEX_ROOT for runtime. AFAICT the issue only happens because the PexInfo.pex_root property can changes the in memory pex_root value after the PEX-INFO file has been written based on the `can_write_dir` return. Perhaps my suggestion would be better phrased to say after a pex is frozen PexInfo.pex_root should be immutable. The changes to `create_sh_boot_script` would follow.

> upgrade to "bug" if there is actually something Pex can do here

I think we should strive to do something here as the limitation in `2` reduces functionality of the feature. I'm going to try to put together a change to see if I can `preserve sh boot perf hacks and not be aware of the final runtime PEX_ROOT at the same time`. Will let you know if I get anywhere with it.

**Comment by jsirois** [comment]
Ok, great. Thanks @hrfuller.
