### ISSUE TITLE
venv_dir calculation doesn't correctly handle PEX_PYTHON_PATH with symlinks.

### ISSUE THREAD

**Issue by hrfuller** [pantsbuild/pex#1885]
I noticed a bug in the variables.venv_dir hash computation. If PEX_PYTHON_PATH has the path of a symlinked interpreter that interpreter value isn't added to the hash of the venv_dir. This can cause collisions in which interpreter is used to resolve dependencies via resolver.resolve. This happens because the canonical path to the interpreter is computed but the PEX_PYTHON_PATH is assumed to have canonical paths. [line in  question](https://github.com/pantsbuild/pex/blob/8c14e563493b8f4a85b4a3c735596dd55586a52b/pex/variables.py#L748)

I think it would be reasonable to map the PEX_PYTHON_PATH entries to their realpath's before comparing with the requested venv interpreter.

**Comment by jsirois** [comment]
@hrfuller is this another issue you plan on tackling like #1881? I do see you've assigned yourself. If so I'll leave it alone and be happy to review when you get time to fix.

FWIW I like to use self-assignment, and then later the in-progress label, as light tracking of what is planned / in progress.

**Comment by hrfuller** [comment]
Yeah that was the idea @jsirois. I have figured out a workaround, but would like to upstream a more robust fix to pex. I'll add the in progress label when I start work on it.
