### ISSUE TITLE
Pex cannot resolve `fbprophet`

### ISSUE THREAD

**Issue by benjyw** [pantsbuild/pex#1888]
```
python -m pex.cli lock create --style=universal    --interpreter-constraint 'CPython>=3.8,<3.9'  fbprophet==0.7.1
```

Fails on `ModuleNotFoundError: No module named 'numpy'`. 

What's going on is: fbprophet is distributed as an sdist, and its setup.py invokes its own code to precompile models, and that ends up evaluating an `__init__.py` that imports `numpy`, which isn't present.

Note that `pip install fbprophet==0.7.1` works, I guess because the numpy dep is installed prior to fbprophet's setup.py being invoked, and is available for it to use.

**Comment by jsirois** [comment]
This is a dup of #1751. Unfortunately there is nothing that can be done in general with sdists like this except to pre build a wheel out of band. See #1751 though for a workaround you might use in this case. There is an unreleased fix for the fbprophet build you can use via VCS requirement.
