### ISSUE TITLE
Strict setuptools requirement?

### ISSUE THREAD

**Issue by sixninetynine** [pantsbuild/pex#193]
Hey gang,

Any reason why the requirement on setuptools version is so strict? Any chance we could loosen this up?

https://github.com/pantsbuild/pex/blob/master/pex/version.py#L6

**Comment by kwlzn** [comment]
I don't see anything in the setuptools changelog between 16.x->current that should prevent us from bumping this.

/cc @wickman in case there are any historic reasons for the ```setuptools>=2.2,<16``` pin.

**Comment by sixninetynine** [comment]
thanks much! :+1: :+1:

**Comment by kwlzn** [comment]
I've merged a bump to both setuptools + wheel to master, which should go out in the next pypi release (1.1.2) - you can follow #188 to track that.
