### ISSUE TITLE
Empty string PEX_PATH="" env var causes CWD (.) to be added bootstrapped pex_path

### ISSUE THREAD

**Issue by hrfuller** [pantsbuild/pex#1936]
The CWD doesn't usually contain a pex so the the pex being executed fails to bootstrap with a pex_info load error looking for a file `./PEX_INFO`.

Ran into this issue when upgrading from 2.1.97 -> 2.1.105. Was able to work around it by unsetting PEX_PATH entirely, but if this is a regression I can look into the root cause. Is this an intentional change?

**Comment by jsirois** [comment]
Sounds like a regression to me. It broke you!

**Comment by jsirois** [comment]
I added this to the 2.1.109 release since it should be a very tiny, very easy fix. @hrfuller do you want to grab it or should I? I'm looking to release 2.1.109 today.
