### ISSUE TITLE
importing a __pex__ leaks bootstrap vendored code

### ISSUE THREAD

**Issue by zmanji** [pantsbuild/pex#1954]
```
$ pex --version
2.1.110

$ python3 -c 'import attr' 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'attr'

$ pex -o psutil.pex --layout=loose 'psutil'  

$ python3
Python 3.9.4 (default, Apr 15 2021, 21:01:17) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(ins)>>> import sys
(ins)>>> sys.path.append('./psutil.pex')
(ins)>>> import __pex__
(ins)>>> import attr
(ins)>>> attr
<module 'pex.vendor._vendored.attrs.attr' from '/Users/zmanji/tmp/psutil.pex/.bootstrap/pex/vendor/_vendored/attrs/attr/__init__.py'>       
```

**Comment by jsirois** [comment]
@zmanji is this just an observation / gedankenbug or is it causing you pain currently? Are you in a position to fix?

**Comment by zmanji** [comment]
This is just an observation, I can take a look investigating it later. Preliminary investigation shows the scrubbing failed to remove `attr`.
```
pex: Not a tainted path element: /Users/zmanji/tmp/psutil.pex/.bootstrap/pex/vendor/_vendored/attrs
```

**Comment by zmanji** [comment]
@jsirois This is my attempt to fix the bug https://github.com/zmanji/pex/commit/0a1c2c7c0eaf0c86192ee51f687ed367535e22df

The added assertion fails on `main`. The assertion passes with the demotion call for unzipped pexes but I am not sure what the fix is for venv pexes.

**Comment by jsirois** [comment]
That looks about right. I left some comments on https://github.com/zmanji/pex/commit/0a1c2c7c0eaf0c86192ee51f687ed367535e22df "No pressure", but I'll assign this one to you since you're rolling.

**Comment by zmanji** [comment]
I attempted the comments on https://github.com/zmanji/pex/commit/0a1c2c7c0eaf0c86192ee51f687ed367535e22df but I wasn't able to get it to work with venv pexes. It seems the stdlib is stripped from the path causing `import csv` to fail. A working but partial fix is on https://github.com/zmanji/pex/commit/08c6c0e3149d67b2f5bc4a9573d199605cc5a3f9
