### ISSUE TITLE
Support editable distributions/zipballs

### ISSUE THREAD

**Issue by sprt** [pantsbuild/pex#196]
Pretty please.

**Comment by kwlzn** [comment]
could you expand a little on the use case(s) here?

in general, the idea of editable deps + pex seems to be at odds with the pex core philosophy of 'hermetically sealed artifacts', which aims to avoid side effects from environment to environment. editable deps appear to be designed to solve a problem with traditional python installations/venvs where deps are "installed" into the environment vs composed into a standalone executable. in the pex/pants world, you'd typically just iterate by building and running another pex - tho arguably it's not quite as fast of a development cycle as you might achieve with something like editable deps.

it's also worth noting that pex files can run uncompressed (`unzip -l the.pex && python2.7 .`), in which case their copy of contents are editable (including the sources of the transitive dependency set). this allows for quick debugging/iteration in more complex multi-package scenarios than even editable deps might.

**Comment by sprt** [comment]
That was indeed poorly worded.

I meant it in the context of pip installs.  For example, you can't have one of these in your `requirements.txt` as pex will throw an `UnsupportedLine` error:

```
-e git+https://github.com/pantsbuild/pex.git@#egg=pex
```

**Comment by sveitser** [comment]
There's #93 for implementing the VCS resolvables. I currently just clone the (git) repos, checkout commit  and then package them as resolvable directories.

**Comment by ariscn** [comment]
@sveitser Could you share a bit more about how you manage projects in dev?

Let's say I'm actively working on `myapp`: I'm in the directory, which contains a `requirements.txt` and `setup.py`. In a virtualenv world, I create a virtualenv, `pip install -r requirements.txt`, and `pip install -e .`, and I'm off to the races with `[i]python`. What's the equivalent pex workflow?

**Comment by kwlzn** [comment]
pex also supports installing requirements from a directory containing a `setup.py` (e.g. `cd ~/dev/project && pex .`). it just doesn't have a special affordance for "editable" dependencies atm because fundamentally our aim has always been repeatable, self contained builds without side effects. so `pex .` nets you effectively the same thing as `pip install -e .`, except instead of being able to edit the code on the fly in say a running webserver you'd have to rebuild the pex each time you run it to encapsulate new changes.

thus, I believe the analog here is simply: `pex -r requirements.txt .` - just run more frequently.

**Comment by sherzberg** [comment]
@kwlzn following up on your statement about using `pex .`, is this possible for multiple relative libraries?

For example, we have a mono repo like this:

```
.
├── bin1
│   └── main1.py
├── bin2
│   └── main2.py
├── dep1
│   └── setup.py
└── dep2
    └── setup.py
```

For `bin1`, I would like to do something like `cd bin1 && pex ../dep1 ../dep2 -- main1.py`.

This may be a separate issue which I can create if you want, but just wanted to follow up here as you mentioned `pex .`

When trying this, I get `pex.resolvable.InvalidRequirement: Unknown requirement type`.

**Comment by kwlzn** [comment]
@sherzberg should work:

```
[omerta show]$ ls -al
total 8
drwxr-xr-x   5 kwilson  wheel  170 Apr 17 16:50 .
drwxrwxrwt  17 root     wheel  578 Apr 17 16:40 ..
drwxr-xr-x  17 kwilson  wheel  578 Apr 17 16:50 Flask-0.10.1
drwxr-xr-x  13 kwilson  wheel  442 Apr 17 16:50 requests-2.12.3
-rw-r--r--   1 kwilson  wheel   82 Apr 17 16:50 test.py
[omerta show]$ cat test.py 
import requests
import flask
print('%s %s' % (requests.__file__, flask.__file__))
[omerta show]$ pex Flask-0.10.1 requests-2.12.3 -- test.py
/private/var/folders/bb/msvj_4_s741g93nzgrj19twc0000gn/T/tmpjxJ4Z7/.deps/requests-2.12.3-py2-none-any.whl/requests/__init__.py /private/var/folders/bb/msvj_4_s741g93nzgrj19twc0000gn/T/tmpjxJ4Z7/.deps/Flask-0.10.1-py2-none-any.whl/flask/__init__.py
```

but given a monorepo, it may make more sense to just use `pants` here (which can produce pex files). then, you don't even need the `setup.py` boilerplate - you can simply declare those as `python_library` targets and depend on them from other `python_library` or `python_binary` targets.

**Comment by sherzberg** [comment]
@kwlzn thanks! your suggestion did work. 

We have also started playing with Pants as well as an alternative.
