### ISSUE TITLE
Forgetting to close a file handle?

### ISSUE THREAD

**Issue by sholsapp** [pantsbuild/pex#197]
We have various short running and long running programs that are using pex. We've been running out of /tmp space in various occasions, so we've been investigating the issue with lsof. We're seeing a number of entries in lsof output:

    foo 17879       sholsapp    2u      REG               0,17   535621632  214612953 /tmp/ffiNf349b (deleted)

These types of files are cleaned up after the respective pex process terminates.

Is this a bug?

**Comment by kwlzn** [comment]
any chance you can provide repro steps?

**Comment by sholsapp** [comment]
@kwlzn When I'm back at my desk tomorrow I'll send you an end-to-end example of what is going on. Before then in case it helps: we're packing a pex file with a ton of dependencies, we're running the generated pex, we're observing that a large amount of the /tmp filesystem is used, using lsof to discover that a file handle to a deleted file exists. The process is long lived (it is a Flask web server). When the process ends, we see that the file is cleaned up.

Thanks for the quick reply. I'll share more tomorrow.

**Comment by sholsapp** [comment]
I was not able to reproduce with a pure pex example (https://github.com/sholsapp/pex-example) which led us to the actual problem in gunicorn. Sorry for the noise. :beers:

**Comment by kwlzn** [comment]
nbd! thanks for updating the issue.
