### ISSUE TITLE
Add an option like Python's `-P`, which doesn't prepend certain paths to sys.path

### ISSUE THREAD

**Issue by thejcannon** [pantsbuild/pex#1981]
See https://docs.python.org/3/using/cmdline.html#cmdoption-P

It'd be great if PEX has a similar option.

**Comment by jsirois** [comment]
@thejcannon do you need those semantics, which differ per run mode (notably the resolving symlinks thing for running a script), or do you just need CWD omitted from sys.path universally?

**Comment by jsirois** [comment]
I think this will need to be both a build-time and runtime (PEX_* env var) option, but please chime in on what you're expecting in that regard as well.

**Comment by thejcannon** [comment]
Funny enough the bug is making this "work" for the zipapp case. I'll file a detailed issue separately that we _should_ fix, but doesn't change this ticket.

(assuming no bugs in PEX)
Any invocation of PEX, should be acting like `python` given the inputs. And from https://docs.python.org/3/library/sys.html#sys.path all 3 possible invocations of `python` will have some path prepended to `sys.path`. The ones causing the Pants bug are `python -m module` prepending CWD and `python -c code`/`python` which prepend `""` which is resolved to be CWD. `python script.py` prepends the scripts directory which isn't causing any waves that I know of in Pants, but for PEX's own feature-parity should likely follow suit and be scrubbed.

**Comment by thejcannon** [comment]
This may be partially moot depending on the outcome of https://github.com/pantsbuild/pex/issues/1982 (specifically I assume using `PEX_INHERIT_PATH=false`). 

If `pex` is meant to mirror `python` 1:1 (and therefore the linked issue needs to be fixed), then we want a toggle to scrub `sys.path` like `PYTHONSAFEPATH`.
If `pex` isn't meant to mirror `python` (presumably because `PEX_INHERIT_PATH=false`) then this issue can be closed as that env var ensures no potentially unsafe path is in `sys.path`.

**Comment by thejcannon** [comment]
@jsirois Yup. So as far as I'm concerned I no longer "need" this feature. Furthermore I think `PEX_INHERIT_PATH=false` already captures the intent for non-interpreter modes. 

I'll leave it up to you to decide if this feature needs to be implemented to handle the interpreter-case w.r.t. `""` at the head of `sys.path`. Especially since I don't "know" PEX and it's users enough to know the expectation of PEXes in interpreter mode with/without `PEX_INHERIT_PATH` set.

**Comment by jsirois** [comment]
Yeah interpreter mode is only triggered by lack of an entry point defined at build time or else PEX_INTERPRETER=1 forcing. PEX_INHERIT_PATH is orthogonal. It simply mixes in the sys.path of the ambient interpreter running the PEX if you ask.

**Comment by jsirois** [comment]
Ok, I'll close this then @thejcannon since you don't need it. The likelyhood of a use case for it seem small at this point, especially because its Python 3.11 only behavior.
