### ISSUE TITLE
Should `pex ... -e module` be prepending CWD?

### ISSUE THREAD

**Issue by thejcannon** [pantsbuild/pex#1982]
According to https://docs.python.org/3/library/sys.html#sys.path `python -m module` prepends CWD to `sys.path`.

```
$ cat code/foo.py 
import sys
import os

def main():
    print(os.getcwd())
    print(sys.path)


if __name__ == "__main__":
    main()
```

```
$ python -m code.foo
/home/josh/work/pants
['/home/josh/work/pants', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/josh/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']
```

---

PEX help says:
```
-m MODULE[:SYMBOL], -e MODULE[:SYMBOL], --entry-point MODULE[:SYMBOL]
                        Set the entry point to module or module:symbol. If just specifying module, pex behaves like python -m, e.g. python -m SimpleHTTPServer. If specifying
                        module:symbol, pex assume symbol is a n0-arg callable and imports that symbol and invokes it as if via `sys.exit(symbol())`. (default: None)
```

So presumably using `pex -D code -e foo` would act like `python -m code.foo`, however:

```
$ pex -D=code -e foo
/home/josh/work/pants
['/tmp/tmpnu421wmb', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/tmp/tmpnu421wmb/.bootstrap']
```
even if I twiddle with `PEX_INHERIT_PATH:
```
$ PEX_INHERIT_PATH=fallback pex -D=code -e foo
/home/josh/work/pants
['/tmp/tmpfauv3vos', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/tmp/tmpfauv3vos/.bootstrap']
```
```
$ PEX_INHERIT_PATH=prefer pex -D=code -e foo
/home/josh/work/pants
['/tmp/tmpyj_l3y5m', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/tmp/tmpyj_l3y5m/.bootstrap']
```

---

Furthermore using a function spec:

```
$ pex -D=code -e foo:main
/home/josh/work/pants
['/tmp/tmp0kfzbnkw', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/tmp/tmp0kfzbnkw/.bootstrap']
```
(It's a big ambiguous if this should prepend CWD as per `python -m` or `""` as per `python -c` as it all depends on how the `entry_point` runner is invoked.)

**Comment by jsirois** [comment]
As discussed on #1983 [here](https://github.com/pantsbuild/pex/issues/1983#issuecomment-1320301671) I think its correct to prepend the CWD on sys.path when a PEX acts as an interpreter, which is when there is no entrypoint defined at build-time or else when PEX_INTERPRETER=1 is used at runtime. Those are the only cases where Pex acts like a Python interpreter and so should behave like one. In all other cases PEX should carry out its mission of being a hermetic Python application environment and not prepend extra sys.path elements unless asked via `--inherit-path`/`PEX_INHERIT_PATH` or `PEX_EXTRA_SYS_PATH`.

I think that means the only thing that needs fixing is this bit in the current venv mode PEX:
https://github.com/pantsbuild/pex/blob/67fc7e05315fc347bcf269712814f160c6035efe/pex/venv/pex.py#L443-L444

That CWD insertion on the sys.path happens before the execution mode is determined. It should happen lower down after the entry point is determined:
https://github.com/pantsbuild/pex/blob/67fc7e05315fc347bcf269712814f160c6035efe/pex/venv/pex.py#L495-L500

Only if `entry_point == PEX_INTERPRETER_ENTRYPOINT` should the CWD sys.path insertion proceed. That will bring parity with PEX zipapp mode and meet all the PEX expectations - work like Python when used as an interpreter, be hermetic at all other times (when used as an app).

**Comment by thejcannon** [comment]
Thanks for thinking this through and laying it out.

>  In all other cases PEX should carry out its mission of being a hermetic Python application environment and not prepend extra sys.path elements unless asked via --inherit-path/PEX_INHERIT_PATH or PEX_EXTRA_SYS_PATH.

Part of this ticket does show that even with `PEX_INHERIT_PATH` set to non-`false`, `sys.path` doesn't contain the CWD in it. Should we leave this ticket open to capture that discrepancy?

**Comment by jsirois** [comment]
I think not.

> So presumably using pex -D code -e foo would act like python -m code.foo, however:

Here you're _building_ a PEX application. When a PEX application defines an entrypoint it acts as that application, it does not act as a Python interpreter.

As to what `--inherit-path`/`PEX_INHERIT_PATH` claims to do, there is no mention of CWD:
```
--inherit-path {false,prefer,fallback}
                        Inherit the contents of sys.path (including site-packages, user site-packages and PYTHONPATH) running the pex. Possible values: false (does not inherit sys.path), fallback (inherits
                        sys.path after packaged dependencies), prefer (inherits sys.path before packaged dependencies), No value (alias for prefer, for backwards compatibility). (default: false)
```

So I think, PEX behaves as it should right now in both zipapp and venv execution modes when not acting as an interpreter. It only misbehaves when running in venv execution mode and not acting as an interpreter.

**Comment by thejcannon** [comment]
Very good point. Thanks!
