### ISSUE TITLE
Allow for sorting the requirements when exporting `requirements.txt`

### ISSUE THREAD

**Issue by thejcannon** [pantsbuild/pex#1988]
This allows for much easier diffing (migrating from `pip-tools`) and grokking (trying to scroll and find)

**Comment by thejcannon** [comment]
Currently I have the following:

```
sed -i -z "s/\\\\\n  //g" requirements.txt
sort -o requirements.txt requirements.txt
sed -i "s/ --hash=\(.*\)/ \\\\\\n  --hash=\1/" requirements.txt
```

**Comment by jsirois** [comment]
This seems fine, if ~arbitrary. That said, its hard to imagine too many more axes beyond alpha-sort an pip-tools is a thing.
