### ISSUE TITLE
Crawler.crawl_remote returns incorrect results if index is redirected

### ISSUE THREAD

**Issue by wyattanderson** [pantsbuild/pex#200]
The PyPI-compatible server [devpi](http://doc.devpi.net/latest/) will issue redirects to the lowercased package page if an uppercased package name (e.g. `Django`) is searched. For example, if the index URL is `https://HOST/wyatt/test/+simple/` (with or without trailing slash), `pex` will query `https://HOST/wyatt/test/+simple/Django/` to install requirement `Django==1.6.5`. devpi will redirect to `https://HOST/wyatt/test/+simple/django` (_without_ a trailing slash) and the crawler crawls URLs on the index page (presumably because `requests` follows the redirect), the links in which are relative to the URL without the trailing slash (i.e. are one level shallower with respect to leading `..` segments).

In `pex.crawler.Crawler.crawl_remote`, the links are joined to the original URL and the link object's URL isn't updated to reflect the new canonical URL of the page. This results in incorrect resolution of the relative URLs on the index since the trailing slash is missing.

Pip itself doesn't have this issue with devpi.

Anyway, I think we can work around this on our end by slapping on a trailing slash with NGINX, but I think for the sake of correctness this should be updated in Pex itself. Happy to work on a patch if this is a valid issue.

The pex version this happens in is 1.1.2.

**Comment by kwlzn** [comment]
@wyattanderson seems like a valid issue to me. I've heard of at least a couple of instances where folks have gotten hung up on pex + trailing slashes at the end of URLs (e.g. in `pants` `[python-repos] repos` configs), so if you see opportunities here to streamline more of the general url handling code - or just want to address this particular issue - go for it!
