### ISSUE TITLE
The PEX_TOOLS venv `--compile` option should ignore compile errors.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#2001]
If there is a compile error, it may be irrelevant as in this case https://github.com/ShantanuKumar/pants-multi-poetry.

There the PEX produced via `./pants package src/package-a/package_a:pex_package_a` runs into this issue:
```
$ PEX_TOOLS=1 python3.9 dist/src.package-a.package_a/pex_package_a.pex venv --scope=deps --compile ./pex-deps-compiled 2>&1 | grep -C5 SyntaxError
Compiling './pex-deps-compiled/lib/python3.9/site-packages/aenum/__init__.py'...
Compiling './pex-deps-compiled/lib/python3.9/site-packages/aenum/_py2.py'...
***   File "./pex-deps-compiled/lib/python3.9/site-packages/aenum/_py2.py", line 5
    raise exc, None, tb
             ^
SyntaxError: invalid syntax

Compiling './pex-deps-compiled/lib/python3.9/site-packages/aenum/_py3.py'...
Listing './pex-deps-compiled/lib/python3.9/site-packages/aenum/doc'...
Compiling './pex-deps-compiled/lib/python3.9/site-packages/aenum/test.py'...
Compiling './pex-deps-compiled/lib/python3.9/site-packages/aenum/test_v3.py'...
```

The `aenum/_py2.py` file will never get imported by the Python 3.9 interpreter; so this compile failure is not relevant.

If the compile error is real, the application will encounter it at runtime and fail anyhow. On balance, it seems a later warning is by far the lesser of two evils here. Currently failing the venv creation due to failing compilation of a file stops things in their tracks with no recourse.

**Comment by jsirois** [comment]
The failing line in question is here:
https://github.com/pantsbuild/pex/blob/af6f74da59d6053cf0b55669449328af3fc79cd4/pex/tools/commands/venv.py#L209

**Comment by ShantanuKumar** [comment]
Should we then just ignore this error using `try/except`?

**Comment by ShantanuKumar** [comment]
By the way do I need to install all the tox envs to run tests?

**Comment by jsirois** [comment]
That should do. Note that the exception raised is `pex.executor.Executor.NonZeroExit`:
https://github.com/pantsbuild/pex/blob/61c150d3635b3603ee9a0e8cf9bc748c415a8660/pex/executor.py#L40-L49

That has fields for stdout and stderr; so you could use one or both of those to relay compilation errors as a warning in case the errors are real and will actually blow up when the PEX is run. I'm not sure about how to handle that, being too noisy for some cases and potentailly too quiet for others, but that's where the data is at any rate.

**Comment by jsirois** [comment]
If you do go the warning route, you'd use `pex.pex_warnings.warn`.

**Comment by ShantanuKumar** [comment]
Hey @jsirois I have finally added an integration test , please have a look.
