### ISSUE TITLE
Support for generating non-hermetic console scripts in `venv`

### ISSUE THREAD

**Issue by danxmoran** [pantsbuild/pex#2004]
The `venv` command rewrites console script shebangs in the generated virtualenv [here](https://github.com/pantsbuild/pex/blob/632a6ba3867d520e2721bf70fa1e7f114050c78b/pex/venv/pex.py#L276-L278), adding `-sE` in the process. Those added flags make it more difficult to use scripts that rely on `PYTHONPATH` (i.e. `pylint` trying to load in-repo plugins). It would be nice if `venv` supported an option to disable the behavior.

**Comment by jsirois** [comment]
Yeah, this sounds sane and useful @danxmoran.
