### ISSUE TITLE
A loose layout, venv-with-symlink PEX creates brittle symlinks

### ISSUE THREAD

**Issue by thejcannon** [pantsbuild/pex#2023]
Pex version `2.1.113`

I found this through Pants, but ultimately seems like a PEX issue/fix.

```console
$ pex --no-venv-copies --layout=loose --venv prepend awscli --script aws -o  awscli.pex
$ python awscli.pex help
<help output>
$ mv awscli.pex awscli2.pex/
$ python awscli2.pex
Traceback (most recent call last):
  File "/home/josh/.pex/venvs/ea7cb7998ed2db4f784178989a4034013cd10e01/ddab8011daaee380698ac2fb9701af18c90c03f6/bin/aws", line 19, in <module>
    import awscli.clidriver
ModuleNotFoundError: No module named 'awscli
```

See also:
```console
$ ls -l /home/josh/.pex/venvs/ea7cb7998ed2db4f784178989a4034013cd10e01/ddab8011daaee380698ac2fb9701af18c90c03f6/lib/python3.8/site-packages/awscli
lrwxrwxrwx 1 josh josh 107 Jan  3 11:49 /home/josh/.pex/venvs/ea7cb7998ed2db4f784178989a4034013cd10e01/ddab8011daaee380698ac2fb9701af18c90c03f6/lib/python3.8/site-packages/awscli -> ../../../../../../../../../<CWD>/awscli.pex/.deps/awscli-1.27.41-py3-none-any.whl/awscli
```

In Pants-land, this manifests as being a symlink to an ephemeral Pants sandbox which has since gone bye-bye.

---

What I might expect is that on first run, the wheels get copied into the PEX root and then the venv symlinks to the extracted wheels in the pex root so moving/deleting the original pex doesn't invalidate the venv.

**Comment by jsirois** [comment]
Pants doesn't use loose, only packed. The same problem likely exists there though. Is loose use new or not a relevant / accurate detail here?

**Comment by thejcannon** [comment]
I'm declaring a `pex_binary` so the keys are all mine.

**Comment by thejcannon** [comment]
I also couldn't reproduce with `packed` or `zipapp` layouts, so I do think it is relevant.

**Comment by jsirois** [comment]
Gotcha. Thanks for the extra context. 

Bug fix aside, if you're willing to share the use case, loose -> venv. Its supported and needs to be fixed, but also the oddest use case in the matrix of layouts x execution mode so I'm curious.

**Comment by thejcannon** [comment]
No specific use-case other than "was using `loose`, then tacked on `venv`". Our local fix is to drop the "loose".

**Comment by jsirois** [comment]
What was the loose for in the 1st place though? I am aware of 0 loose users (Pants would be if sandboxing were performant); so I'd love to learn what problems it helps people with.

**Comment by thejcannon** [comment]
The PR that introduced it lacks context :unamused: If I had to guess it was either to workaround a bug or was a result of "bang on it until it works"
