### ISSUE TITLE
Using `--complete-platform` with `--resolve-local-platforms` should build sdists when local platform provides a subset of complete-platforms

### ISSUE THREAD

**Issue by shalabhc** [pantsbuild/pex#2026]
# Summary

If a builder platform is capable of building sdists into wheels that are compatible with a target platform, then `pex --complete-platform=cp-generated-from-target.json --resolve-local-platforms` should build any pex on the builder, including any sdists.

# Example where this doesn't work

* builder: PyPA [official](https://github.com/pypa/manylinux#docker-images) wheel builder `quay.io/pypa/manylinux2014_x86_64` 
* target: `python:3.10-slim` [source](https://github.com/docker-library/python/blob/7a54933c66171020473b9a4f06aec4e8ffb43a45/3.10/slim-bullseye/Dockerfile)

# Steps to reproduce

1. Generate the complete-platform.json ([py310-complete-platform.json.zip](https://github.com/pantsbuild/pex/files/10356605/py310-complete-platform.json.zip))
    ```
    % docker run --platform=linux/amd64 -it python:3.10-slim /bin/bash -c 'pip3 install pex==2.1.119 --quiet --quiet --quiet; pex3 interpreter inspect --markers --tags;' > py310-complete-platform.json
    ```
2. Prepare the builder
    ```
    % docker run --platform=linux/amd64 -it -v ${PWD}:/curdir quay.io/pypa/manylinux2014_x86_64            
    [root@3a4bc9eae7f5 /]# export PATH=/opt/python/cp310-cp310/bin/:$PATH
    [root@3a4bc9eae7f5 /]# python3.10 --version
    Python 3.10.9
    [root@3a4bc9eae7f5 /]# which pip3
    /opt/python/cp310-cp310/bin/pip3
    [root@3a4bc9eae7f5 /]# pip3 install pex
    Collecting pex
      Downloading pex-2.1.119-py2.py3-none-any.whl (2.9 MB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 6.0 MB/s eta 0:00:00
    Installing collected packages: pex
    Successfully installed pex-2.1.119
    
    [root@3a4bc9eae7f5 curdir]# cd /curdir
    [root@3a4bc9eae7f5 curdir]# export _PEX_FILE_LOCK_STYLE=bsd
    ```

3. Build the PEX (note [there is no wheel](https://pypi.org/project/pendulum/) for `pendulum` for Python 3.10)
    ```
    [root@3a4bc9eae7f5 curdir]# pex --python=python3.10 --complete-platform=py310-complete-platform.json --pip-version=22.2.2 --resolver-version=pip-2020-resolver pendulum==2.1.2 -o pendulum.pex --resolve-local-platforms
    pid 513 -> /root/.pex/venvs/6c59b447d0c1988f35c5942be176267a84f608a5/34acb08bef9fb9b19fe854dbe3d6bc571944def9/bin/python -sE /root/.pex/venvs/6c59b447d0c1988f35c5942be176267a84f608a5/34acb08bef9fb9b19fe854dbe3d6bc571944def9/pex --disable-pip-version-check --no-python-version-warning --exists-action a --no-input --isolated -q --cache-dir /root/.pex/pip_cache --log /tmp/pex-pip-log.dig57pt8/pip.log download --dest /root/.pex/downloads/resolver_download.pgnh8tee/cp310-cp310-manylinux_2_31_x86_64 --only-binary :all: pendulum==2.1.2 --index-url https://pypi.org/simple --retries 5 --timeout 15 exited with 1 and STDERR:
    ERROR: Could not find a version that satisfies the requirement pendulum==2.1.2 (from versions: 0.3.1, 0.4, 3.0.0a1)
    ERROR: No matching distribution found for pendulum==2.1.2
    ```

# Alternatives tried

* using `--interpreter-constraint` instead of `--python` -> same error as above
* using `--platform=manylinux2014_x86_64-cp-310-cp310` instead of `--complete-platform`
    * build succeeded
    * run succeeded - I was able to run the built pex on the target, which means this was a compatible wheel
    * the built wheel was `manylinux_2_17` :
       ```
        unzip -l pendulum-b.pex | grep 'whl/$'
        0  01-01-1980 00:00   .deps/pendulum-2.1.2-cp310-cp310-manylinux_2_17_x86_64.whl/
        0  01-01-1980 00:00   .deps/python_dateutil-2.8.2-py2.py3-none-any.whl/
        0  01-01-1980 00:00   .deps/pytzdata-2020.1-py2.py3-none-any.whl/
        0  01-01-1980 00:00   .deps/six-1.16.0-py2.py3-none-any.whl/
        ````

**Comment by shalabhc** [comment]
Here's a test that I think should pass, but doesn't:

https://github.com/pantsbuild/pex/compare/main...shalabh-pex-lab:pex:main

**Comment by jsirois** [comment]
Why are you using --platform or --complete-platform at all here?

**Comment by jsirois** [comment]
So, the issue here is there is no interpreter in the manylinux image that has a subset of the complete platform info you built in the lim image. It goes _exactly_ like this:
1. If either `--platform` or `--complete-platform` is presented along with `--resolve-local-platforms`, then before using either `--platform` or `--complete-platform` is used, an attempt is made to find a local interpreter that matches each `--platform` or `--complete-platform` you sepcificed. In this case there are 0 matches for the `--complete-platform` and so the resolve proceeds using the `--complete-platform` with no substitute. As such, no sdist building is allowed.

**Comment by shalabhc** [comment]
The definition of 'matches' is what I'm confused about. If a builder can build `['manylinux_2_3']` and complete platform includes `['manylinux_2_4', 'manylinux_2_3', 'manylinux_2_2']`, then IMO the sdists build should be attempted. This should be considered a match but isn't.

**Comment by shalabhc** [comment]
i.e instead of a subset match it does two checks:
1. most specific tag matches
2. for remaining tags, the builder interpreter tags should be a superset of the complete-platforms tags.

I think 1 should not be necessary?

**Comment by jsirois** [comment]
@shalabhc the test is right here:
https://github.com/pantsbuild/pex/blob/7a2db79f12e747b173fd34f12af03934fe513a14/pex/resolve/target_configuration.py#L103-L167

**Comment by shalabhc** [comment]
Note `all_platforms` uses the first tag for matching only: https://github.com/pantsbuild/pex/blob/7a2db79f12e747b173fd34f12af03934fe513a14/pex/targets.py#L264

I see in your diff above that the builder (right) is a proper subset of the target complete-platforms (left). Did I miss something?

**Comment by jsirois** [comment]
@shalabhc why do you see the line you pulled as relevant? Its the block I point to that should be the relevant one.

**Comment by jsirois** [comment]
Ok, you've gathered some good info here. I'll need some time to process.

**Comment by shalabhc** [comment]
See my test (slightly modified version of existing test) [above](https://github.com/pantsbuild/pex/compare/main...shalabh-pex-lab:pex:main) - it should succeed if 'subset' is the only criteria.

**Comment by jsirois** [comment]
@shalabhc what these seems to boil down to is me having done a poor job of reviewing @huonw's change in #1991. You appear to have a bit of a handle on what's going on here. Do you think you have the fix? I can try and do a better job of reviewing this time if so.

**Comment by shalabhc** [comment]
@jsirois I have a fix for my new test but it breaks some existing tests :)

I can tweak it until all tests pass and make a PR - may take a couple of iterations to get it right.

**Comment by jsirois** [comment]
Sounds great. Thanks @shalabhc
