### ISSUE TITLE
Failed to resolve compatible distributions: `Sphinx==6.1.3` requires `docutils<0.20,>=0.18` but `docutils 0.16` was resolved

### ISSUE THREAD

**Issue by NiklasRosenstein** [pantsbuild/pex#2069]
Hi! I'm trying to build a Pex of an application that has `s3` as a dependency. But when I try that, I get the following error:

```
$ pex ./ -o snapper-backups.pex -e snapper_backups.main
Failed to resolve compatible distributions:
1: Sphinx==6.1.3 requires docutils<0.20,>=0.18 but docutils 0.16 was resolved
```

The issue can be more easily reproduced by simply trying to Pexify the `s3` <sup>[1]</sup> package:

```
$ pex s3
Failed to resolve compatible distributions:
1: Sphinx==6.1.3 requires docutils<0.20,>=0.18 but docutils 0.16 was resolved
```

<sup>[1]</sup> The version of `s3` that is being used here is `3.0.0`.

This appears to be a bug with Pex because I can properly install `s3` with Pip.

**Comment by jsirois** [comment]
One key principle to keep in mind with Pex is that it does not break you. An unfortunate consequence of this is that new features, even when better, are not the default (this will change on the next breaking release 3.0.0).

So you're missing an option here, which is to use the modern Pip resolver:
```
$ pex s3 --resolver-version pip-2020-resolver
/tmp/tmp9emh862b/.bootstrap/pex/environment.py:654: PEXWarning: The `pkg_resources` package was loaded from a pex vendored version when declaring namespace packages defined by:

1. sphinxcontrib-devhelp==1.0.2 namespace packages:
  sphinxcontrib

2. sphinxcontrib-jsmath==1.0.1 namespace packages:
  sphinxcontrib

3. sphinxcontrib-serializinghtml==1.1.5 namespace packages:
  sphinxcontrib

4. sphinxcontrib-qthelp==1.0.3 namespace packages:
  sphinxcontrib

These distributions should fix their `install_requires` to include `setuptools`
  pex_warnings.warn(
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>>
```

So that toggles the default of `--resolver-version pip-legacy-resolver`.

**Comment by jsirois** [comment]
@NiklasRosenstein I'm going to close this as an answered question, but please speak up if you have more that the Pex CLI help doesn't provide enough information for.

**Comment by NiklasRosenstein** [comment]
Thanks for the explanation @jsirois! 

On a side note, I only just realized that `s3` is not the package I needed anyway, it's `boto3`. 😅
