### ISSUE TITLE
Deprecate and remove python 2.6 support.

### ISSUE THREAD

**Issue by kwlzn** [pantsbuild/pex#208]
from a travis log:

```
py26 installed: DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6,argparse==1.4.0,funcsigs==0.4,mock==1.3.0,pbr==1.8.1,pex==1.1.2,py==1.4.31,pytest==2.5.2,six==1.10.0,twitter.common.contextutil==0.3.4,twitter.common.dirutil==0.3.4,twitter.common.lang==0.3.4,twitter.common.testing==0.3.4,wheel==0.29.0
```

I think it would make sense to align with pip's timing on the removal of 2.6 support from pex.

**Comment by petmakris** [comment]
+1 

One of the reasons we use pex is because we need to pack dependencies and execute .pex files in an isolated environment with python2.6 

could be reconsidered/postponed or remove python2.6 support after a good-and-safe major release of pex?

**Comment by kwlzn** [comment]
sure, there's certainly no hurry here. after speaking to the pypa folks, they also don't have a planned timeline for the removal of 2.6 support either - they've only just recently added the warning to attempt to prod folks onto newer versions.

this ticket is mostly just to track this as a future todo.

**Comment by hugovk** [comment]
Python 2.6 was dropped in https://github.com/pantsbuild/pex/pull/408.

This can be closed now.

**Comment by kwlzn** [comment]
indeed, thanks.
