### ISSUE TITLE
pex fails to build pycryptodome due to filename too long

### ISSUE THREAD

**Issue by konstin** [pantsbuild/pex#2087]
I tried building a pex file for a project that has pycryptodome in its dependency tree and pex fails to include that wheel:

```
$ pex pycryptodome==3.16.0 -o pycryptodome.pex
pid 32518 -> /home/konsti/.pex/venvs/6a452ba209173892c06990a2eddf5e60e775054e/ddab8011daaee380698ac2fb9701af18c90c03f6/bin/python -sE /home/konsti/.pex/venvs/6a452ba209173892c06990a2eddf5e60e775054e/ddab8011daaee380698ac2fb9701af18c90c03f6/pex --disable-pip-version-check --no-python-version-warning --exists-action a --no-input --use-deprecated legacy-resolver --isolated -q --cache-dir /home/konsti/.pex/pip_cache install --no-deps --no-index --only-binary :all: --no-warn-script-location --force-reinstall --ignore-installed --ignore-requires-python --prefix /home/konsti/.pex/installed_wheels/e750a21d8a265b1f9bfb1a28822995ea33511ba7db5e2b55f41fb30781d0d073/pycryptodome-3.16.0-cp35-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl.a4d26b5a48ca4a8c92e788d1879f39e6.work --no-compile /home/konsti/.pex/downloads/resolver_download.e44__tz5/home.konsti.meine-stadt-transparent..venv.bin.python/pycryptodome-3.16.0-cp35-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl exited with 1 and STDERR:
ERROR: Could not install packages due to an EnvironmentError: [Errno 36] File name too long: '/home/konsti/.pex/installed_wheels/e750a21d8a265b1f9bfb1a28822995ea33511ba7db5e2b55f41fb30781d0d073/pycryptodome-3.16.0-cp35-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl.a4d26b5a48ca4a8c92e788d1879f39e6.work'
```

pex 2.1.127
Ubuntu 20.04
Python 3.8.10

**Comment by jsirois** [comment]
Hrm:
```
echo /home/konsti/.pex/installed_wheels/e750a21d8a265b1f9bfb1a28822995ea33511ba7db5e2b55f41fb30781d0d073/pycryptodome-3.16.0-cp35-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl.a4d26b5a48ca4a8c92e788d1879f39e6.work | wc -c
254
```

I have no issues running `pex pycryptodome==3.16.0 -o pycryptodome.pex` but I have:
```
$ grep -E " (NAME_MAX|PATH_MAX) " /usr/include/linux/limits.h
#define NAME_MAX         255    /* # chars in a file name */
#define PATH_MAX        4096    /* # chars in a path name including nul */
```

I'm not sure what to do about this. At some point path names will simply be too long for some systems.

@konstin what does you kernel show for those same limits?

**Comment by konstin** [comment]
yeah they do:

```
$ grep -E " (NAME_MAX|PATH_MAX) " /usr/include/linux/limits.h
#define NAME_MAX         255	/* # chars in a file name */
#define PATH_MAX        4096	/* # chars in a path name including nul */
```

i'll try to make reproducer in docker later

**Comment by jsirois** [comment]
Docker may not help much since containers run using the host kernel. You could hand me a container and if my host kernel is configured differently, I'll get a different result.

**Comment by anler** [comment]
@konstin is your file system encrypted with ecryptfs? I had the same issue but stoped after switching to full-disk encryption (luks) on mine.

**Comment by konstin** [comment]
yes it is, never considered this to make a difference

**Comment by jsirois** [comment]
Aha, big difference. See, for example: https://bugs.launchpad.net/ecryptfs/+bug/344878

Thanks for teasing that out of @konstin @anler. I'm going to mark this closed. There really isn't much PEX can do about a ~144 max path length. I know I switched off ecryptfs >10 years ago after hitting path name length issues in other software.

**Comment by jsirois** [comment]
@konstin this is a bit of a pain to test from a non-eCryptFS system, but if you have a chance to try out the forthcoming PR, I'd be grateful. I'll post instructions on the PR and ping you there.

**Comment by konstin** [comment]
it now works on main, thanks

**Comment by jsirois** [comment]
Ok, great. Thanks for checking @konstin. That's also available in released form at:
+ https://pypi.org/project/pex/2.1.143/
+ https://github.com/pantsbuild/pex/releases/tag/v2.1.143
