### ISSUE TITLE
Universal lock file might not contain platform-dependent dependencies

### ISSUE THREAD

**Issue by misberner** [pantsbuild/pex#2124]
- **Sample command:** `pex3 lock create --style=universal 'torch==2.0.0'`
- **Expected behavior:** A lockfile is created with all (transitive) dependencies of packages matching the `torch==2.0.0` for all platforms.
- **Observed behavior:** Lockfile does not reference dependencies of packages for Linux (`nvidia-*` packages, `triton-2.0.0`).

Without knowing too much about the internals of Pex, it looks like only the first wheel is taken into account (in my case, that's https://files.pythonhosted.org/packages/9f/cd/670e5e178db87065ee60f60fb35b040abbb819a1f686a91d9ff799fc5048/torch-2.0.0-1-cp310-cp310-manylinux2014_aarch64.whl ) and inspected for dependencies. The `torch-2.0.0.dist-info/METADATA` file for this wheel lists:
```
Requires-Dist: filelock
Requires-Dist: typing-extensions
Requires-Dist: sympy
Requires-Dist: networkx
Requires-Dist: jinja2
Provides-Extra: opt-einsum
Requires-Dist: opt-einsum (>=3.3) ; extra == 'opt-einsum'
```
which matches the lockfile output:
```
          "project_name": "torch",
          "requires_dists": [
            "filelock",
            "jinja2",
            "networkx",
            "opt-einsum>=3.3; extra == \"opt-einsum\"",
            "sympy",
            "typing-extensions"
          ],
```

However, one of the linux/amd64 wheels (https://files.pythonhosted.org/packages/5f/24/16e94ac3a470027a2f6cf56dbbe2ce1b2742fa0ac98844f039fad103e142/torch-2.0.0-cp39-cp39-manylinux1_x86_64.whl) lists the following in its `METADATA` file:
```
Requires-Dist: filelock
Requires-Dist: typing-extensions
Requires-Dist: sympy
Requires-Dist: networkx
Requires-Dist: jinja2
Requires-Dist: nvidia-cuda-nvrtc-cu11 (==11.7.99) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cuda-runtime-cu11 (==11.7.99) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cuda-cupti-cu11 (==11.7.101) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cudnn-cu11 (==8.5.0.96) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cublas-cu11 (==11.10.3.66) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cufft-cu11 (==10.9.0.58) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-curand-cu11 (==10.2.10.91) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cusolver-cu11 (==11.4.0.1) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cusparse-cu11 (==11.7.4.91) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-nccl-cu11 (==2.14.3) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-nvtx-cu11 (==11.7.91) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: triton (==2.0.0) ; platform_system == "Linux" and platform_machine == "x86_64"
Provides-Extra: opt-einsum
Requires-Dist: opt-einsum (>=3.3) ; extra == 'opt-einsum'
```
where all the platform-specific dependencies are absent from the universal lockfile.

Is this a bug, or is my understanding of what should be in the universal lockfile just wrong? Many thanks!

**Comment by jsirois** [comment]
This is known behavior. Pex does in fact expect all metadata to be uniform for a given family of artifacts for a given version (as do the PyPI APIs). Pulling down, sometimes, 10+ wheels per project version is not feasible. I'm pretty sure every locker in the Python ecosystem is in the same boat here.

**Comment by jsirois** [comment]
@misberner I'm going to close this as a won't fix, but you're describing a real problem with torch plenty of others have hit in the Pants community. Afaict torch is badly behaved here and some pressure on that project is warranted to fix its artifact design and publishing. If all projects were to do similar, resolves in the Python ecosystem would become ~impossible / time prohibitive.

**Comment by jsirois** [comment]
This thread on the rejected [PEP-665](https://peps.python.org/pep-0665/) has some discussion of this problem: https://discuss.python.org/t/pep-665-specifying-installation-requirements-for-python-projects/9911

**Comment by misberner** [comment]
Thanks for the prompt response and explanation @jsirois ! This makes sense and was what I had suspected. I thought for some reason that `pex` would download all the wheels for checksum computation, but I guess the checksums simply come from the index.

**Comment by jsirois** [comment]
That's correct re checksums but if they are not available, as they sometimes aren't, Pex does in fact download them to checksum. You're missing the serious of the issue though. That step is _post_ resolve solution. If a locker has to assume this behavior in all project metadata, then the problem compounds during resolution. Say the 18th dependency I'm resolving, foo 1.2.3 has a requirement `bar>=1.0` and say there are 25 releases of bar meeting that criteria, each with 10 artifacts. Mind you, this was just for foo 1.2.3! The resolve may need to examine foo 1.2.4, etc.

**Comment by jsirois** [comment]
As noted in the PEP-665 discussion thread, the use case for variance appears to be platform dependency differences but this is already accounted for by environment markers: https://peps.python.org/pep-0508/#environment-markers

Using those, you can supply a single, uniform requirement list that will have varying effective content per platform.

Basically this is another case of the PyPA not having yet got around to taming organic growth in an under constrained ecosystem.
