### ISSUE TITLE
Add option to include a Python package/module in the Pex

### ISSUE THREAD

**Issue by lordmauve** [pantsbuild/pex#2134]
The `-D DIR` option adds directory entries in `DIR` at the root of the Pex import namespace.

This is awkward given a typical workspace layout like

```
.github/workflows/...
pyproject.toml
README.md
.venv/...
myapp/__init__.py
```

as giving `-D .` includes lots of junk that is also in the workspace (up to and including whole virtualenvs) and giving `-D myapp` does not create a `myapp` package in the Pex, it puts `__init__.py` into the root instead.

A workspace layout with a `src/` directory works but it means that a plain `python` command cannot import `myapp`.

I would propose adding an option (say `-P`) to include a single Python package or module in the PEX.

With this option:

* `-P myapp` would copy the `myapp` package into the PEX and make it importable as `myapp`
* `-P myapp.py` would copy the `myapp.py` module into the PEX and make it importable as `myapp`

**Comment by jsirois** [comment]
So, Pex itself has this problem, but it, like most Python projects, has a project metadata file; so Pex uses `pex . -c pex -o pex.pex` to build itself as a PEX. Even though the `.` dir contains the `pex` package it also contains the `scripts` dir, etc but the built `pex.pex` contains none of this. Does that suffice?

**Comment by jsirois** [comment]
Fwiw the actual production release build of the Pex PEX released to GitHub releases uses this:
https://github.com/pantsbuild/pex/blob/382d7aa1fdb89072cb33863565ff67e45000a4f3/scripts/package.py#L28-L59

**Comment by lordmauve** [comment]
Ah, I'm seeking to avoid needing our applications to build with setuptools/flit/poetry. This is in a corporate environment, for context.

We've tended to distinguish between libraries and applications. Libraries publish wheels and sdists so they need a package build tool - but the bar is generally going to be higher, ensuring they work across Python versions, dependency versions and so on.

But applications just run with a `requirements.txt` and some Python code. That feels like less for user to think about, particularly when it comes to versioning. For deployment we just have to provide a virtualenv with the requirements. We're exploring Pex for this CLI applications. For services we will just build Docker images.

I now have a workaround that I'm happy with, which is to export the package tree into a temp dir using git. Unlike a plain copy, which only exists to overcome pex's command line limitations, it has the desirable side-effect of excluding untracked files and uncommitted changes, so that seems to justify it a little more:

```bash
TMPDIR="$(mktemp -d)"
trap 'rm -rf -- "$TMPDIR"' EXIT
git archive HEAD myapp | tar x -C "$TMPDIR"
pex -D "$TMPDIR"
```

**Comment by jsirois** [comment]
> Ah, I'm seeking to avoid needing our applications to build with setuptools/flit/poetry. This is in a corporate environment, for context.

Aha, Ok. Your OP included a `pyproject.toml` mention and I assumed. Well, you are carving a niche I have not heard about use of yet which is large corp / project, uses Pex but doesn't use Pants. Pants would allow you this control and generate a PEX.

So your use case is not unreasonable (Pants rolls this way - not forcing and in fact even discouraging a python distribution for anything but to-be-published libraries). The trick is just nailing down the interface here. I could imagine an extension of the current syntax like `-D myapp=myapp`, where the `=` is the trigger to take the LHS as the directory to use and the RHS as the prefix to give files in that directory.

**Comment by khaledh** [comment]
We have a similar use for packaging pyspark jobs with pip dependencies. Packaging the pip dependencies is fine, but including the job module (and other modules it imports) is cumbersome. We don't want to create package metadata for each job, we just want to include a few directories in the resulting pex file and have them being importable at runtime.

The `-D myapp=myapp` syntax would be fantastic.

**Comment by jsirois** [comment]
@khaledh thanks for chiming in with a second use case. @lordmauve I've gone with your suggestion roughly. `-P foo` to grab package `foo` and all sub-packages in the CWD with support for `-P foo.bar` and, finally `-P foo@src` for functionality ~redundant with `-D src` when foo is the only top-level package, but otherwise providing more selction flexibility when it is not. Likewise there is a `-M` option to pick out individual modules.
