### ISSUE TITLE
Duplicate constraints sometimes ignored

### ISSUE THREAD

**Issue by tgolsson** [pantsbuild/pex#2149]
Hello,

Runnable repro: https://github.com/tgolsson/pants-repros/tree/main/sentry-lost-constraint

As the readme there says, Pants 2.15.0 + Pex v2.1.129 is *randomly* failing to lock correctly. Sentry has the following constraints for urllib3:

```json
        [
            "urllib3<2.0.0",
            "urllib3>=1.25.7; python_version <= \"3.4\"",
            "urllib3>=1.26.11; python_version >= \"3.6\"",
            "urllib3>=1.26.9; python_version == \"3.5\""
        ]
```

But the lockfile will (randomly) resolve with the below for urllib3. Note that the locked version is 2.0.2. The other version it will find is 1.26.15, which is permissible with all constraints. I've not tested extensively but it seems to be 50/50 which one it ends up locking, with no huge bias to either one. I didn't see anything in the changelog from the few latest releases that would affect this.

``` json
          "artifacts": [
            {
              "algorithm": "sha256",
              "hash": "d055c2f9d38dc53c808f6fdc8eab7360b6fdbbde02340ed25cfbcd817c62469e",
              "url": "https://files.pythonhosted.org/packages/4b/1d/f8383ef593114755429c307449e7717b87044b3bcd5f7860b89b1f759e34/urllib3-2.0.2-py3-none-any.whl"
            },
            {
              "algorithm": "sha256",
              "hash": "61717a1095d7e155cdb737ac7bb2f4324a858a1e2e6466f6d03ff630ca68d3cc",
              "url": "https://files.pythonhosted.org/packages/fb/c0/1abba1a1233b81cf2e36f56e05194f5e8a0cec8c03c244cab56cc9dfb5bd/urllib3-2.0.2.tar.gz"
            }
          ],
```

**Comment by jsirois** [comment]
That is an absolutely bizarre set of requirements. I'm surprised Pip doesn't just die with a dup requirement error. It should just be 3 requirements, each with the existing marker but also the upper bound from the current 1st requirement.

I'll take a look later today or tomorrow.

**Comment by tgolsson** [comment]
Fully in agreement. :P

**Comment by tgolsson** [comment]
For what it's worth, I cannot repro this without pants, though I'm definitely not doing a 1-1 repro given my unfamiliarity with Pants/Pex invocation styles... Raw pip seems to work fine (consistently picks 1.26), and raw pex seems to complain about duplicate dependencies. PDM and poetry also pick 1.26... Not sure what's going on.

**Comment by jsirois** [comment]
Apples to apples this works fine.
```
$ pex3 lock create --style universal --resolver-version pip-2020-resolver --pip-version latest --interpreter-constraint "==3.9.*" --target-system linux --target-system mac --indent 2 -o lock.json sentry-sdk==1.22.2
```

The apples here is Pip. Pants defaults to Pex default which is 20.3.4 which picks urllib3 2.0.2. Using `--pip-version latest` (which is currently 23.1.2), picks urllib3 1.26.15.

**Comment by jsirois** [comment]
@tgolsson I'm going to close this as answered. Pants supports setting `--pip-version` in 2.16.x+:
+ https://www.pantsbuild.org/v2.16/docs/reference-python#pip_version
+ https://www.pantsbuild.org/v2.17/docs/reference-python#pip_version

The 23.0.1 supported by 2.16.x appears to be enough to get the expected result of urllib3 1.26.15.

Let me know if you have further questions.

**Comment by tgolsson** [comment]
Ah dang it. I downgraded to 20.0 but couldn't repro there either, maybe bad luck. Hopefully 2.16 is out soon then! :-) Thank you.
