### ISSUE TITLE
Pex file looses the executable permission of a binary file if packaged 

### ISSUE THREAD

**Issue by sumitsanghrajka** [pantsbuild/pex#223]
I have a use case where the pex file I am generating has to package another statically compiled binary. 
When the pex file is exploded the binary file has lost the executable permission. Is there anyway to preserve the permissions?

**Comment by kwlzn** [comment]
are you sure the binary is executable before being composed into the pex? how are you including the binary? how are you extracting/invoking it?

we have several cases where we package binaries as resources in libraries and then compose those libraries into a pex  - and AFAICT this has never been a problem.

a repro would be helpful to understand the exact situation you're facing.

**Comment by snyaggarwal** [comment]
Still happening with version 1.2.6:
Reproducible code is in foo.zip.
foo/yo/bar.sh has executable permissions.
After unzip run -- pex . -e bar.console:run -o foobar.pex -v
the pex file wont have executable permissions on bar.sh

[foo.zip](https://github.com/pantsbuild/pex/files/943355/foo.zip)

Is there anyway to preserve the permissions?
