### ISSUE TITLE
Pex doesn't include my code

### ISSUE THREAD

**Issue by bishopmatthew** [pantsbuild/pex#225]
This is probably just me misunderstanding something, but I can't get pex to include my code in the output .pex file. Here's my project structure:
```
├── README.md
├── mock-api.pex
├── mock_api
│   ├── __init__.py
│   ├── api.py
│   ├── auth.py
│   ├── constants.py
│   ├── index.py
│   ├── java_generator.py
│   ├── misc.py
│   ├── mock_api.py
│   ├── save.py
│   └── utils.py
├── requirements.txt
├── setup.py
└── templates
    └── MockUser.java
```

And I'm building my pex file with:
`pex -c mock_api/mock_api.py -o mock-api.pex -r requirements.txt`

Which outputs `mock-api.pex` which includes my dependencies 
```
click==6.2
furl==0.4.9
Jinja2==2.8
ordered-set==2.0.1
orderedmultidict==0.7.5
ply==3.8
pycrypto==2.6.1
requests==2.9.1
six==1.10.0
wheel==0.24.0
```

But doesn't include any of my code. Any idea what I'm doing wrong?

**Comment by kwlzn** [comment]
it doesn't look like you're including your own package in the pex build. you should be pointing pex to the directory that your setup.py exists in so it can package that code up in addition to your dependencies.

and `-c` is for console scripts as entrypoints - unless mock_api.py is a console script, you probably just want a normal `-e` entrypoint.

something like this:

`pex . -r requirements.txt -e mock_api:main -o mock-api.pex`

**Comment by bishopmatthew** [comment]
Thanks! 

Definitely revealing my own ignorance here, but I can't figure out what this error means:

`pex.resolvable.InvalidRequirement: Unknown requirement type: .`

My setup.py:
```
from setuptools import setup, find_packages
setup(
    name = "Mock Api",
    version = "0.1",
    packages = find_packages(),
)
```

**Comment by kwlzn** [comment]
hmm, what's the context of that error?

here's a similar example of pexing 'wheel' from its sources with extra deps via a `requirements.txt`:

```
[illuminati wheel-0.29.0]$ pex --version
pex 1.1.4
[illuminati wheel-0.29.0]$ pwd
/Users/kwilson/Downloads/wheel-0.29.0
[illuminati wheel-0.29.0]$ ls -al setup.py
-rw-r--r--@ 1 kwilson  staff  2047 Feb  5 12:42 setup.py
[illuminati wheel-0.29.0]$ echo "requests" > requirements.txt
[illuminati wheel-0.29.0]$ pex . -r requirements.txt -v
  requests 2.9.1x :: Resolving distributions :: Packaging wheel
  wheel 0.29.0
pex: Building pex: 535.8ms                                     
pex:   Resolving distributions: 315.5ms
pex:       Packaging wheel: 188.4ms
Running PEX file at /var/folders/3t/xkwqrkld4xxgklk2s4n41jb80000gn/T/tmp0ARe4h with args []
pex: PEX.run invoking /Users/kwilson/Python/CPython-2.7.11/bin/python2.7 /var/folders/3t/xkwqrkld4xxgklk2s4n41jb80000gn/T/tmp0ARe4h
Python 2.7.10 (default, Dec 16 2015, 14:09:45) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> 
```

**Comment by bishopmatthew** [comment]
Not sure what the problem was, I went on a bit of a random walk of problem solving. But it works now. One thing that wasn't obvious to me is that `-o` was only pulling in changes to my code if I bumped the version number in setup.py. Which makes sense, but isn't totally obvious.

Anyways, it's working so thanks again for the help!

**Comment by kwlzn** [comment]
ah, I believe that's just package caching in effect. you should be able to use `--disable-cache` to avoid this behavior.

**Comment by grimreaper** [comment]
>Not sure what the problem was, I went on a bit of a random walk of problem solving.
For anyone else that runs into this in the future: I got bit by not having an `__init__.py` file. Interestingly this not a sufficient condition for this error to occur since at one point a similar setup was working without one. Unsure of what changed in between.
