### ISSUE TITLE
Handle eggs for libraries with versions containing _ in the filename

### ISSUE THREAD

**Issue by baroquebobcat** [pantsbuild/pex#226]
In 1.1.3, there was a change that caused the versions of packages to not be normalized anymore. This is a problem because the egg filename spec normalizes versions using to_filename, which turns '-'s into '_'s. So, any egg with a version containing an '-' or any character normalized to a '-' can't be resolved with pex's resolver.

**Comment by mikekap** [comment]
Sorry about that. Looks like this is a bug due to an old `pkg_resources` used for packing the egg - the new versions don't do anything to the version: https://github.com/pypa/setuptools/blob/master/pkg_resources/__init__.py#L1381 . The proper fix looks like using `safe_version`. I'll send a PR.

**Comment by baroquebobcat** [comment]
Sure. Here's a foobarified version: `pyfoo-1.0.0_bar-py2.7-linux-x86_64.egg`, where the normalized version is `1.0.0-bar`.

For reference, here's the egg filename metadata docs https://pythonhosted.org/setuptools/formats.html#filename-embedded-metadata

I *think* what we'd need to do is check the normalized safe_version-ified versions against eachother, then if they match pull down the egg and check the internal metadata which isn't filename-ified, just to be sure.

If we could ensure that pex always used a setuptools >=8.0 for the `.bootstrap/pkg_resources.py`, then local versions ought to work generally--though I haven't played with how they interact with egg naming conventions.

**Comment by mikekap** [comment]
I think I rather just drop support for local specifiers if the `pkg_resources` you're using doesn't support them properly. The spec is out of date with what `setuptools` actually does, which is normalization according to https://www.python.org/dev/peps/pep-0440/ only. This would require that your eggs' `pkg_resources` needs to be <= pex's `pkg_resources`, which is reasonable.
