### ISSUE TITLE
Once we release 2.1.150, Restore RTD "default version" to it if needed.

### ISSUE THREAD

**Issue by benjyw** [pantsbuild/pex#2267]
A change in RTD's own settings caused the 2.1.148 doc build to break. 

The breakage has been fixed in https://github.com/pantsbuild/pex/pull/2266, so the next release's docs will build. But until then, I've manually configured the "default version" on RTD's Admin -> Advanced Settings, which pointed to "v2.1.148" to point to "latest", so that https://pex.readthedocs.io/ isn't broken. ("latest" points to the latest SHA, not the latest release, AFAICT).

Once 2.1.149 is released we may need to manually repoint it (or this may happen automatically, I haven't dug into how RTD normally updates this).

**Comment by jsirois** [comment]
It looks like this automation rule handles activating any new incoming tag as the default version; so the ship should right itself automatically: https://readthedocs.org/dashboard/pex/rules/regex/865/

**Comment by jsirois** [comment]
It looks like this automation rule handles activating any new incoming tag as the default version; so the ship should right itself automatically: https://readthedocs.org/dashboard/pex/rules/regex/865/

**Comment by jsirois** [comment]
Alrighty. They are changing all the things - new failure: https://readthedocs.org/projects/pex/builds/22435029/:

![image](https://github.com/pantsbuild/pex/assets/157586/ab6edb1a-f7d8-48a0-8a85-41f9cffe8f06)

The fix for that is outlined here: https://blog.readthedocs.com/migrate-configuration-v2/

**Comment by benjyw** [comment]
> It looks like this automation rule handles activating any new incoming tag as the default version; so the ship should right itself automatically: https://readthedocs.org/dashboard/pex/rules/regex/865/

I'd hoped that was the case, but I wasn't sure if my manually resetting it would somehow prevent it automatically righting itself (I didn't dig into how those get set, but I concur that this automation rule should do the trick).

**Comment by jsirois** [comment]
Yeah - it did do the trick. The now-failing-in-a-new-way RTD build has undone your manual pointing fix. You should find https://pex.readthedocs.io -> https://pex.readthedocs.io/en/v2.1.149/ which is broken now.

**Comment by jsirois** [comment]
Ok, #2275 has fixed the RTD build and I've pointed the default version at latest for now. Hopefully the 2.1.150 Pex release triggers a self-righting of the default version.

**Comment by jsirois** [comment]
Ok, the auto-reset worked. https://pex.readthedocs.io now re-directs to https://pex.readthedocs.io/en/v2.1.150/ with no intervention on my part.
