### ISSUE TITLE
Documentation website is down/missing

### ISSUE THREAD

**Issue by Garulf** [pantsbuild/pex#2337]
404 Not Found error when attempting to access documentation at: [pex.readthedocs.io](https://pex.readthedocs.io/)

![image](https://github.com/pantsbuild/pex/assets/535299/908d64bd-d748-45b6-9490-60252b641a6c)

**Comment by benjyw** [comment]
Thanks for the report! We'll look into this ASAP. 

Meanwhile this slightly earlier version appears to work: https://pex.readthedocs.io/en/v2.1.156/

**Comment by benjyw** [comment]
Latest docs now build: https://pex.readthedocs.io/en/latest/

I've temporarily set the default version to 2.1.156 (instead of 2.1.159) so that https://pex.readthedocs.io/ doesn't 404. This will reset automatically on the next release.

**Comment by jsirois** [comment]
Thanks @benjyw. I was just updating science to the PBS 3.12.1 release et. al. and had my `nox -e doc linkcheck` fail because - low and behold:
```
Warning, treated as error:
/home/jsirois/dev/a-scie/lift/docs/_/manifest/interpreter.md:3:broken link: https://python-build-standalone.readthedocs.io (404 Client Error: Not Found for url: https://python-build-standalone.readthedocs.io/)
nox > Command sphinx-build -b linkcheck -aEW /home/jsirois/dev/a-scie/lift/docs /home/jsirois/dev/a-scie/lift/docs/build/linkcheck failed with exit code -11
nox > Session linkcheck-3.12 failed.
nox > Ran multiple sessions:
nox > * doc-3.12: success
nox > * linkcheck-3.12: failed
```
It looks like he got fed up too some time ago: https://gregoryszorc.com/docs/python-build-standalone/main/
