### ISSUE TITLE
Old version of setuptools?

### ISSUE THREAD

**Issue by ariscn** [pantsbuild/pex#238]
https://github.com/pantsbuild/pex/blob/master/pex/version.py pins setuptools `<20`. Are there any known issues with more recent versions?

**Comment by jsirois** [comment]
No known, issues, but no research either.  If you don't mind consulting the CHANGELOGs, testing and sending a PR noting all this, that would be wonderful.

**Comment by jsirois** [comment]
In preparation for the [1.1.5 release](#237) I though about widening the pin range, but the CHANGELOG is large and will take some careful vetting alnog with the switch to v-prefixed versions: https://pythonhosted.org/setuptools/history.html

**Comment by ariscn** [comment]
I've been using the latest setuptools with pex for a few days without issue so far.

**Comment by jsirois** [comment]
@ariscn - If you're available to review #244 I'd be grateful.

**Comment by jsirois** [comment]
Fix is in master @ https://github.com/pantsbuild/pex/commit/ab2b5113cacb1926db2f4652256a2b300118968e

**Comment by ariscn** [comment]
Nice! Will upgrade to master now and report back if anything breaks.

**Comment by epu** [comment]
@ariscn Did anything break? Could there be a new release, or is more testing needed?

**Comment by ariscn** [comment]
There have been several Pex releases since I opened this issue. :-)

**Comment by epu** [comment]
Ah, ok. I'm having the same issue with a module requesting latest setuptools (22.0.0). I guess I can roll my own and see how it goes.
