### ISSUE TITLE
default caching in the pex tool is incorrect

### ISSUE THREAD

**Issue by wickman** [pantsbuild/pex#24]
if you do pex --repo=/tmp/path/to/my/repo -r req and that requirement gets pulled into $PEX_ROOT/build, subsequent calls to 'pex -r req' will resolve to the version in $PEX_ROOT/build if 'req' is ahead of the PyPI tip.  this is unexpected default behavior. the pex tool should only do this if --cache/--cache-ttl are both specified.

**Comment by sholsapp** [comment]
@wickman +1 to this issue -- that was a big surprise. :)

**Comment by wickman** [comment]
https://rbcommons.com/s/twitter/r/2076/ addresses this for the most part (source packages are always built...but it removes the -s option in favor of being uniform with pip.)

**Comment by wickman** [comment]
should be fixed by c93ea9c7.
