### ISSUE TITLE
When building cross-platform pex, stymied by abi tag for linux packages

### ISSUE THREAD

**Issue by ericzundel** [pantsbuild/pex#250]
I'm using pants 1.0.0 to build a cross platform pex (for pants itself)
The version of pex used by pants is pex==1.1.2

We created some wheels with `pip --wheel ` and they look like:

```
$ ls *linux*
lmdb-0.89-cp27-cp27mu-linux_x86_64.whl          
pywatchman-1.3.0-cp27-cp27mu-linux_x86_64.whl  
...
```

But when we try to link in these wheels with our pants target, the pex resolver can't find them:

```
Exception message: Could not get distribution for SourcePackage(u'file:///Users/zundel/Development/java/.pants.d/python-setup/resolved_requirements/CPython-2.7.10/PyYAML-3.11.tar.gz') on platform linux-x86_64.
```

On a hunch, I found that if I rename the wheels to remove the cp27mu field (This is the 'abi' tag on the wheel as per: PEP-427[1]

```
lmdb-0.89-cp27-none-linux_x86_64.whl          
pywatchman-1.3.0-cp27-none-linux_x86_64.whl 
```

Now pex can resolve them.  Is this expected behavior?  If so:

Is there something I can do in pants/pex to allow it to use wheels with this ABI tag?
Does anyone know how to get pip to generate these wheels with an abi tag of `none` (other than just renaming them)?

Here's a snippet from the PEP-425[2] doc. 

> Why is the ABI tag (the second tag) sometimes "none" in the reference implementation?
> Since Python 2 does not have an easy way to get to the SOABI (the concept comes from newer versions of Python 3) the reference implentation at the time of writing guesses "none". Ideally it would detect "py27(d|m|u)" analagous to newer versions of Python, but in the meantime "none" is a good enough way to say "don't know".

Maybe the weird thing is that this wheel that got generated has both an `m` and a `u` suffix?  In ~/.pex/install I see that when pex caches them, it uses `cp27m`:

```
ls -d ~/.pex/install/*cp27m*
/Users/zundel/.pex/install/PyYAML-3.11-cp27-cp27m-linux_x86_64.whl.1ac921760b77435dc948b81372d7a03034ef2795
/Users/zundel/.pex/install/pywatchman-1.3.0-cp27-cp27m-linux_x86_64.whl.26077f5592aa3f150a6101aba73e3f5c3146b416
/Users/zundel/.pex/install/setproctitle-1.1.9-cp27-cp27m-linux_x86_64.whl.74786c3aa705b664033287ed98a888031299acbe
```

[1]:https://www.python.org/dev/peps/pep-0427
[2]:https://www.python.org/dev/peps/pep-0425/

**Comment by kwlzn** [comment]
any clue what pex release you're on? I'd halfway expect this to work based on: https://github.com/pantsbuild/pex/commit/0b1e5fdd1b6f33bd7ab1828c986c40e384dbb9e9

but I've also heard recent anecdotal stories that it does not work against wheels generated by the `manylinux` docker image (which also use the `cp27mu` abi tag - `m` denotes with 'pymalloc' support and `u` denotes wide unicode). have not yet dug in, but we'll also need this soon. if you guys have cycles, I'd be happy to review any PRs or otherwise will plan to dig into this myself sometime in the next few weeks.

**Comment by ericzundel** [comment]
pex is at 1.1.2 in the Pants 1.0 release, looks like it does not include that change.

```
commit 0b1e5fdd1b6f33bd7ab1828c986c40e384dbb9e9
Author: Eric Wang <eric1990@gmail.com>
Date:   Thu Mar 10 19:17:03 2016 -0800

    Add python 2.x abi tag support
```

**Comment by kwlzn** [comment]
aha - that would make sense. I believe there was a resolution regression in 1.1.3 which caused a rollback to 1.1.2 in pants master. I'd try a simple version bump here and see if that works.

**Comment by ericzundel** [comment]
I built a custom version of pants that was updated to pex 1.1.6 and this problem went away.
