### ISSUE TITLE
Update PyPI page

### ISSUE THREAD

**Issue by johnthagen** [pantsbuild/pex#256]
It would be nice if the `README.rst` were included in the `setup.py` `long_description` in addition to the `CHANGES.rst` so that users browsing PyPI could read the README without having to travel to GitHub.

Would also be nice if the trove classifiers in `setup.py` reflected which versions of Python were officially supported (e.g. `'Programming Language :: Python :: 3.5'`).

**Comment by jsirois** [comment]
SGTM, happy to review your pull request(s) if you have time.

**Comment by kwlzn** [comment]
fyi, this change is live on pypi as of the 1.1.7 release: https://pypi.python.org/pypi/pex/1.1.7
