### ISSUE TITLE
Unable to execute pex utility on Windows

### ISSUE THREAD

**Issue by johnthagen** [pantsbuild/pex#259]
I don't see any mention of Windows in the docs, so perhaps `pex` simply doesn't support Windows, but I get the following errors when trying to do a [simple install and run](http://pex.readthedocs.io/en/stable/buildingpex.html#invoking-the-pex-utility) of `pex` on Windows 10.

```batch
>python -V
Python 3.5.1

>pip -V
pip 8.1.2 from c:\users\john hagen\appdata\local\programs\python\python35\lib\site-packages (python 3.5)

>pip install pex
Collecting pex
  Downloading pex-1.1.6-py2.py3-none-any.whl (99kB)
    100% |################################| 102kB 1.3MB/s
Requirement already satisfied (use --upgrade to upgrade): setuptools<20.11,>=2.2 in c:\users\john hagen\appdata\local\programs\python\python35\lib\site-packages\setuptools-20.10.1-py3.5.egg (from pex)
Installing collected packages: pex
Successfully installed pex-1.1.6

>pex
Traceback (most recent call last):
  File "c:\users\john hagen\appdata\local\programs\python\python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\john hagen\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\John Hagen\AppData\Local\Programs\Python\Python35\Scripts\pex.exe\__main__.py", line 9, in <module>
  File "c:\users\john hagen\appdata\local\programs\python\python35\lib\site-packages\pex\bin\pex.py", line 509, in main
    pex_builder = build_pex(reqs, options, resolver_options_builder)
  File "c:\users\john hagen\appdata\local\programs\python\python35\lib\site-packages\pex\bin\pex.py", line 444, in build_pex
    interpreter = interpreter_from_options(options)
  File "c:\users\john hagen\appdata\local\programs\python\python35\lib\site-packages\pex\bin\pex.py", line 437, in interpreter_from_options
    interpreter = resolve(interpreter, WHEEL_REQUIREMENT)
  File "c:\users\john hagen\appdata\local\programs\python\python35\lib\site-packages\pex\bin\pex.py", line 410, in resolve_interpreter
    installer_provider)
  File "c:\users\john hagen\appdata\local\programs\python\python35\lib\site-packages\pex\bin\pex.py", line 361, in _resolve_and_link_interpreter
    egg = EggPackage(os.path.realpath(target_link))
  File "c:\users\john hagen\appdata\local\programs\python\python35\lib\site-packages\pex\package.py", line 150, in __init__
    raise self.InvalidPackage('Not an egg: %s' % filename)
pex.package.InvalidPackage: Not an egg: wheel
```

I even tried using the `--no-binary` flag for `pip`, but it resulted in the same error:
```batch
C:\Users\John Hagen>pip install --no-binary :all: pex
Collecting pex
  Downloading pex-1.1.6.tar.gz (472kB)
    100% |################################| 481kB 1.6MB/s
Requirement already satisfied (use --upgrade to upgrade): setuptools<20.11,>=2.2 in c:\python35\lib\site-packages (from pex)
Installing collected packages: pex
  Running setup.py install for pex ... done
Successfully installed pex-1.1.6
```

Before I went trying to investigate this too far, I wanted to check to see if Windows is really a supported platform to begin with.

**Comment by kwlzn** [comment]
pex does not currently claim windows support. however, there have been a handful of recent PRs from the Buck team that have moved the needle to the point that some folks  are making this work with modifications - see: https://github.com/pantsbuild/pex/issues/230

ultimately, windows support is something that the primary developers of pex do not have a need for or interest in (we are all mostly UNIX shops). if a reliable owner can be established to implement and maintain this functionality tho (including setup of AppVeyor for CI on windows, etc), we'd be amenable to that. it just hasn't materialized yet.

**Comment by nfx** [comment]
@kwlzn i've landed on this issue from different perspective - would linux-built `.pex` files run on windows?...

**Comment by TheXenocide** [comment]
Came seeking windows support and not entirely sure what the issue is around symlinks, but depending on what version of windows you're aiming for, symlink support has been improved in newer versions of windows (NTFS has supported a similar concept for awhile, but they have been making them more accessible like by adding `mklink` command line tooling and other improvements since Windows 10).

**Comment by TheXenocide** [comment]
Oh, apologies, just saw that it appears there are limitations on how many times a file can be linked? I didn't realize there was a significant limit on that. Either way, consider this my vote for being able to use pex on windows 🙏😅
