### ISSUE TITLE
pex does not support the compatible release clause

### ISSUE THREAD

**Issue by agandhi4** [pantsbuild/pex#266]
I'm trying to incorporate the use of hyper into my pants project, however, I'm running to an issue. Here is the breakdown:

```
$ pip show pex

---
Metadata-Version: 2.0
Name: pex
Version: 1.1.8
...

$ pex hyper==0.6.0
...
ValueError: ('Expected version spec in', 'hyperframe ~=3.2', 'at', ' ~=3.2')
```

This spec is outlined here: https://www.python.org/dev/peps/pep-0440/#compatible-release. I can get the command to work if I change the setup.py of hyper to be hyperframe>=3.2,<4.0, rather than hyperframe~=3.2

**Comment by agandhi4** [comment]
Seems like there is already an issue for this, but seems to be buried

https://github.com/pantsbuild/pex/issues/50

**Comment by kwlzn** [comment]
noting that I'm no longer able to repro this with the latest pex and a current setuptools:

```
[omerta ~]$ pex --version
pex 1.2.5
[omerta ~]$ pex hyper==0.6.0
Python 2.7.10 (default, Dec 16 2015, 14:09:45) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import hyper
>>> hyper.__file__
'/private/var/folders/bb/msvj_4_s741g93nzgrj19twc0000gn/T/tmpdaLsUE/.deps/hyper-0.6.0-py2.py3-none-any.whl/hyper/__init__.py'
>>> 
```

marking as closed - but feel free to reopen if you can provide a new repro.
