### ISSUE TITLE
bdist_pex.run() doesn't resolve cache-dir's "{pex_root"}

### ISSUE THREAD

**Issue by weigon** [pantsbuild/pex#274]
bdist_pex.run() doesn't rewrite the {pex_root} token as the "pex" cmdline frontend does which leads
to a directory named "{pex_root}/" in the root-folder of the project.

Adding the same rewrite to pex/commands/bdist_pex.run() fixes it:

    if options.cache_dir:
      options.cache_dir = make_relative_to_root(options.cache_dir)

Introduced by #206

**Comment by kwlzn** [comment]
@weigon thanks for the bug report.

@digwanderlust this is related to your `--pex-root` change - can you take a look?
