### ISSUE TITLE
Filter prerelease versions in package iterators by default

### ISSUE THREAD

**Issue by wickman** [pantsbuild/pex#28]
Pip has the `--pre` flag -- we should allow similar behavior.

**Comment by jsirois** [comment]
OK - modern pip does this via `packaging` which has only been around since 2014.  We support `setuptools>=2.2,<16` and 2.2 does not use packaging.  I have not dug deeper, but I want to take a bit more care if I implement this, so I'm going to drop from the 1.1 release and move to a 1.2 milestone.

**Comment by daveFNbuck** [comment]
+1, pulling in prerelease versions is probably worse than not supporting old setuptools. The logic is pretty simple, perhaps we could just reimplement it if old setuptools support is a priority.

**Comment by jsirois** [comment]
OK - looking back into this, it looks like the only version of setuptools that depends on packaging is `7.0b1`. The `7.0` version doesn't use packaging and the `8.0` version uses it, but it pulls from a vendored version. So one option is to exclude 7.0b1, ie add `!=7.0b1` to our requirement string, and then add our own dependency on `packaging` (16.8) at a top level to pick up [`packaging.specifiers.SpecifierSet`](https://packaging.pypa.io/en/latest/specifiers/#reference) which has the logic we need with a `prereleases` flag we can toggle.

I'll take a spin at this presently.

**Comment by daveFNbuck** [comment]
Thanks @jsirois!

**Comment by jsirois** [comment]
This is in and will go out with the [`1.2.0`](https://github.com/pantsbuild/pex/issues/345) release - likely to be published and consumed by pants in this Friday's `1.3.0.dev8` pants release.

**Comment by daveFNbuck** [comment]
Thanks again for the quick turnaround on this!
