### ISSUE TITLE
.bootstrap import path leak for pkg_resources in pex

### ISSUE THREAD

**Issue by kwlzn** [pantsbuild/pex#307]
with the default `sys.path` construction in pex, the `.bootstrap` dir ends up at the tip of `sys.path` which causes the [baked-in](https://github.com/pantsbuild/pex/blob/master/pex/pex_builder.py#L352-L380) `pkg_resources` module to be used in place of any composed `setuptools` dep:

```
>>> import sys, pkg_resources
>>> pkg_resources.__file__
'/Users/kwilson/.pants.d/bin/pants.pex/1.2.0dev8-tw3/pants.pex/.bootstrap/pkg_resources.py'
```

to avoid this, we should either scrub the `.bootstrap` path from `sys.path` or move it to the end and reload:

```
>>> sys.path = sys.path[1:]
>>> reload(pkg_resources)
<module 'pkg_resources' from '/Users/kwilson/.pex/install/setuptools-5.4.1-py2.py3-none-any.whl.77dd06420042734134bc9f929de0433f5c64ec67/setuptools-5.4.1-py2.py3-none-any.whl/pkg_resources.pyc'>
>>> pkg_resources.__file__
'/Users/kwilson/.pex/install/setuptools-5.4.1-py2.py3-none-any.whl.77dd06420042734134bc9f929de0433f5c64ec67/setuptools-5.4.1-py2.py3-none-any.whl/pkg_resources.pyc'
```

**Comment by sixninetynine** [comment]
I vote to scrub it! I've definitely had scenarios where I needed to scrub it due to the baked in pkg_resources loading prior to any pex'd libraries, causing entry_points to not be discoverable except after `reload`, you may recall from your other project https://github.com/kwlzn/pyuwsgi_pex/pull/2

**Comment by jsirois** [comment]
As demonstrated by issues like #949 this has since been fixed. Pex has vendored its dependencies since 1.6.0 under the `pex.third_party` package prefix and Pex now also scrubs all pex modules prior to handing control over to application code.
