### ISSUE TITLE
Pex files include cp26 and cp27 at random when given a choice

### ISSUE THREAD

**Issue by mleonard87** [pantsbuild/pex#333]
I am build a pex containing flask app and having gunicorn as the entry point. This all works fine but when I run the resulting pex as an executable I get the following warning message:
```
797 WARNING py.warnings: /home/mike/.pex/install/pyzmq-15.2.0-cp26-none-
linux_x86_64.whl.d56060b30ef594bd1d9180bf886abcc1512e9ade/pyzmq-15.2.0-cp26-none-
linux_x86_64.whl/zmq/backend/cython/__init__.py:6: RuntimeWarning: compiletime
version 2.6 of module 'zmq.backend.cython._device' does not match runtime version 2.7
```

I built the pex whilst in a virtualenv using python 2.7 with the following command:
```
python pex credentials -o dist/my_first_pex.pex --repo /opt/wheels-cache --find-links 
/opt/wheels-cache --no-index -r requirements-pex.txt
```
The wheels cache contains both `cp26` and `cp27` versions of `pyzmq`.

I am finding the resulting pex has a mixture of cp26 and cp27 wheels and chooses seemingly randomly per library which is included. Is there a way to force pex to include wheels for the correct version? In my case the pex I am creating with both be built and run with python2.7.

Thanks, Mike.

**Comment by kwlzn** [comment]
@mleonard87 are you sure the python you're using at build-time is python2.7 (e.g. what does `python --version` say)?

fwiw, I don't seem to repro for a simple case:

```
[illuminati show]$ find wheels
wheels/
wheels/cffi-1.9.1-cp26-cp26m-macosx_10_10_intel.whl
wheels/cffi-1.9.1-cp27-cp27m-macosx_10_10_intel.whl
wheels/pycparser-2.17.tar.gz
[illuminati show]$ head -1 `which pex`
#!/Users/kwilson/Python/CPython-2.7.11/bin/python
[illuminati show]$ pex cffi --no-index -f ./wheels -o /tmp/throwaway.pex
[illuminati show]$ unzip -l /tmp/throwaway.pex |grep cffi | head -1
   320576  01-03-2017 10:32   .deps/cffi-1.9.1-cp27-cp27m-macosx_10_10_intel.whl/_cffi_backend.so
```

any ideas on a reliable repro?

**Comment by mleonard87** [comment]
Unfortunately I cannot repro this. I've cleared out my .pex directory and have been running again with no issues. We can close this. Thanks for your help.
