### ISSUE TITLE
pex pulls in pre-release versions of libraries

### ISSUE THREAD

**Issue by daveFNbuck** [pantsbuild/pex#346]
I recently had an issue where my production build stopped working because it picked up a pre-release version of protobuf. `pex protobuf` will pick up version `3.2.0rc2` right now, while a pip install will pick up `3.1.0.post1`. I didn't expect this to happen and there doesn't appear to be a way to change the behavior.

**Comment by daveFNbuck** [comment]
pip seems to be following [PEP 440](https://www.python.org/dev/peps/pep-0440/#version-scheme) and defining stable releases to exclude pre-releases (those including `a`, `b`, or `rc` in the version identifier) and developmental releases (those with `dev` followed by a number at the end).

**Comment by wickman** [comment]
I think this is a dupe of #28. y/n?

**Comment by daveFNbuck** [comment]
Yes, I missed that one in my search.
