### ISSUE TITLE
Bootstrapped PEX can't resolve dependencies within itself locally

### ISSUE THREAD

**Issue by scanlong** [pantsbuild/pex#349]
e.g. If I do `$ pex pex requests -c pex -o ~/bin/pex`

then `$ ~/bin/pex requests . -o test.pex -v` (same thing if i do -e or -c and give it an entrypoint)

PEX will try to resolve requests through PyPI instead of within the PEX itself. Is there a way to prevent this behavior or somewhere I can look to add this behavior? Or should i ask this elsewhere?

**Comment by kwlzn** [comment]
this isn't how pex works - the tool runtime will always attempt to resolve against an index or find-links repo/dir when its constructing a pex, full stop. if you want pex to resolve against a dir of local dists (sdists like .tar.gz or bdists like .egg or .whl), you could copy all of the dists you need into a local dir and pex a `-f /path/to/dir/of/dists --no-pypi`.

beyond that, it'd probably be helpful to elaborate your use case a bit more.

**Comment by scanlong** [comment]
thanks for your quick response!

basically trying to freeze the dependencies for the libraries we use for datascience (numpy and pandas) in a PEX locally, and then ideally use that PEX to build every binary that depends on them

should i just save those dependencies locally and point at them to replace the first step?

**Comment by sixninetynine** [comment]
@scanlong if I am understanding your use case, you basically want a pex that acts as a frozen virtualenv? If so, just make a pex with all the deps you want, say:

```
pex requests numpy pandas -o data_sci.pex
```

Then you can use that pex exactly as you would an interpreter, either invoking directly for an interactive shell, or running scripts with it:

```
$ ./data_sci.pex
Python 2.7.11 (default, Dec 23 2015, 18:01:50)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import requests, numpy, pandas

$ ./data_sci.pex some_script.py

```
