### ISSUE TITLE
4 space? style?

### ISSUE THREAD

**Issue by sixninetynine** [pantsbuild/pex#364]
Hey pex maintainers,

Curious what your opinions on 4 space indents are... I presume the style in this codebase is an extension of twitter's internal guidance? 

We (linkedin) switched over to 4 space (and mostly pep8) early last year and it's been great. The transition has been pretty easy too. Wondering if y'all are open to the idea of moving pex to 4 space indents and perhaps prescribing some additional style guidance for contribution?

If not, feel free to close.

**Comment by kwlzn** [comment]
aside from widespread use of 2-space indent within Twitter (which is largely carry over from the high number of ex-Googlers we've employed), pants' codebase also uses 2 space indent - and technically pex is a subproject of the pantsbuild org. so ultimately, in the OSS world this is an organizational choice at one level higher than pex.

in practice, 2 space indent proves to be quite useful in providing ample vertical space for deeply indented blocks which leads to less superficial line breaking/wrapping. so, IMHO pretty doubtful that we'd ever switch back to 4 space indent for pex or pants.

regarding a style guide - pants has a very lightweight style guide [here](http://www.pantsbuild.org/styleguide.html) which is probably about as opinionated as we'd want to get on the matter given the size of the codebase and contribution frequency. pex's style is largely a mix of PEP8 (w/ 2 space indent, 100-chars per line) + Google's styleguide + matching existing precedent. beyond that, we tend to focus on substance over style.
