### ISSUE TITLE
Resolving pre-release when explicitly requested

### ISSUE THREAD

**Issue by toddgardner** [pantsbuild/pex#372]
So upgrading to pants 1.3.0 dev releases, I ran into an issue with an whl we have as a pre-release, pex is more picky with these than pip at the moment:

```
$ ls wheelhouse/pydicom-1.0.0a1-py2-none-any.whl 
wheelhouse/pydicom-1.0.0a1-py2-none-any.whl
$ pip install pydicom==1.0.0a1 -f wheelhouse/ --no-index
Collecting pydicom==1.0.0a1
Installing collected packages: pydicom
Successfully installed pydicom-1.0.0a1
$ pex pydicom==1.0.0a1 -f wheelhouse/ --no-index
Could not satisfy all requirements for pydicom==1.0.0a1:
    pydicom==1.0.0a1
```

Looking through pep 440 and pip code, it looks like if any specifier in a set is inclusive and specifies a pre-release, then pre-releases should be accepted.

It seems like that could just be a check here: https://github.com/pantsbuild/pex/blob/d70f2c4e679770a586c765eaaa5ce6466bbc8879/pex/package.py#L82 if operator is inclusive and version is prerelease?

**Comment by kwlzn** [comment]
fixed in #374
