### ISSUE TITLE
Release pex 0.8.4

### ISSUE THREAD

**Issue by Yasumoto** [pantsbuild/pex#38]
Thanks to a nudge from @Moult, we should tag a new release and ship to PyPI.

**Comment by jsirois** [comment]
+1

If this RB makes it into the release too, we'll have a super perf-win filled update to gobble up: https://rbcommons.com/s/twitter/r/1685/

**Comment by Moult** [comment]
+1 (of course)

... would really appreciate if https://github.com/pantsbuild/pex/pull/39 was merged in before release as well, because it's a showstopper bug for me :)

**Comment by wickman** [comment]
I'll try to get this published within the next couple hours.  Thanks for all the PRs!

**Comment by jsirois** [comment]
Thanks Brian

**Comment by wickman** [comment]
This is now published.

**Comment by wickman** [comment]
Ugh I'm a friggin idiot.  I published the version on pypi (it's correct, don't worry) but screwed up and tagged 0.8.4 on github against the 0.8.3 version.  Will attempt to delete the github release.
