### ISSUE TITLE
feature request: [pex-binary] -m [package in pex] (allows pip-in-pex)

### ISSUE THREAD

**Issue by kurtbrose** [pantsbuild/pex#392]
It would be nice if PEX could support '-m {package}'.

There are a lot of packages that do [sys.executable, '-m', 'something-else'].  Currently there isn't really a way to embed these into a PEX.

Specifically, pip calls setuptools in this fashion.

pex can build a runnable version of itself right?  does the self-hosted pex also carry along a version of pip, or does it depend on the system having a pip version available?

I am working on a project that wants to self-embed its build tools as part of the published pex artifact.  That means pex + pip + virtualenv embedded into the pex.  It isn't blocked by `python -m`, just wanted to call out that having that support would make this kind of project a lot easier.

**Comment by kwlzn** [comment]
we can't support `-m` self-referentially in a built pex, because the pex may take it's own arguments that this would interfere with. however, this option could easily be plumbed in a built pex by the author as needed.

it's worth noting that pex does support this mode of execution today via environment variables - specifically, `PEX_MODULE` - which executes module execution (`some.mymodule`) as well as importable entrypoints (`some.module:main`) - and `PEX_SCRIPT` which executes console script entrypoints.

```
[omerta ~]$ pex pip -o /tmp/throwaway.pex
[omerta ~]$ /tmp/throwaway.pex
Python 2.7.10 (default, Dec 16 2015, 14:09:45)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>>
[omerta ~]$ PEX_SCRIPT=pip /tmp/throwaway.pex

Usage:
  pip <command> [options]

Commands:
  install                     Install packages.
...
[omerta ~]$ PEX_MODULE='pip' /tmp/throwaway.pex

Usage:
  pip <command> [options]

Commands:
  install                     Install packages.
...
[omerta ~]$ echo '{"test": 1}' | PEX_MODULE="json.tool" /tmp/throwaway.pex
{
    "test": 1
}
```

so, you could achieve this today by plumbing `-m` in your pex main or shim to re-exec itself with one of these environment variables defined to net this effect.

**Comment by kwlzn** [comment]
```
pex can build a runnable version of itself right? does the self-hosted pex also carry along a version of pip, or does it depend on the system having a pip version available?
```

yes:

```
[omerta ~]$ pex --version
pex 1.2.7
[omerta ~]$ pex pex -c pex -o /tmp/pex
[omerta ~]$ /tmp/pex --version
pex 1.2.7
```

and pex doesn't rely on pip at all, but you can easily include it (or pex itself) as a dependency in the pex and call it - see above for examples.

**Comment by kurtbrose** [comment]
Very specifically, `pip wheel` will re-exec `setup.py bdist_wheel` using `sys.executable`.  You get this kind of error:

```
Building wheels for collected packages: sky-metadata
  Running setup.py bdist_wheel for sky-metadata ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/bf/hk4tnscx7ps0k06gqgrb8g400000gn/T/pip-oddFVu-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/bf/hk4tnscx7ps0k06gqgrb8g400000gn/T/tmpztJmlFpip-wheel-:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
```

This just means you can't run `pip wheel` from within a PEX.  Our work-around is to instead embed virtualenv inside the pex executable, and set up a virtualenv from which to run `pip wheel`.  This has the side benefit of allowing pex library to be pip installed into this temporary virtualenv rather than being embedded, saving about 3MB off the size of the executable.

**Comment by kurtbrose** [comment]
When I have time I'll try your example with `bdist_wheel`
