### ISSUE TITLE
PEX wheel support fetches the wrong wheel variant (cp27m instead of cp27mu)

### ISSUE THREAD

**Issue by apollo13** [pantsbuild/pex#398]
When specifying the platform there does not seem to be a way to specify the abi tag. This results in 
```
 msgpack_python-0.4.7-cp27-cp27m-manylinux1_x86_64.whl
```
getting pulled in instead of
```
 msgpack_python-0.4.7-cp27-cp27mu-manylinux1_x86_64.whl
```
which uses UCS4 instead of UCS2 and is basically what every linux distribution uses (according  to https://github.com/pypa/manylinux)

**Comment by kwlzn** [comment]
this is a known issue for folks resolving directly against pypi, but it'd be good to provide a repro here to confirm this is fixed in the upcoming work.

**Comment by apollo13** [comment]
This can be used to repro:
```
pex msgpack-python==0.4.7 -o test.zip --platform=manylinux1_x86_64 --no-build --wheel
unzip -l test.zip|grep cp27mu
```

**Comment by kwlzn** [comment]
platform/impl/abi tags are now directly targetable as of pex 1.4.0:

```
[omerta ~]$ pex msgpack-python==0.4.7 -o /tmp/throwaway --platform=linux-x86_64-cp-27-mu --no-build
[omerta ~]$ unzip -l /tmp/throwaway | grep cp27mu | head -1
warning [/tmp/throwaway]:  25 extra bytes at beginning or within zipfile
  (attempting to process anyway)
     1385  05-15-2018 17:33   .deps/msgpack_python-0.4.7-cp27-cp27mu-manylinux1_x86_64.whl/msgpack/__init__.py
```

(also noting that manylinux support is intended to be implicit, so you needn't specify it exactly on the commandline - any linux platform will implicitly pickup manylinux wheels now)
