### ISSUE TITLE
FEATURE - Add ability to specify major version of python for PEX to run with

### ISSUE THREAD

**Issue by esazhin** [pantsbuild/pex#4]
When I have created a PEX it recorded the interpreter as python3.3. becasue that was the version we
had installed.
But we have recently installed python 3.4.1 and the question is that if the python 3.3 will get removed, then all PEX files built with py33 will break becasue of the "hardcoded" python interpreter value with minor version.

I thought if I'd use --python option and specify interperter as "python3" it would allow to use/run PEX with any python3 version that is present in the $PATH but it doesn't seem to be the case. 

Please add the support for major version of python specification (python3) that would effectively use first python3 found in the $PATH

**Comment by wickman** [comment]
This is now more or less possible using ``--python-shebang`` and/or the PEX_PYTHON environment variable.  The former allows you to specify an explicit shebang line (e.g. ``--python-shebang="/usr/bin/env python3"``) and the latter allows you to specify an explicit python e.g. PEX_PYTHON=python3.4 even if the pex file says something else.  Reopen if you think that this is insufficient.

**Comment by esazhin** [comment]
perfect!
