### ISSUE TITLE
update pex.readthedocs.io

### ISSUE THREAD

**Issue by nathanhruby** [pantsbuild/pex#428]
Hi Folks!

http://pex.readthedocs.io/en/latest/ seems to be from v1.0.3 circa 2014 and is missing a few details (like .pexrc support).  When you have a moment, could you update readthedocs to the latest version?

Thank you!

-n

**Comment by jsirois** [comment]
@wickman do you hold the keys to the https://pex.readthedocs.io project? If so can you add jsirois (https://readthedocs.org/profiles/jsirois/) to the admin?

**Comment by nathanhruby** [comment]
looks like this is fixed, thanks!
