### ISSUE TITLE
interpreter.py's _from_binary_external doesn't handle perm errs well.

### ISSUE THREAD

**Issue by engineerkatie** [pantsbuild/pex#445]
Python35 has been mis-installed on my dev system. Some of the packages are owned root, read only root. (This is a diff issue which I'll be emailing root about).

However, Pex's interpreter identifier throws a "permission denied" error trying to get versions of those packages at the point it imports "pkg_resources". Which causes it to decide the interpreter as a whole is unusable, causing my python>3.0 requirement to fail to be satisfied...

Should it perhaps not yield a valid interpreter but without the extras portion of the identification data?

**Comment by jsirois** [comment]
> (This is a diff issue which I'll be emailing root about).

Hah!


> Should it perhaps not yield a valid interpreter but without the extras portion of the identification data?

Perhaps, but its likely code downstream will fail. For example, `pkg_resources` is part of `setuptools`, and [pex tries to install setuptools](https://github.com/pantsbuild/pex/blob/master/pex/bin/pex.py#L520-L521) for the interpreter it's using and I suspect that step would then fail in your case.


It's not immediately clear to me how to teach pex to check for broken python distributions that are broken little-enough to be viable.

I'm going to mark this as answered but leave the issue open a bit to attach some cleanup PRs to - your prompt got me looking at some code where some dead bits stood out.

**Comment by engineerkatie** [comment]
> Hah!

Root did, in fact, email me back about ten minutes later have done a recursive chmod...

We have no idea why the package update didn't work properly.

> Perhaps, but its likely code downstream will fail.

Fair enough!
