### ISSUE TITLE
Confusing example in docs

### ISSUE THREAD

**Issue by pfmoore** [pantsbuild/pex#459]
The very first example in the "Building pex files" section in the documentation is: `pex pex requests -c pex -o ~/bin/pex`. There's little explanation of what it does, but I assumed it would build a copy of pex with requests "built in". So the following output confused me:

```
$ ~/bin/pex
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import requests
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ModuleNotFoundError: No module named 'requests'
```

I expected the import to work. I'm guessing that I've misunderstood what's happening here (this is a *very* quick initial attempt to work out what pex is about) but it would be worth having a clearer initial example.

Apologies if this isn't the right place to put something like this - is there a community mailing list or similar where I can ask beginner questions like this?

**Comment by jsirois** [comment]
One place to ask questions in is the Pantsbuild slack on the #pex channel. You can sign up here: https://pantsslack.herokuapp.com/

As far as the confusion, this is fundamentally down to the arguably confusing behavior of running pex with no arguments, which drops you into an isolated python environment scrubbed of any extra dependencies.

Your pex does in fact have requests included and you can see this in 2 ways:

1. Look inside the pex:

        $ unzip -l ~/bin/pex | grep requests
            49017  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests-2.18.4.dist-info/DESCRIPTION.rst
            50496  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests-2.18.4.dist-info/METADATA
             1904  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests-2.18.4.dist-info/RECORD
              110  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests-2.18.4.dist-info/WHEEL
             1638  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests-2.18.4.dist-info/metadata.json
                9  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests-2.18.4.dist-info/top_level.txt
             3507  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests/__init__.py
              436  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests/__version__.py
             1096  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests/_internal_utils.py
            20836  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests/adapters.py
             6237  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests/api.py
             9728  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests/auth.py
              453  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests/certs.py
             1595  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests/compat.py
            18208  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests/cookies.py
             3103  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests/exceptions.py
             3616  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests/help.py
              767  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests/hooks.py
            34003  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests/models.py
              542  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests/packages.py
            27546  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests/sessions.py
             3323  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests/status_codes.py
             3012  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests/structures.py
            27652  2018-04-26 10:24   .deps/requests-2.18.4-py2.py3-none-any.whl/requests/utils.py

2. Do what you thought you were doing by executing the pex with no arguments:

        $ PEX_INTERPRETER=1 ~/bin/pex 
        Python 3.6.5 (default, Apr 14 2018, 13:17:30) 
        [GCC 7.3.1 20180406] on linux
        Type "help", "copyright", "credits" or "license" for more information.
        (InteractiveConsole)
        >>> import requests
        >>> 
        ```
    This is explained a bit here:

        ```
        $ ~/bin/pex --help-variables | grep -A5 INTERPRETER
        PEX_INTERPRETER: Boolean

            Drop into a REPL instead of invoking the predefined entry point of
            this PEX. This can be useful for inspecting the PEX environment
            interactively.  It can also be used to treat the PEX file as an
            interpreter in order to execute other scripts in the context of
            the PEX file, e.g. "PEX_INTERPRETER=1 ./app.pex my_script.py".
            Equivalent to setting PEX_MODULE to empty. Default: false.

        PEX_MODULE: String

            Override the entry point into the PEX file.  Can either be a

**Comment by jsirois** [comment]
I'm going to close this as answered, but please re-open / speak-up if you have more questions on this.

**Comment by pfmoore** [comment]
Thanks, that's fine. Would it be worth me submitting a docs PR clarifying the behaviour?

**Comment by pfmoore** [comment]
I'm looking at creating a docs PR, but I'm actually a little confused. What is the benefit of including `requests` in the `pex` file created? As far as I can see, `pex` doesn't need requests, so this is of no benefit. Would it not be just as reasonable to say:

> you can use pex to bootstrap itself:
>
> ```
>     $ pex pex -c pex -o ~/bin/pex
> ```
> This command creates a pex file containing pex, using the console script
> named "pex", saving it in ~/bin/pex.  At this point, assuming ~/bin is on
> your $PATH, then you can use pex in or outside of any virtualenv.

Or is there a reason why you need to include requests in order for the pex file to work? I couldn't find one in my simple tests...
