### ISSUE TITLE
master, travis are silently broken

### ISSUE THREAD

**Issue by kwlzn** [pantsbuild/pex#461]
after some mysterious local failures that weren't reproducing in CI, I noticed that several of the recent travis runs have green test shards that actually have silently failing tests.

e.g. PR #316 in https://travis-ci.org/pantsbuild/pex/builds/368145168 the 3.6 shard in https://travis-ci.org/pantsbuild/pex/jobs/368145178 shows:

```
======== 16 failed, 170 passed, 12 skipped, 1 xfailed in 111.28 seconds ========
```

tox emits an error, but then there appear to be some missing commands at the end of the run which seem suspect:

```
ERROR: InvocationError for command '/home/travis/build/pantsbuild/pex/.tox/py36/bin/py.test' (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py36: commands failed
/home/travis/.travis/job_stages: line 95: uname: command not found
/home/travis/.travis/job_stages: line 105: date: command not found
/home/travis/.travis/job_stages: line 87: -: syntax error: operand expected (error token is "-")
cache.2
store build cache
Done. Your build exited with .
/home/travis/.travis/job_stages: line 163: pgrep: command not found
/home/travis/.travis/job_stages: line 163: grep: command not found
/home/travis/.travis/job_stages: line 164: awk: command not found
```

cc @CMLivingston @jsirois

**Comment by kwlzn** [comment]
looks like this started in https://github.com/pantsbuild/pex/pull/427 likely via the `.travis.yml` changes - @CMLivingston would you mind taking a look?

**Comment by CMLivingston** [comment]
Will do.
