### ISSUE TITLE
1.2.16 or 1.2.26 ?

### ISSUE THREAD

**Issue by benjaoming** [pantsbuild/pex#485]
This release is a bit confusing :)

On PyPi, it's called 1.2.26

![image](https://user-images.githubusercontent.com/374612/40122885-1ba28342-5925-11e8-85ee-f2d4ba3a6a90.png)

**Comment by kwlzn** [comment]
hmm, everything else there looks correct to me (including the inner versions in the release) other than the version in the release notes. I've updated that here: https://github.com/pantsbuild/pex/releases/tag/v1.2.16

but - I also don't see a PyPi `1.2.26` version either? can you link?

https://pypi.org/project/pex/1.2.16/#description <-- this should map to that release.
https://pypi.org/project/pex/1.2.26/#description <-- this gives me a "Page not Found"

**Comment by kwlzn** [comment]
but also: I'd highly recommend just using the latest release (1.4.0) vs targeting something in the 1.2.x series if possible.

**Comment by kwlzn** [comment]
optimistically closing this one based on the version edit, but let me know if you still see an issue.

**Comment by benjaoming** [comment]
> but also: I'd highly recommend just using the latest release (1.4.0) vs targeting something in the 1.2.x series if possible.

Oh sorry, I mis-remembered! It is indeed 1.2.16 that's on PyPi:

```
pip install pex\<1.3
Collecting pex<1.3
  Using cached https://files.pythonhosted.org/packages/da/53/06d6b8ade6d8180b1c7723d090a654c13e49311aaa43c17308dea5e2bb03/pex-1.2.16-py2.py3-none-any.whl
```

**Comment by benjaoming** [comment]
Thanks for clarifying the release notes!
