### ISSUE TITLE
pypy shards in travisCI can fail with 'too many open files' errors

### ISSUE THREAD

**Issue by kwlzn** [pantsbuild/pex#497]
this needs more investigation, but intermittently only the "pypy" shards in travis will fail arbitrarily with "too many open files" errors.

we had previously pinned to the travis `precise` image because of this, but because of deprecation prompting for that image we'd jumped forward here: https://github.com/pantsbuild/pex/pull/476

an initial pass may want to try some simple `ulimit` tuning.

**Comment by kwlzn** [comment]
filed https://github.com/travis-ci/travis-ci/issues/9706 for some upstream help.

**Comment by kwlzn** [comment]
topical relief achieved here: https://github.com/pantsbuild/pex/pull/513

at a cost of ~4x test execution time (~2m -> ~8m) - good enough to tide us over for now.

**Comment by jsirois** [comment]
I found the bug and it is in pypy. I need to work around it for other reasons, and it turns out this fixes our pypy shard which can now run normally. Re-opening to linkup the fix PR and add bug links.

**Comment by jsirois** [comment]
The pypy issue: https://bitbucket.org/pypy/pypy/issues/1686/issue-with-our-zipimporter-module
