### ISSUE TITLE
start using pep440 identifiers.

### ISSUE THREAD

**Issue by wickman** [pantsbuild/pex#50]
specifically switch to using dstufft's [packaging](https://pypi.python.org/pypi/packaging) package to manage version numbers instead of pkg_resources.Requirement.

**Comment by wickman** [comment]
Related to #55.  Newer setuptools use packaging under the covers, so we might just mark this as wontfix.

**Comment by kwlzn** [comment]
this is indeed implicitly handled by newer setuptools. closing.
