### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by JakeTheDev** [pantsbuild/pex#506]
Hi there. We're working on using pex to build up happy fat little binaries of some internal web services. Often, these web services rely on numpy/scipy/keras, and I've gotten pex to work with a pure 'numpy' dependency in the setup.py - but it's blowing up on scipy/keras install with the title error. At several cumulative hours into researching this and digging through the pex issues log for information, I figure it's time to ask

We're using pex directly, as we already have a full build system in place, and pants would be waaay overkill here. We're relying entirely on setup.py dependency versioning, as we're doing our best to avoid a need for virtual environments, it works nicely with pex, and it gives developers a single point of reference for all deps/requirements so it's easier to work with. 

My setup is real simple, it just has one local package, one local script as an entry point, and the following install_requires, which is basically gunicorn and the numpy stuff in addition to the result of pip install flask followed by pip freeze:

```
    install_requires=[
      'numpy',
      'keras',
      'click==6.7',
      'Flask==1.0.2',
      'gunicorn==19.8.1',
      'itsdangerous==0.24',
      'Jinja2==2.10',
      'MarkupSafe==1.0',
      'Werkzeug==0.14.1',
    ],
```

Note: Keras depends on scipy depends on numpy, but you can swap keras with scipy in the above block and you get the same result either way. 

I've been testing things a step at a time, and I've got it happily churning out pex files for flask/gunicorn apps with a direct numpy requirement. But it seems to lose its mind when numpy is relied on by a dependency, even if I specifically declare numpy in the install_requires before the problem dependency.

I'm running pex 1.3.2 as a self-bootstrapped binary, and all this is happening in a python3.6 venv that only has pip, setuptools, wheel, and six installed. Command is happening in the setup.py directory:

pex . -v -c runserver.py -o app.pex --python=python3.6 --platform=linux_x86_64 --not-zip-safe

Any help would be appreciated. Full error below:

```
pex: Building pex :: Resolving distributions :: Packaging scipy    
**** Failed to install scipy-1.1.0 (caused by: NonZeroExit("received exit code 1 during execution of 
`['/home/jakethedev/.virtualenvs/p36/bin/python3.6', '-', 'bdist_wheel', '--dist-dir=/tmp/tmpcog0upnb']` while trying to execute `['/home/jakethedev/.virtualenvs/p36/bin/python3.6', '-', 'bdist_wheel', '--dist-dir=/tmp/tmpcog0upnb']`",)
):
stdout:

stderr:
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "setup.py", line 474, in <module>
    setup_package()
  File "setup.py", line 450, in setup_package
    from numpy.distutils.core import setup
ModuleNotFoundError: No module named 'numpy'
```

**Comment by kwlzn** [comment]
this particular error is the result of a failure of a `python3.6 setup.py bdist_wheel` against an scipy-1.1.0 sdist:

```
[omerta scipy-1.1.0]$ python3.6 setup.py bdist_wheel
Traceback (most recent call last):
  File "setup.py", line 474, in <module>
    setup_package()
  File "setup.py", line 450, in setup_package
    from numpy.distutils.core import setup
ModuleNotFoundError: No module named 'numpy'
```

pex expects this to "just work", so the fact that it doesn't is probably either due to 1) a bug in scipy's setup.py logic or 2) an implicit assumption by scipy that it's always being installed via `pip`.

however - given that `scipy` does provide manylinux wheels on pypi, if you bump to pex `1.4.3` (which now supports manylinux) you should be able to directly consume those wheels vs falling back to this build step - which should be both faster and cleaner.

**Comment by JakeTheDev** [comment]
Thank you sooooo much for the lightning response, I felt like this was going to drive me nuts haha

Works like a charm!

**Comment by kwlzn** [comment]
no problem! glad that worked for you.
