### ISSUE TITLE
PyPI tar.gz is missing some files

### ISSUE THREAD

**Issue by warsaw** [pantsbuild/pex#51]
The PyPI tar.gz is missing some files which are useful for downstream packagers (e.g. Debian).

* The entire docs/ directory (.md should be .rst, etc.)
* LICENSE
* rbt (may or may not be useful)
* scripts/
* tests/
* tox.ini

There might be others, but that's as far as I've gotten so far.  Probably just need an updated MANIFEST.in and I'll add PR if I can get it working.

**Comment by wickman** [comment]
Fixed by #52.
