### ISSUE TITLE
Parameters for PEXBuilder constructor not described on RTD 

### ISSUE THREAD

**Issue by altendky** [pantsbuild/pex#514]
https://pex.readthedocs.io/en/v1.0.3/api/index.html#module-pex.pex_builder

![image](https://user-images.githubusercontent.com/543719/41192768-df873a06-6bd0-11e8-96da-696c118572f6.png)

I would expect the `path`, `interpreter`, `chroot`, etc parameters to the `PEXBuilder` constructor to be described in the docs.  This may be a general issue with the docs rather than specific to `PEXBuilder`, I have not reviewed other classes.

**Comment by stuhood** [comment]
`1.0.3` is a pretty old version of pex. To see the docs for the latest version, use: http://pex.readthedocs.io/en/stable/api/index.html#module-pex.pex_builder
