### ISSUE TITLE
non-trivial pex invocation overhead

### ISSUE THREAD

**Issue by wisechengyi** [pantsbuild/pex#549]
```
# invoke zipped pex
$ for i in `seq 1 5` ; do time /Users/me/.cache/pants/pex/bin//pants.pex/1.10.0rc0-ba2ea292/pants.pex -V &> /dev/null; done

real	0m4.054s
user	0m3.038s
sys	0m0.842s

real	0m3.929s
user	0m2.997s
sys	0m0.795s

real	0m4.052s
user	0m3.066s
sys	0m0.849s

real	0m3.913s
user	0m2.994s
sys	0m0.788s

real	0m3.866s
user	0m2.896s
sys	0m0.761s

# extract it to a dir
$ unzip -d extracted_pex  /Users/me/.cache/pants/pex/bin//pants.pex/1.10.0rc0-ba2ea292/pants.pex

# invoke the extracted dir
$ for i in `seq 1 5` ; do time /opt/ee/python/2.7/bin/python2.7 extracted_pex -V &> /dev/null; done

real	0m2.844s
user	0m2.043s
sys	0m0.706s

real	0m2.865s
user	0m2.049s
sys	0m0.724s

real	0m2.968s
user	0m2.113s
sys	0m0.735s

real	0m2.946s
user	0m2.123s
sys	0m0.730s

real	0m2.979s
user	0m2.125s
sys	0m0.747s
```

**Comment by jsirois** [comment]
This is well and long (>5 years?) known. Can you flesh out a bit more what you expect? IE: Are you satisfied with the extracted execution time or not?
1. If you are creating not zip safe pexes (even if they actually are zip safe), can leverage the local pex cache for 1-time unzip such that repeated invocations are at the unzipped speed.
2. If not, we could narrow this issue to trying to provide measurements / solutions for pex pythonpath setup time - which is surely the majority of the remaining time after unzip.

**Comment by wisechengyi** [comment]
Would be helpful if you could clarify the time difference here is
a) just the unzip portion, or 
b) unzip + pthonpath setup
?

**Comment by wisechengyi** [comment]
Agreed that a more detailed investigation is needed. Regarding the known part, if there wasn't an old ticket, we can use this as a placeholder if that's okay.

**Comment by jsirois** [comment]
Its such an old problem - its really by design, pex fundamentally being a zipped virtualenv - that there is no written down issue I can find (not in twitter/commons or pantsbuild/pex). This is why I'm gunning for a bit more clarity in the issue; ie: It's a given pexes have unzipping overhead, so what do you hope to do about it?

**Comment by wisechengyi** [comment]
Like you mentioned earlier, potentially we may leverage some caching to get around the unzipping part (optionally behind a flag or env var). For example: 
1. When running `./pants.pex`, it checks for its own fingerprint, call it`<SHA>`
2. Unzip it to or reuse `~/.cache/pex/<SHA>`
3. Exec against `~/.cache/pex/<SHA>`

**Comment by jsirois** [comment]
This is already supported.

Fresh (The custom ~/.pex dir here - /tmp/test-existing-functionality DNE):
```
$ time PEX_FORCE_LOCAL=True PEX_ROOT=/tmp/test-existing-functionality /tmp/pants_local_binary.pex 
No goals specified.
Use `pants goals` to list goals.
Use `pants help` to get help.

real	0m2.400s
user	0m1.964s
sys	0m0.205s
```

Typical subsequent:
```
$ time PEX_FORCE_LOCAL=True PEX_ROOT=/tmp/test-existing-functionality /tmp/pants_local_binary.pex 
No goals specified.
Use `pants goals` to list goals.
Use `pants help` to get help.

real	0m1.262s
user	0m0.919s
sys	0m0.074s
```

And:

**Comment by jsirois** [comment]
To be clear, `PEX_FORCE_LOCAL` maps to `zip_safe` and can be an option embedded in the pex at build time so that the env var is not needed. Likewise, when leaving out the `PEX_ROOT` and env var, a pex root of `~/.pex` is automatically used.

**Comment by jsirois** [comment]
I'm going to mark this as answered. FWICT you were probably just unaware of these features. Feel free to re-open if you were looking for more here.

**Comment by wisechengyi** [comment]
Hmm how come I am unable to observe the effect? I can see `PEX_ROOT` is being created tho.
```
[tw-mbp-yic source (master)]$ for i in `seq 1 5` ; do time PEX_FORCE_LOCAL=True PEX_ROOT=/tmp/123 ~/.cache/pants/pex/bin//pants.pex/1.10.0rc0-ba2ea292/pants.pex -V &> /dev/null; done

real	0m3.886s
user	0m2.927s
sys	0m0.793s

real	0m3.845s
user	0m2.870s
sys	0m0.793s

real	0m4.177s
user	0m3.138s
sys	0m0.840s

real	0m4.203s
user	0m3.133s
sys	0m0.831s

real	0m3.915s
user	0m2.933s
sys	0m0.780s
[tw-mbp-yic source (master)]$ for i in `seq 1 5` ; do time ~/.cache/pants/pex/bin//pants.pex/1.10.0rc0-ba2ea292/pants.pex -V &> /dev/null; done

real	0m3.895s
user	0m2.897s
sys	0m0.794s

real	0m3.785s
user	0m2.807s
sys	0m0.782s

real	0m3.800s
user	0m2.904s
sys	0m0.781s

real	0m3.737s
user	0m2.869s
sys	0m0.784s

real	0m3.892s
user	0m3.011s
sys	0m0.786s
```

**Comment by wisechengyi** [comment]
Ah I see. The effect does show up. The original stats were obtained basically with this feature enabled already, which means there is still 1 sec head room we may be able to eliminate. Happy to dive in at a later time.

```
# PEX_ROOT enabled
$ for i in `seq 1 5` ; do time PEX_FORCE_LOCAL=True PEX_ROOT=/tmp/123 ~/.cache/pants/pex/bin//pants.pex/1.10.0rc0-ba2ea292/pants.pex -V &> /dev/null; done


real	0m7.784s
user	0m5.469s
sys	0m1.977s

real	0m3.888s
user	0m2.899s
sys	0m0.780s

real	0m3.901s
user	0m2.931s
sys	0m0.772s

real	0m3.948s
user	0m2.948s
sys	0m0.790s

real	0m3.991s
user	0m2.990s
sys	0m0.792s

# run on extracted dir
$ for i in `seq 1 5` ; do time /opt/ee/python/2.7/bin/python2.7 extracted_pex -V &> /dev/null; done

real	0m3.543s
user	0m2.170s
sys	0m1.063s

real	0m2.937s
user	0m2.114s
sys	0m0.731s

real	0m2.995s
user	0m2.129s
sys	0m0.743s

real	0m2.950s
user	0m2.119s
sys	0m0.730s

real	0m2.901s
user	0m2.087s
sys	0m0.713s
```

**Comment by sixninetynine** [comment]
It should be noted that unzipping is not the only overhead - you may be running into pkg_resources' now infamous Issue 510 https://github.com/pypa/setuptools/issues/510

**Comment by wisechengyi** [comment]
wow the overhead isn't as bad as seconds, but still pretty bad.
```
[tw-mbp-yic pants (6430)]$ time python -c 'import setuptools'

real	0m0.330s
user	0m0.255s
sys	0m0.067s
[tw-mbp-yic pants (6430)]$ time python -c 'import pkg_resources'

real	0m0.295s
user	0m0.229s
sys	0m0.059s
```
