### ISSUE TITLE
[Errno 13] Permission denied when executing with bdist_pex

### ISSUE THREAD

**Issue by fhoering** [pantsbuild/pex#570]
It seems that [this review](https://github.com/jsirois/pex/commit/8bba41f39198215ea1378ab5c325dde7deaba358#diff-4895aa16756686554f1906f607a1296e) released in version 1.4.6 has introduced a regression when executing pex with the bdist_pex target

```python setup.py bdist_pex
running bdist_pex
Writing environment pex into dist/test-0.1.pex
error: [Errno 13] Permission denied: '/tmp/tmpaumuj9wb/.deps/tensorflow-1.10.1-cp36-cp36m-manylinux1_x86_64.whl/tensorflow/libtensorflow_framework.so'
```

The package that fails is tensorflow.
Minimal setup.py:
```
#!/usr/bin/env python3

import setuptools
import os

setuptools.setup(
    name='test',
    version='0.1',
    install_requires=["tensorflow==1.10.1"],
    packages=setuptools.find_packages())
```

It works when just calling the command line tool pex:
`pex tensorflow==1.10.1`

Can you have a look ?

**Comment by jsirois** [comment]
Hrm. Will do.
