### ISSUE TITLE
Bundle python inside pex

### ISSUE THREAD

**Issue by HerrSpace** [pantsbuild/pex#601]
Since your readme states `pex is a library for generating .pex (Python EXecutable) files which are executable Python environments in the spirit of virtualenvs.` I expected it to also bundle the python bin itself inside the pex bundle, like virtualenv does. This doesn't seem to be the case though. Did I just miss some flag or is this currently not possible?

This feature would allow easily benefiting from new python features w/o having to deal with the mess of having multiple global python installations or waiting for a distro upgrade.

**Comment by jsirois** [comment]
@HerrSpace although I agree this would be an amazing feature it is by no means easy to support.

Unless there has been a major development I don't know about - virtualenv does not bundle python, it uses an existing python installed on the system to create a link/copy farm inside the venv.

For what it's worth, the easiest way I know of moving beyond global python installs in `pyenv`. We leverage this in both Panst and Pex in Travis CI and in unit tests: https://github.com/pyenv/pyenv

**Comment by HerrSpace** [comment]
Thanks for clarifying! After reading up on PEP 441 I see where you are coming from. While it probably would be possible to build an executable, bundling python with python libs, it wouldn't have anything to do with PEP441 anymore. :/
