### ISSUE TITLE
Come up with a plan for installing wheels in pexes post wheel 0.31.1

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#603]
After 0.31.1 the `wheel.WheelFile.install` API we use here is gone:
https://github.com/pantsbuild/pex/blob/ac7aab86e90cfdff43e0b05c6a3500a6cb354547/pex/pex_builder.py#L279-L291

See https://github.com/pypa/wheel/issues/262

**Comment by jsirois** [comment]
The `WheelFile.install` code is not super involved even though it looks extensive at 1st glance:
https://github.com/pypa/wheel/blob/3dc261abc98a5e43bc7fcf5783d080aaf8f9f0cf/wheel/install.py#L275-L397

The answer may be to just buckle down and implement install ourselves.

**Comment by kwlzn** [comment]
> The answer may be to just buckle down and implement install ourselves.

makes sense to me for now until pypa/wheel#262 manifests - or perhaps we could both fork and attempt to upstream that impl as contrib solution for pypa/wheel#262.

**Comment by jsirois** [comment]
This was solved in Pex 2.0.0 by vendoring Pip and using it to perform installs in #788
