### ISSUE TITLE
PEX is not packaging its subpackages and its Dependencies

### ISSUE THREAD

**Issue by itsmesrds** [pantsbuild/pex#609]
i have structured folder that contains 

->tree
--->package1
---------->package2
---------->__init__.py
---------->main.py
--->setup.py
--->requirements.txt
--->package1.wheel

i want to build pex file for this structure.when i use command in tree folder "pex --python=python3 -rrequirements.txt  package1 -e package.main -o samplepkg.pex"

When i try run the samplepkg.pex ...Error:package2 not found .....when i run the pex file deactivating the environment ...dependencies module not found

Is this Tox is for packaging dependencies module and subpackages rite..?

**Comment by jsirois** [comment]
It would be helpful if you gave the full output of the error and make sure the directory tree you describe is accurate. Right now the command line you gave: `pex --python=python3 -rrequirements.txt package1 -e package.main -o samplepkg.pex` does not match the directory structure you listed, which has `package1/main.py` which does not match your command line entrypoint `-e package.main`.

**Comment by jsirois** [comment]
One more bit of debug advice: pex should package exactly what setup.py packages. PEX basically just runs `python setup.py sdist` on the setup.py you point to.

**Comment by itsmesrds** [comment]
Thanks for debugging advice. it is rectified.
But pex is using cache to create pex file.even though i have used "pip3 wheel -w .  ." and if i delete the wheel file still we are able to generate the pex..?

If i change any command in setup.py file and iam building a new wheel ....still it is using OLDER cache ...

**Comment by jsirois** [comment]
> If i change any command in setup.py file and iam building a new wheel ....still it is using OLDER cache ...

That's a bug, but its pretty far afield of the initial issue report here. I'm going to close this issue as answered and let #620 stand in for this narrower issue.
