### ISSUE TITLE
Resolve seems to be inconsistent in python 3.4

### ISSUE THREAD

**Issue by OniOni** [pantsbuild/pex#611]
While looking at pants python 3 tests and trying to fix failures, we noticed that resolve was different in python 3.4 vs. python 2.7. 

The [test](https://github.com/pantsbuild/pants/blob/d24cfe2257a88b80c2938cc212dcfcc8a329d970/tests/python/pants_test/backend/python/tasks/test_resolve_requirements.py#L56) expects the resolve to find the `macosx_10_10_x86_64` wheel for cffi. We have seen failures with python 3.4, where resolver grabs the `macosx_10_6_intel` wheel. 

The result is not incorrect, but unexpected. It is also not stable, this test does not fail 100% of the time.

**Comment by jsirois** [comment]
For easiest repro, the failing test in pants unstably resolves either `cffi-1.9.1-cp34-cp34m-macosx_10_10_x86_64.whl` or `cffi-1.9.1-cp34-cp34m-macosx_10_6_intel.whl` (https://pypi.org/project/cffi/1.9.1/#files) on OSX for platform `v_10_10_x86_64` when running under python 3.4 on OSX in travis-ci.
