### ISSUE TITLE
Pex cannot correctly resolve between multiple transitive dependencies

### ISSUE THREAD

**Issue by tglstory** [pantsbuild/pex#614]
Reproduction:
`pex apache-airflow==1.10.0 --interpreter-constraint='CPython<3.7'`
Pex version:
pex 1.5.1

Problem: 
Above command gives output of 
```
Could not satisfy all requirements for flask-login==0.2.11:
    flask-login==0.2.11(from: apache-airflow==1.10.0), Flask-Login<0.5,>=0.3(from: apache-airflow==1.10.0->flask-appbuilder<2.0.0,>=1.11.1)
```

Airflow 1.10.0's setup.py denotes flask-login of 0.2.11. https://github.com/apache/incubator-airflow/blob/1.10.0/setup.py#L280

However, it also depends on flask-appbuilder with a constraint of `<2.0.0,>=1.11.1`.
Looking at two different versions of flask-appbuilder:
https://github.com/dpgaspar/Flask-AppBuilder/blob/v1.11.1/setup.py#L41 vs https://github.com/dpgaspar/Flask-AppBuilder/blob/v1.12.1/setup.py#L42

1.11.1 and 1.12.1 both meet the requirement of `<2.0.0,>=1.11.1` but they require incompatible versions of `flask-login`. Pex should be able to resolve to the earlier version and pick up `flask-login` 0.2.11.

**Comment by jsirois** [comment]
Noting that the workaround is to specify the correct solution for Flask-AppBuilder manually:
`SLUGIFY_USES_TEXT_UNIDECODE=yes pex --python=python2 'apache-airflow==1.10.0; python_version < "3.7"' Flask-AppBuilder==1.11.1`.
