### ISSUE TITLE
Feature Request: Add support for pyproject.toml files generated with poetry

### ISSUE THREAD

**Issue by ghost** [pantsbuild/pex#647]
The toml file generated through poetry provides a lot of the information that pex could need, including the dependencies and possible entrypoints. It would be handy if there was a flag in pex that told it to parse and use the toml file inside the archive

**Comment by jsirois** [comment]
To be clear, parsing pyproject.toml would only be in-effect for distributions only available in sdist form. Today pex assumes a distutils-based build and executes `python setup.py bdist_wheel` to both build a distribution for the pex as well as read (from the whl metadata) the list of further requirements to resolve. As such, I think support for https://www.python.org/dev/peps/pep-0518 would not come in the form of parsing pyproject.toml for anything more than the build tool to invoke for resolved sidsts / local projects. Does this ammendment to your feature request sound sensible?

**Comment by ManchurianSector** [comment]
Yes, that would make sense. Thank you.

**Comment by jsirois** [comment]
I've filed #660 to take the place of this issue with the more general feature agreed on above as the target.
