### ISSUE TITLE
If an `--interpreter-constraint` is set, it should always be honored.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#656]
Right now these are only consulted when PEX_PYTHON or PEX_PYTHON_PATH are set:
https://github.com/pantsbuild/pex/blob/a16f0ecb21ce3526f7d243778507d68219c3a91c/pex/pex_bootstrapper.py#L141-L150

There is no reason for the constraints to not always apply.

**Comment by blorente** [comment]
Took a stab at it in #668, where I have written some questions.
