### ISSUE TITLE
Make `run_pex_command` honor the `env` parameter

### ISSUE THREAD

**Issue by blorente** [pantsbuild/pex#669]
In pex, `ENV` is a singleton (of type `Variables`) that contains parsed environment variables.  [`run_pex_command`](https://github.com/pantsbuild/pex/blob/edc636ce6a004fa1bfc762d74f01c9fd3a862429/pex/testing.py#L244) is a helper function used in integration testing to simulate pex runs, and it has an `env` parameter that should override the environment variables. Currently, that parameter only overrides the env vars set by the calling process (in `os.environ`), and not the global `ENV`.

The task is to modify `run_pex_command` so that it uses `Variables::patch` to patch `ENV` with the value of the passed `env` param.

**Comment by jsirois** [comment]
I'm taking a simpler tack here - PR shortly.
