### ISSUE TITLE
Package jars (Scala/Java)

### ISSUE THREAD

**Issue by archenroot** [pantsbuild/pex#728]
So usually one need with pyspark also jars to submit with, is it possible with PAX?

**Comment by jsirois** [comment]
It is not possible. Currently, PEX ensures a PYTHONPATH that includes `setuptools` and `wheel` and invokes `python setup.py bdist_wheel` to build sdists like [pyspark](https://pypi.org/project/pyspark/#files). Looking at the `setup.py` for `pyspark`, it is not self-contained, requiring the user to have pre-built the spark distribution:
https://github.com/apache/spark/blob/c6a45e6f67abc99d1953d915b96e65a3e2148cf1/python/setup.py#L42-L55

Until the `pyspark` setup.py` / sdist build process is converted to be self contained PEX will not be able to build a wheel from its sdist unless the `pyspark` pre-build requirements have been met on the machine you
re running PEX on. The easiest way to work around this is to:
1. Pre-build a pyspark wheel for each platform you care about (say linux and osx).
2. Point pex at the pre-built wheels from 1 via `--find-links=/path/to/directory/containing/prebuilt/wheels`
