### ISSUE TITLE
Pex fails with tensorflow==2.0.0rc0  (probably because of manylinux2010)

### ISSUE THREAD

**Issue by zachmoshe** [pantsbuild/pex#763]
```
<<start in a new virtualenv>>
pip install -U pip
# got me pip-19.2.3
pip install pex
# got me pex-1.6.10
pip install tensorflow==2.0.0rc0

pip freeze
# shows:
# absl-py==0.8.0
# astor==0.8.0
# gast==0.2.2
# google-pasta==0.1.7
# grpcio==1.23.0
# h5py==2.9.0
# Keras-Applications==1.0.8
# Keras-Preprocessing==1.1.0
# Markdown==3.1.1
# numpy==1.17.1
# opt-einsum==3.0.1
# pex==1.6.10
# protobuf==3.9.1
# six==1.12.0
# tb-nightly==1.15.0a20190806
# tensorflow==2.0.0rc0
# termcolor==1.1.0
# tf-estimator-nightly==1.14.0.dev2019080601
# Werkzeug==0.15.5
# wrapt==1.11.2

pex -r <(pip freeze) -o tmp.pex
# fails on:
# Could not satisfy all requirements for tensorflow==2.0.0rc0:
#    tensorflow==2.0.0rc0
```

This only happens when I try `tensorflow==2.0.0rc0`, for example `tensorflow-2.0.0-b1` works fine. It also doesn't happen on macos.
I've noticed that the `-b1` version detects the distribution as `manylinux1` while `rc0` calls it `manylinux2010` - could that be the difference? 

Any solution or a workaround?

Thanks!

**Comment by dcherniv** [comment]
@zachmoshe the only workaround is to repackage tensorflow as manylinux1.

**Comment by zachmoshe** [comment]
Thanks @fhoering, #778 helped me! I see it's still open, so I assume you're planning some more long-term support.

For future readers: I installed pex directly from git (got version 1.6.12 rather than 1.6.10 from apt-get), and it solved the problem.
