### ISSUE TITLE
Pex should support some form of verifiably reproducible resolve.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#772]
Supporting requirements files with hashes would help #429, but even then the results of indirect dependencies are not pinned and could vary if the requirements presented do not form a closure. Being able to inform Pex that the requirements presented are a closure and that it should do no more than fetch distributions at most but not transitively attempt to resolve / fetch their dependencies, etc would help fill out a full solution. This would allow a lock file to be presented and used to guarantee a reprodcible resolve or fail fast.

**Comment by benjyw** [comment]
Mostly solved by https://github.com/pantsbuild/pex/pull/775

That change allows us to install a list of URLs, provided as positional args, with no transitive resolution. 

We may still want an option to provide that URL list from a file, but that can happen in a followup.

**Comment by benjyw** [comment]
Closed in https://github.com/pantsbuild/pex/pull/775

That change allows us to install a list of URLs with no transitive resolution.
