### ISSUE TITLE
`pex -r <(pip freeze)` syntax stopped working in 2.0.0

### ISSUE THREAD

**Issue by zachmoshe** [pantsbuild/pex#793]
So far I was using pex with a temporary requirements file like this: 
`pex -r <(pip freeze)`  and it worked nicely.

After updating to 2.0, I started getting this: 
`ERROR: Could not open requirements file: [Errno 9] Bad file descriptor: '/dev/fd/63'`

I'm on MacOS, with pex upgraded to the latest (2.0.0), python 3.6.5 and pip 19.3.1.

If I try on Unix (Ubuntu 16.04), python 3.6.5, pex 2.0.0, pip 19.3.1, I get a slightly different message:
`ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/dev/fd/63'`

It works normally if I save the `pip freeze` output to a file and pass the filename as the argument.

Was anything changed in how pex parses arguments or opens the requirements file?
Is the (convenient) old syntax still supported?

**Comment by jsirois** [comment]
This one is tricky to fix. PEX needs to read requirement files before handing them off to pip, and for process substitution psuedo-files, this closes the fd leaving pip without a valid handle. Can you instead just `pex $(pip freeze)`? Less typing and works with all versions of PEX.

**Comment by zachmoshe** [comment]
makes sense. thanks!

**Comment by adeandrade** [comment]
The non-working approach is still in the docs.

**Comment by jsirois** [comment]
@adeandrade do you mean here?: https://github.com/pantsbuild/pex/blob/master/README.rst#simple-examples
If so would you be willing to sping up a PR?
