### ISSUE TITLE
Slow builds in 2.0 - how does --python interact with --platform?

### ISSUE THREAD

**Issue by AlexHill** [pantsbuild/pex#811]
I want to build a pex that supports Linux armv7l and x86_64, on Python versions 3.5 through 3.7.

Before pex 2.0, I used

`--platform linux_armv7l --platform linux_x86_64 --python python3.5 --python python3.6 --python python3.7 --python-shebang "/usr/bin/env python3"`

And that produced a pex file meeting those requirements in about ten seconds.

As of 2.0 I'm not sure what I need to do. pex seems to resolve requirements for every combination of platform and python, so if I specify all six relevant `--platform` options (`--platform linux_armv7l-cp-35-m`, `--platform linux_x86_64-cp-36-m`, etc) plus all three `--python` options it takes **200s**.

For my use case I can simplify and specify just `--platform any-py-<35/36/37>-none` and the `--python`s. That takes **90s**.

Ultimately the dependencies are in this case resolved to py3-none-any wheels, so I figure I can probably get away with specifying `--platform any-py-35-none` and the `--python`s. That takes **60s**.

If I omit `--python` entirely with the single `--platform` arg, it takes about **15s** - close to the pre-2.0 time. For every `--python` I add, including the default interpreter, it adds another ~15s.

In all these cases the actual resolved and bundled dependencies are identical. What effect does `--python` actually have on the pex over and above the platform specifier? Is there anything I can do to get the build time down while ensuring that I'm producing a file that will work where it needs to?

**Comment by jsirois** [comment]
Could you give a bit more concrete example? Preferrably one we can share in whittling away the perf difference? For example, platforms like `--platform linux_armv7l` and `--platform linux_x86_64` are no longer accepted. Any `--platform` supplied must be exact:
```
$ ./pex-2.0.2.pex --platform linux_armv7l
Usage: pex-2.0.2.pex [-o OUTPUT.PEX] [options] [-- arg1 arg2 ...]

pex-2.0.2.pex builds a PEX (Python Executable) file based on the given specifications: sources, requirements, their dependencies and other options.

pex-2.0.2.pex: error: The --platform option is invalid:
Not a valid platform specifier: linux_armv7l

Platform strings must be in one of two forms:
1. Canonical: <platform>-<python impl abbr>-<python version>-<abi>
2. Abbreviated: <platform>-<python impl abbr>-<python version>-<abbr abi>

Given a canonical platform string for CPython 3.7.5 running on 64 bit linux of:
  linux-x86_64-cp-37-cp37m

Where the fields above are:
+ <platform>: linux-x86_64 
+ <python impl abbr>: cp
+ <python version>: 37
+ <abi>: cp37m

The abbreviated platform string is:
  linux-x86_64-cp-37-m

These fields stem from wheel name conventions as outlined in
https://www.python.org/dev/peps/pep-0427#file-name-convention and influenced by
https://www.python.org/dev/peps/pep-0425.
```

Once we have a shared example, the obvious places to compare will be correctness changes and missed caching opportunities after that. I'm pretty sure pex pre 2.0.0 incorrectly handled multi-interpreter / multi-platform.

In pex<2.0.0:
1. The list of interpreters and the list of platforms were combined in a cross-product, and, for each, a resolve was done.
2. When a wheel for a foreign platform was not found, the active interpreter in the cross-product was use to build a wheel - this is incorrect.

In pex>=2.0.0:
1. A full resolve is done for each interpreter, and then for each platform that is foreign, a full resolve is done.
2. For foreign platforms, no wheel building is allowed. Either a wheel for the foreign platform is found, or the resolve fails - this is correct.

**Comment by AlexHill** [comment]
Sorry yes, I've edited my initial post to make that clear. I was effectively doing the cross-product manually to provide the six relevant `--platform` arguments in 2.0.

**Comment by jsirois** [comment]
Do you have a public distribution I can try this against that has pre-built wheels? It would be extremely useful to have an exact command line we can both execute to work this problem. I don't have access to an arm box, so if you can't provide a public example I'll have to simulate with a Linux / OSX example.

**Comment by jsirois** [comment]
For a similar repro case I'm using numpy:
```
$ time ~/Downloads/pex-1.6.12.pex -vvv --platform=manylinux1-x86_64-cp-35-m --platform=manylinux1-x86_64-cp-36-m --platform=manylinux1-x86_64-cp-37-m --platform=macosx-10.9-x86_64-cp-35-m --platform=macosx-10.9-x86_64-cp-36-m --platform=macosx-10.9-x86_64-cp-37-m numpy==1.17.4 --python-shebang "/usr/bin/env python3" -o numpy-pex1.6.2.pex
...
Saving PEX file to numpy-pex1.6.2.pex

real	0m20.963s
user	0m19.862s
sys	0m0.852s
```
vs.
```
$ time ~/Downloads/pex-2.0.2.pex -vvv --platform=manylinux1-x86_64-cp-35-m --platform=manylinux1-x86_64-cp-36-m --platform=manylinux1-x86_64-cp-37-m --platform=macosx-10.9-x86_64-cp-35-m --platform=macosx-10.9-x86_64-cp-36-m --platform=macosx-10.9-x86_64-cp-37-m numpy==1.17.4 --python-shebang "/usr/bin/env python3" -o numpy-pex2.0.2.pex
...
Saving PEX file to numpy-pex2.0.2.pex

real	0m27.946s
user	0m24.947s
sys	0m1.935s
```

Thats 40% slower with pex 2.0.2.

Noting a few things:
1. Since platforms are now required to be exact, there is no need when building a multiplatform pex to specify both `--python` and `--platform`, `--platform` is enough. Note though, `--platform` now requires all wheels be available for that platform pre-built.
2. Looking at the verbose output of both its clear pex caches the resolve better in 1.6.2 than it does in 2.0.2 accounting for most of the speed difference.

I'll look at the caching 1st.

**Comment by jsirois** [comment]
A reasonable change has the above example down to 23s in he pex 2.0 case or ~10% slower. These measurements are with warm caches. There is one further obvious change for the cold cache case to parallelize installation of wheels in chroots. I'll get out seperate PRs for both here.

**Comment by AlexHill** [comment]
You probably get this all the time but I'm consistently impressed by your responsiveness and turnaround - before I've even posted a proper repro case you've made a fix and a new release. Amazing, thankyou!

The new version is a lot faster for my use case.

> Since platforms are now required to be exact, there is no need when building a multiplatform pex to specify both --python and --platform, --platform is enough.

Okay, this is what I was wondering and good to know. Under pex 2.0.2, when I specify multiple `--python` arguments, I get different artifacts so I wasn't sure - but upon inspection I think the only thing that's different is the `version` key under `build_properties` in PEX-INFO which I assume doesn't affect anything at runtime.

> Note though, --platform now requires all wheels be available for that platform pre-built

Yep, that's all good. I have a pre-built universal pure-python PyYAML wheel which I supply with `--find-links`, and for everything else there are universal wheels. So I can actually just do `--platform any-py-3<5,6,7>-none` and be satisfied that if any transitive requirements change to require compilation, the build will fail.

As an appendix - with this change (these all produce effectively the same artifact with my dependencies):

`--python python3.5 --python python3.6 --python python3.7 --platform linux_armv7l-cp-35-m --platform linux_armv7l-cp-36-m --platform linux_armv7l-cp-37-m --platform linux_x86_64-cp-35-m --platform linux_x86_64-cp-36-m --platform linux_x86_64-cp-37-m`
takes **70s**

`--python python3.5 --python python3.6 --python python3.7 --platform any-py-35-none --platform any-py-36-none --platform any-py-37-none`
takes **40s**

`--platform any-py-35-none --platform any-py-36-none --platform any-py-37-none`
takes **18s**

And installing a single platform with no `--python` takes **8s**.

**Comment by jsirois** [comment]
Thanks for the report back @AlexHill. I didn't mean to close this out quite yet - 2 more fixes bring pretty much all the major perf wins we can have easily:

+ Parallelize resolve. #818
+ Cache sdist & local project builds #817

These will go out in the pex 2.0.3 release at which point I'll re-close this issue.
