### ISSUE TITLE
Attribute/item access or function call before check for None or undefined

### ISSUE THREAD

**Issue by huornlmj** [pantsbuild/pex#845]
https://github.com/pantsbuild/pex/blob/a2b6d0a645824e5ed20e422f34482b60e0e7cdd6/pex/vendor/_vendored/wheel/wheel/cli/convert.py#L67

Null-checking egg_info["arch"] suggests that it may be null, but it has already been dereferenced (line 62) on all paths leading to the check.

**Comment by jsirois** [comment]
Closing as wont fix as explained in #844.
