### ISSUE TITLE
Structurally dead code but no stubbing comment

### ISSUE THREAD

**Issue by huornlmj** [pantsbuild/pex#846]
https://github.com/pantsbuild/pex/blob/a2b6d0a645824e5ed20e422f34482b60e0e7cdd6/pex/vendor/_vendored/setuptools/setuptools/_vendor/pyparsing.py#L650

This cannot be reached but there is no stubbing comment like similar instances in the same file (e.g. line 4203).

**Comment by jsirois** [comment]
Closing as wont fix as explained in #844.
