### ISSUE TITLE
Logically dead code in requirements.py L107

### ISSUE THREAD

**Issue by huornlmj** [pantsbuild/pex#847]
https://github.com/pantsbuild/pex/blob/a2b6d0a645824e5ed20e422f34482b60e0e7cdd6/pex/vendor/_vendored/pip/pip/_vendor/packaging/requirements.py#L107

At line 108, `parsed_url.scheme` must be true.
Execution cannot reach the expression `parsed_url.netloc` inside the statement on line 108, because the condition `not (parsed_url.scheme `cannot be true.

Same occurs in /pex/vendor/_vendored/setuptools/setuptools/_vendor/packaging/requirements.py line 123

**Comment by jsirois** [comment]
Closing as wont fix as explained in #844.
