### ISSUE TITLE
Logically dead code in requests auth.py

### ISSUE THREAD

**Issue by huornlmj** [pantsbuild/pex#848]
https://github.com/pantsbuild/pex/blob/a2b6d0a645824e5ed20e422f34482b60e0e7cdd6/pex/vendor/_vendored/pip/pip/_vendor/requests/auth.py#L223

Line 175, `entdig = None`
Line 222, `if entdig:` cannot be true
Line 223 is never reached

**Comment by jsirois** [comment]
Closing as wont fix as explained in #844.
