### ISSUE TITLE
Please be clear about using virtualenv or venv #Documentation

### ISSUE THREAD

**Issue by hivemall** [pantsbuild/pex#878]
While diggung through your docs + talks, there is no clear mention of what virtual environment you are using. Pypa endorses venv which also is stdlib natively , thus i highly favor.

What are you using, can venv be used too, what would hinder it?

**Comment by jsirois** [comment]
We use neither and implement our own isolation mechanism instead that works from within a zipfile (from inside a PEX). That isolation code exists primarily in two places:
1. https://github.com/pantsbuild/pex/blob/85f156548e3ac0d4d9c03246815a4dd0a67a31ed/pex/environment.py#L37
2. https://github.com/pantsbuild/pex/blob/1b7689e7c74fc80c92d8177181c464bc77930123/pex/pex.py#L379

**Comment by jsirois** [comment]
I'm going to close this issue as answered, but if you have more questions about this please fire away.
