### ISSUE TITLE
Py4JException: Constructor org.apache.spark.api.python.PythonAccumulationV2 does not exist

### ISSUE THREAD

**Issue by dclong** [pantsbuild/pex#904]
I got the following error while using PEX with PySpark. 
```
py4j.protocol.Py4JError: An error occurred while calling None.org.apache.spark.api.python.PythonAccumulatorV2. Trace:
py4j.Py4JException: Constructor org.apache.spark.api.python.PythonAccumulatorV2([class java.lang.String, class java.lang.Integer, class java.lang.String]) does not exist
```
The environment variable `PYTHONPATH` (I checked it inside the PEX environment in PySpark) is set to the following. Is there any other path that I should add to `PYTHONPATH` manually?
'PYTHONPATH': '/hadoop/5/yarn/local/usercache/dclong/filecache/31/__spark_libs__385482079064142506.zip/spark-core_2.11-0.4.jar:/hadoop/2/yarn/local/usercache/dclong/appcache/application_1581371194283_161101/container_e2601_1581371194283_161101_02_000001/pyspark.zip:/hadoop/2/yarn/local/usercache/dclong/appcache/application_1581371194283_161101/container_e2601_1581371194283_161101_02_000001/py4j-0.10.7-src.zip',

**Comment by jsirois** [comment]
When building the pex you can use the `--inherit-path` option to break PEX hermeticity and allow `PYTHONPATH` to leak in:
```
$ pex --help
...
  PEX output options:
    Tailor the behavior of the emitted .pex file if -o is specified.
    ...
    --inherit-path=INHERIT_PATH
                        Inherit the contents of sys.path (including site-
                        packages, user site-packages and PYTHONPATH) running
                        the pex. Possible values: false (does not inherit
                        sys.path), fallback (inherits sys.path after packaged
                        dependencies), prefer (inherits sys.path before
                        packaged dependencies), No value (alias for prefer,
                        for backwards compatibility). [Default: false]
```

If the pex is already built without this option or else you only want to change this behavior locally you can export `PEX_INHERIT_PATH`:
```
$ pex --help-variables
...
PEX_INHERIT_PATH: String (false|prefer|fallback)

    Allow inheriting packages from site-packages, user site-packages
    and the PYTHONPATH. By default, PEX scrubs any non stdlib packages
    from sys.path prior to invoking the application. Using 'prefer'
    causes PEX to shift any non-stdlib packages before the pex
    environment on sys.path and using 'fallback' shifts them after
    instead. Using this option is generally not advised, but can help
    in situations when certain dependencies do not conform to standard
    packaging practices and thus cannot be bundled into PEX files.
    Default: false.
```
```

**Comment by jsirois** [comment]
I'm going to close this as answered, but please speak up and include `pex --version` if you have more questions.

**Comment by dclong** [comment]
@jsirois Thank you for the prompt response! I tried to build the pex environment file with the option `--inherit-path=prefer`. It made Spark work but Spark failed to find hive meta information. A Spark application that does not using any Hive table works while a Spark application using a Hive table fails. Any insights? I'm using pex 2.1.3.

![image](https://user-images.githubusercontent.com/824507/74996199-c7b12100-5407-11ea-87ca-dbfa3e6cfab6.png)

**Comment by jsirois** [comment]
> It made Spark work but Spark failed to find hive meta information. A Spark application that does not using any Hive table works while a Spark application using a Hive table fails. Any insights? I'm using pex 2.1.3.

I have never used spark or hive so I really have no insights at all.
