### ISSUE TITLE
Failed to set the pex root directory

### ISSUE THREAD

**Issue by dclong** [pantsbuild/pex#905]
I tried to use pex with PySpark and run into [the permission denied issue](https://github.com/pantsbuild/pex/issues/359) with the default pex root directory. I tried to set a different writable pex root directory using a few approaches but all failed. 

## --conf spark.executorEnv.PEX_ROOT
It seems to me that pex doesn't honor the environment variable set by this way. I can verify from PySpark (not with pex) that environment variables set this is readable by Python but when used with pex, it has no effect. The pex root directory is always `/home/.pex`.
```
#!/bin/bash

/apache/spark2.3/bin/spark-submit \
    --files "file:///apache/hive/conf/hive-site.xml,file:///apache/hadoop/etc/hadoop/ssl-client.xml,file:///apache/hadoop/etc/hadoop/hdfs-site.xml,file:///apache/hadoop/etc/hadoop/core-site.xml,file:///apache/hadoop/etc/hadoop/federation-mapping.xml" \
    --master yarn \
    --deploy-mode cluster \
    --queue YOUR_QUEUE \
    --num-executors 200 \
    --executor-memory 10G \
    --driver-memory 15G \
    --executor-cores 4 \
    --conf spark.yarn.maxAppAttempts=2 \
    --conf spark.dynamicAllocation.enabled=true \
    --conf spark.dynamicAllocation.maxExecutors=1000 \
    --conf spark.network.timeout=300s \
    --conf spark.executor.memoryOverhead=2G \
    --conf spark.pyspark.driver.python=./env.pex \
    --conf spark.pyspark.python=./env.pex \
    --conf spark.executorEnv.PEX_ROOT=/some/writable/directory \
    --files env.pex \
    $1
```

## PEX_ROOT=/some/writable/directory ./env.pex
I got the error message saying that "cannot run the program `PEX_ROOT=/some/writable/directory ./env.pex`, file or directory not found".
```
#!/bin/bash

/apache/spark2.3/bin/spark-submit \
    --files "file:///apache/hive/conf/hive-site.xml,file:///apache/hadoop/etc/hadoop/ssl-client.xml,file:///apache/hadoop/etc/hadoop/hdfs-site.xml,file:///apache/hadoop/etc/hadoop/core-site.xml,file:///apache/hadoop/etc/hadoop/federation-mapping.xml" \
    --master yarn \
    --deploy-mode cluster \
    --queue YOUR_QUEUE \
    --num-executors 200 \
    --executor-memory 10G \
    --driver-memory 15G \
    --executor-cores 4 \
    --conf spark.yarn.maxAppAttempts=2 \
    --conf spark.dynamicAllocation.enabled=true \
    --conf spark.dynamicAllocation.maxExecutors=1000 \
    --conf spark.network.timeout=300s \
    --conf spark.executor.memoryOverhead=2G \
    --conf spark.pyspark.driver.python="PEX_ROOT=/some/writable/directory ./env.pex" \
    --conf spark.pyspark.python="PEX_ROOT=/some/writable/directory ./env.pex" \
    --files env.pex \
    $1
```
## ./env.pex --pex-root /some/writable/directory
Similarly, I got the error message saying that "cannot run the program `./env.pex --pex-root /some/writable/directory`, file or directory not found".
```
#!/bin/bash

/apache/spark2.3/bin/spark-submit \
    --files "file:///apache/hive/conf/hive-site.xml,file:///apache/hadoop/etc/hadoop/ssl-client.xml,file:///apache/hadoop/etc/hadoop/hdfs-site.xml,file:///apache/hadoop/etc/hadoop/core-site.xml,file:///apache/hadoop/etc/hadoop/federation-mapping.xml" \
    --master yarn \
    --deploy-mode cluster \
    --queue YOUR_QUEUE \
    --num-executors 200 \
    --executor-memory 10G \
    --driver-memory 15G \
    --executor-cores 4 \
    --conf spark.yarn.maxAppAttempts=2 \
    --conf spark.dynamicAllocation.enabled=true \
    --conf spark.dynamicAllocation.maxExecutors=1000 \
    --conf spark.network.timeout=300s \
    --conf spark.executor.memoryOverhead=2G \
    --conf spark.pyspark.driver.python="PEX_ROOT=/some/writable/directory ./env.pex" \
    --conf spark.pyspark.python="PEX_ROOT=/some/writable/directory ./env.pex" \
    --files env.pex \
    $1
```

**Comment by jsirois** [comment]
Your 1st attempt looks like the right way to do this. I know nothing about spark, but just now searched through the docs, and given your config (yarn), it looks like you need `--conf spark.yarn.appMasterEnv.PEX_ROOT=/some/writable/directory` instead of `--conf spark.executorEnv.PEX_ROOT=/some/writable/directory`. The docs I read are here: https://spark.apache.org/docs/2.3.0/running-on-yarn.html#configuration, but snipped:

> Add the environment variable specified by EnvironmentVariableName to the Application Master process launched on YARN. The user can specify multiple of these and to set multiple environment variables. In cluster mode this controls the environment of the Spark driver and in client mode it only controls the environment of the executor launcher.

Let me know if this works for you.

**Comment by dclong** [comment]
@jsirois Thank you for your inspirations! It turns out that I need to export the environment variable `PEX_ROO` for both executor nodes and the master node since I used pex on both executor nodes and the master node. This means that I need of the following configurations.
```
--conf spark.executorEnv.PEX_ROOT=/some/writable/directory
--conf spark.yarn.appMasterEnv.PEX_ROOT=/some/writable/directory
```
