### ISSUE TITLE
Remove pkg_resources.build_zipmanifest monkeypatching

### ISSUE THREAD

**Issue by wickman** [pantsbuild/pex#91]
This may involve increasing the minimum setuptools version.  Another alternative is vendoring setuptools.

**Comment by dan-blanchard** [comment]
From pypa/setuptools#154, it appears the reason for the monkeypatching was fixed in setuptools 5.4, so setting the minimum version to at least that should do the trick.

**Comment by kwlzn** [comment]
sgtm. reviewable here: https://github.com/pantsbuild/pex/pull/322

**Comment by kwlzn** [comment]
btw, it looks like from setuptools 5.4->5.6 you have to set the  `PKG_RESOURCES_CACHE_ZIP_MANIFESTS` environment variable to get this behavior - and it's on by default after 5.7: https://pypi.python.org/pypi/setuptools/5.7#id1

will bump the minimum version in the PR to 5.7 based on this.
