### ISSUE TITLE
Pex files breaking if renamed?

### ISSUE THREAD

**Issue by honnibal** [pantsbuild/pex#919]
I think this might be a regression sometime in v2.1. Tested with v2.1.6.

If I rename the pex file after building it, it doesn't execute, because it's looking for the folder according to the original name:

```
$ ./spacy-2.2.3.pex # Works
$ mv spacy-2.2.3.pex spacy.pex
nomad@worker-lj8x:~$ ./spacy.pex
Traceback (most recent call last):
  File "/home/nomad/spacy.pex/.bootstrap/pex/pex.py", line 391, in execute
  File "/home/nomad/spacy.pex/.bootstrap/pex/pex.py", line 83, in _activate
  File "/home/nomad/spacy.pex/.bootstrap/pex/pex_info.py", line 81, in from_pex
FileNotFoundError: [Errno 2] No such file or directory: 'spacy-2.2.3.pex/PEX-INFO'
```

**Comment by jsirois** [comment]
@honnibal a quick scan of the backtrace / implicated code lines implies the `PEX_PATH` env var is set (or set through a pexrc file) or else the PEX was built with `--pex-path`. Can you confirm or deny this? Possibly extracting the PEX-INFO file from the PEX (a zip file) and attaching or pasting it here would be useful.

**Comment by jsirois** [comment]
@honnibal let me know if you have any of the information requested above and I'll resume investigation.
I'm going to close this issue for now though since there has been no actionable information provided yet.
