### ISSUE TITLE
Improve error message when interpreters cannot be found

### ISSUE THREAD

**Issue by Eric-Arellano** [pantsbuild/pex#922]
Current:

```
pex --interpreter-constraint='CPython>=3.8.*'
Could not find compatible interpreter
```

This is a fine message for trivial constraints, especially when using Pex directly through the CLI. But, this is hard to interpret when there are complex constraints and when Pex is used programmatically, such as Pants passing often quite complex constraints to Pex.

An ideal message will
a) output all requested constraints
b) identify which interpreters were recognized by Pex
c) offer suggestions to resolve the issue

See https://github.com/pantsbuild/pants/pull/7628 for possible inspiration.

**Comment by jsirois** [comment]
I don't think `c` can be satisfied without stating the obvious, but how about:
```
$ python -m pex --interpreter-constraint='>=3.9'
Examined the following interpreters:
	/opt/pypy/bin/pypy PyPy==2.7.13
	/usr/bin/python2.7 CPython==2.7.17
	/usr/bin/python3.5 CPython==3.5.9
	/usr/bin/python3.6 CPython==3.6.10
	/usr/bin/python3.7 CPython==3.7.7
	/usr/bin/python3.8 CPython==3.8.2
None were compatible with the requested constraints:
	>=3.9
Could not find compatible interpreter
```

**Comment by Eric-Arellano** [comment]
c) is indeed less relevant with Pex than Pants. In Pants, this is the message we use:

```
Possible ways to fix this:
* Modify your Python interpreter constraints by following https://www.pantsbuild.org/python_readme.html#configure-the-python-version.
* Ensure the targeted Python version is installed and discoverable.
* Modify Pants' interpreter search paths via --pants-setup-interpreter-search-paths.
```

The only one that we could bring from this to Pex is `Ensure the targeted Python version is installed and discoverable.`. Maybe:

> Ensure that the targeted Python version is installed and discoverable, or tweak your constraints to work with one of the discovered interpreters.

Indeed, this is obvious to us Pants devs, but think about a first time user (e.g. a summer intern) using Pex/Pants for the first time. This at least gives 2 paths forward. Thinking back to my first week at Foursquare two summers ago, this sentence would have helped me.

--

I really like your suggestion. The only tweak would be moving "Could not find compatible interpreter" to the very top of the message so that you know what the issue is, and then are presented with helpful information to debug.

**Comment by jsirois** [comment]
Since I have a branch I'm going to take this over and post for further discussion.
