### ISSUE TITLE
pex 2.1.7 not resolving tensorflow==1.14.0 if a correct interpreter constraint is provided

### ISSUE THREAD

**Issue by cosmicexplorer** [pantsbuild/pex#935]
Seen when trying to run something from the pants repo just now, and narrowed the issue down to the `--interpreter-constraint` option:
```bash
> pex pex==2.1.7 --entry-point=pex -- --interpreter-constraint='CPython>=3' tensorflow==1.14.0
ERROR: Could not find a version that satisfies the requirement tensorflow==1.14.0 (from versions: none)
ERROR: No matching distribution found for tensorflow==1.14.0
> pex pex==2.1.7 --entry-point=pex -- tensorflow==1.14.0
Python 3.7.7 (default, Mar 10 2020, 15:43:33)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>>
```

I'll be diving into this more tomorrow.

**Comment by cosmicexplorer** [comment]
This feels so absurd that I feel positive it must be only on my machine. This exact command line had definitely been working before. I've tried clearing `~/.pex`, and I've tried bisecting, but it continues to fail at every commit, so again, I feel positive it must be an issue on my local machine. `-vvvvvvvvv` is being used on all commands I'm running to investigate this -- the error is the same. It also fails on every python interpreter I try to use when running:
```bash
> python -m pex.bin.pex -vvvvvvvvv --interpreter-constraint='CPython' 'tensorflow==1.14.0'
```

**Comment by jsirois** [comment]
It's on my machine too Danny, but it makes sense:
```
$ pex pex==2.1.7 -c pex -- --interpreter-constraint='CPython>=3' tensorflow==1.14.0
ERROR: Could not find a version that satisfies the requirement tensorflow==1.14.0 (from versions: 2.2.0rc1)
ERROR: No matching distribution found for tensorflow==1.14.0
pid: 45334 -> /usr/bin/python3.8 /tmp/tmpz2yayp4y --disable-pip-version-check --isolated --no-python-version-warning -q --cache-dir /home/jsirois/.pex download --dest /tmp/tmpot39wtar/resolved_dists/cp38-cp38 tensorflow==1.14.0 raised Executing /usr/bin/python3.8 /tmp/tmpz2yayp4y --disable-pip-version-check --isolated --no-python-version-warning -q --cache-dir /home/jsirois/.pex download --dest /tmp/tmpot39wtar/resolved_dists/cp38-cp38 tensorflow==1.14.0 failed with 1
```
So for me, Pex obeyed my instructions and attempted to build a PEX for my local python3.8 which is `CPython>=3`. Note `-v` is not needed to observe that.

Adding one `-v` reveals the full flight plan:
```
$ pex pex==2.1.7 -c pex -- -v --interpreter-constraint='CPython>=3' tensorflow==1.14.0
pex: Building pex :: Resolving distributions (['tensorflow==1.14.0']) :: Resolving for:
  DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.8', PythonIdentity('/usr/bin/python3.8', 'cp38', 'cp38', 'manylinux2014_x86_64', (3, 8, 2))))
  DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.5', PythonIdentity('/usr/bin/python3.5', 'cp35', 'cp35m', 'manylinux2014_x86_64', (3, 5, 9))))
  DistributionTarget(interpreter=PythonInterpreter('/usr/bin/python3.6', PythonIdentity('/usr/bin/python3.6', 'cp36', 'cp36m', 'manylinux2014_x86_64', (3, 6, 10))))
pex: Isolating pex
...
```
Looking over at tensorflow==1.14.0 (https://pypi.org/project/tensorflow/1.14.0/#files), it is only released in binary form so we can't compile locally and its only released for up to python3.7 and is not abi3 compatible.

Sure enough:
```
$ pex pex==2.1.7 -c pex -- --interpreter-constraint='CPython>=3,<=3.7' tensorflow==1.14.0
Python 3.5.9 (default, Jan 17 2020, 18:02:21) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> 
```
And:
```
$ pex pex==2.1.7 -c pex -- --interpreter-constraint='CPython>=3,<=3.7' tensorflow==1.14.0 -o tensorflow.pex
$ zipinfo -1 tensorflow.pex | grep tensorflow | grep .whl | grep WHEEL
.deps/tensorflow-1.14.0-cp35-cp35m-manylinux1_x86_64.whl/tensorflow-1.14.0.dist-info/WHEEL
.deps/tensorflow-1.14.0-cp36-cp36m-manylinux1_x86_64.whl/tensorflow-1.14.0.dist-info/WHEEL
.deps/tensorflow_estimator-1.14.0-py2.py3-none-any.whl/tensorflow_estimator-1.14.0.dist-info/WHEEL
```
So the PEX builds successfully for python3.5 and python3.6.

The correct interpreter constraint to guaranty non-failure is `--interpreter-constraint='CPython>=3.3,<=3.7'` since tensorflow at version 1.14.0 is only published for those pythons.

I'm guessing that the `--interpreter-constraint` really is picking an interpreter on your machine that there is no published tensorflow wheel for. This highlights that `--interpreter-constraint` has never been a fully coherent buildtime option. It's contingent to your machine, and it may pick many more interpreters than you care about if you have alot installed. On my machine I have 15 split between 7 PATH and 8 pyenv. I don't think there is a good alternative to ` --interpreter-constraint` at buildtime yet, so it stays, but it's problematic in exactly the way you discovered.

**Comment by jsirois** [comment]
I'm going to mark this as answered but will leave open pending your report back with more detailed console output from various levels of `-v`.

**Comment by cosmicexplorer** [comment]
> I'm guessing that the --interpreter-constraint really is picking an interpreter on your machine that there is no published tensorflow wheel for.

It was picking a 3.8 interpreter! And this:
> The correct interpreter constraint to guaranty non-failure is --interpreter-constraint='CPython>=3.3,<=3.7' since tensorflow at version 1.14.0 is only published for those pythons.

was super helpful! I had been assuming that just `<4` would be sufficient, not thinking that hard about what that meant before.

> This highlights that --interpreter-constraint has never been a fully coherent buildtime option. It's contingent to your machine, and it may pick many more interpreters than you care about if you have alot installed.

What would you think about an error message that triggers when a resolve fails, which displays all available interpreter/abi platforms that *could* have matched, but didn't (kind of like when you specify an incorrect version constraint and pip/pex tells you which versions actually existed)?

If there had been a big message at `PEX_VERBOSE=0` whenever a resolve fails that did just a little bit of bookkeeping, this might have been less mysterious to me.

On the other hand, now that I know to keep in mind sneaky other interpreter versions, I don't know if the effort to do that is justified. It could be another spelunking adventure in pip.

**Comment by jsirois** [comment]
> What would you think about an error message that triggers when a resolve fails, which displays all available interpreter/abi platforms that could have matched, but didn't (kind of like when you specify an incorrect version constraint for a requirement and pip/pex tells you which versions actually existed)?

Yeah, that's what the doctor ordered but it requires pip work. Currently you can only scrape this from  `pip -v` output. Pip would need an option to present a resolve failure in structured form, probably `--log-solution-input=failure.json`.
