### ISSUE TITLE
DeprecationWarning: 'U' mode is deprecated

### ISSUE THREAD

**Issue by walles** [pantsbuild/pex#942]
Quoting this failing Travis run: <https://travis-ci.com/github/walles/px/jobs/311074370>

```
test-pex3 run-test: commands[2] | python -Werror '-Wdefault:the imp module' /home/travis/build/walles/px/dist3/px.pex
Traceback (most recent call last):
  File ".bootstrap/pex/pex.py", line 349, in execute
  File ".bootstrap/pex/pex.py", line 276, in patch_sys
  File ".bootstrap/pex/pex.py", line 244, in minimum_sys
  File ".bootstrap/pex/pex.py", line 119, in _extras_paths
  File ".bootstrap/pex/util.py", line 228, in iter_pth_paths
DeprecationWarning: 'U' mode is deprecated
```

Looking at `util.py` in `iter_pth_paths`, it goes:
https://github.com/pantsbuild/pex/blob/1b7689e7c74fc80c92d8177181c464bc77930123/pex/util.py#L200-L203

Please remove the deprecated use of `U` file mode?

Regards /Johan

**Comment by walles** [comment]
Quoting [the Python docs](https://docs.python.org/3.8/library/functions.html#open):
> There is an additional mode character permitted, 'U', which no longer has any effect, and is considered deprecated. It previously enabled universal newlines in text mode, which became the default behaviour in Python 3.0. Refer to the documentation of the newline parameter for further details.

So maybe this will have to wait until if or when dropping Python 2.7 support?

You decide, feel free to keep or close!

**Comment by Eric-Arellano** [comment]
> So maybe this will have to wait until if or when dropping Python 2.7 support?

We will likely keep Python 2 support for some time because Pex is a core piece of infrastructure, similar to Pip keeping Python 2 for some time, even though it's EOL.

Instead, the solution is to add ugly glue code. I'll fix this up. Thank you for reporting!

**Comment by Eric-Arellano** [comment]
@walles see https://github.com/pantsbuild/pex/pull/956.
