### ISSUE TITLE
Requirement resolution errors should provide enough information to resolve conflicts.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#943]
Right now `ResolveRequest._check_resolve` just informs the user that a particular distribution's requirement was not satisfied:
https://github.com/pantsbuild/pex/blob/73ce2f4b4fdc1fe3ad76779c06f0b9a25f443384/pex/resolver.py#L603-L642

We could do more work and provide the full list of other requirers and their requirements.

**Comment by stuhood** [comment]
Ah, so: I filed a related error over here: #943.

It is not precisely the same codepath, but the resolution seems to be similar... render all relevant requirement declarations to determine which dependency something came from (...possibly transitively up from the error?)

**Comment by jsirois** [comment]
> Ah, so: I filed a related issue over here: #943.

@stuhood you referenced the wrong issue (this one). I'm not sure which issue you meant to reference. Can you update?

**Comment by stuhood** [comment]
Sorry about that. Updated to #947.

**Comment by jsirois** [comment]
We're losing the ability to have control over this. For --resolver-version=pip-2020-resolver we cede all control - Pip now always fails inconsistent resolves so we have no data to post-process. As such I'm going to close this as obsolete.
