### ISSUE TITLE
Not able to reference local WSDL file when using PEX 

### ISSUE THREAD

**Issue by arnabthumbtack** [pantsbuild/pex#946]
I have a question about pex build. So we have this project structure and we are trying to build a pex file off of it. It has a WSDL file which needs to be referenced in the code. No matter what I do, when I run the pex file, it throws an exception: File Not Found . Does anyone have any idea how to fix it? 

Below is the folder structure -

```
Main_Folder
      Util
            util1.py
      main.py
      WebService.xml
```

```
path = os.path.join(os.path.abspath(__file__), 'WebService.xml')
url = urllib.parse.urljoin('file:', urllib.request.pathname2url(os.path.abspath(path)))
```

**Comment by dgkatz** [comment]
I had a similair issue where I needed to "access" static files from python when running in pex.
The solution i came up with was unzipping the needed file(s) out of the pex into some other location, then the files should be accesible from there.
For info on how to unzip certian files in python: https://stackoverflow.com/questions/13765486/how-to-unzip-specific-folder-from-a-zip-with-python

**Comment by jsirois** [comment]
There are 2 old ways to fix this and 1 new way as-of Pex 2.1.8. All are predicated on the idea that filesystem APIs don't work when you run from inside a zip file and PEXes are zip files.
1. Don't use file system APIs, use resource APIs.
  Common choices are:

    a. The `pkg_resources` APIs from `setuptools` (you'll need to add a requirement for setuptools to your project to use these APIs): https://setuptools.readthedocs.io/en/latest/pkg_resources.html#basic-resource-access
    b. The Python stdlib `pkgutil` API: https://docs.python.org/3/library/pkgutil.html#pkgutil.get_data

2. Use filesystem APIs.
  You just need to mark your PEX file as being not zip safe. This can be done by either of:
    
    a. Specify `--not-zip-safe` when building your PEX file.
    b. Export `PEX_FORCE_LOCAL=1` at runtime to mark your already-built PEX file as being not zip safe.

The new way of doing 2 which can also speed up your app startup time in many cases is to specify `--unzip` when building the PEX using `pex>=2.1.8`.

**Comment by jsirois** [comment]
@arnabthumbtack and @dgkatz hopefully the explanation above makes sense / provides ease of use. I'm going to close this as answered, but please speak up if any of the above still leaves you wanting.

**Comment by arnabthumbtack** [comment]
Thanks @jsirois It makes sense. I will give it a try.

**Comment by arnabthumbtack** [comment]
> I had a similair issue where I needed to "access" static files from python when running in pex.
> The solution i came up with was unzipping the needed file(s) out of the pex into some other location, then the files should be accesible from there.
> For info on how to unzip certian files in python: https://stackoverflow.com/questions/13765486/how-to-unzip-specific-folder-from-a-zip-with-python

I did the same way..
