### ISSUE TITLE
ImportError when importing pkg_resources

### ISSUE THREAD

**Issue by taranlu-houzz** [pantsbuild/pex#949]
**Problem**:
I use `poetry` for development and have been exploring pex lately. I have run into an issue with projects that use `pkg_resources`. The simplified example below causes an error for me:

```lang=sh
poetry new --src to_delete
cd to_delete
poetry add --dev pex
poetry run pex
>>> import pkg_resources
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: No module named pkg_resources
```

I don't think this is an issue on `poetry`'s end, since it is just creating a venv and installing `pex` into it. I've seen a couple of other issues that seem like they might be related: #749, #307 

**Config**:
I'm on macOS using the `brew` installed version of Python 2.7.16.

```lang=sh
pex --version
pex 2.1.8

poetry --version
Poetry version 1.0.5
```

**Comment by taranlu-houzz** [comment]
My actual use case is that I am trying to use `pex` to build a .pex file with my package installed inside of it. It does generate the file, but when trying to run the `output.pex` it breaks with the `ImportError` on `pkg_resources`. Previously, this had worked, but I recently started using `pkg_resources` to pull version information on the distribution from within the package, which is how I started running into this error.

**Comment by jsirois** [comment]
@taranlu-houzz unlike `virtualenv` / `python -mvenv`, Pex virtual environments are completely hermetic. They do not expose any dependencies you did not ask for to your application. So no "free" setuptools, pip or wheel like you get in virtualenvs. You should just need to add an explicit dependency on `setuptools` to gain access to it's `pkg_resources` APIs:
```
jsirois@gill /tmp/to_delete $ poetry run pex setuptools
Python 3.8.2 (default, Feb 26 2020, 22:21:03) 
[GCC 9.2.1 20200130] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import pkg_resources
>>> pkg_resources.__file__
'/tmp/tmphz2zj42h/.deps/setuptools-46.1.3-py3-none-any.whl/pkg_resources/__init__.py'
>>> 
now exiting InteractiveConsole...
```
Perhaps more vividly:
```
jsirois@gill /tmp/to_delete $ poetry run pex setuptools -o example.pex
jsirois@gill /tmp/to_delete $ zipinfo -1 example.pex
.bootstrap/_pex/__init__.py
...
.bootstrap/pex/version.py
...
.deps/setuptools-46.1.3-py3-none-any.whl/pkg_resources/__init__.py
...
.deps/setuptools-46.1.3-py3-none-any.whl/setuptools-46.1.3.dist-info/INSTALLER
.deps/setuptools-46.1.3-py3-none-any.whl/setuptools-46.1.3.dist-info/LICENSE
.deps/setuptools-46.1.3-py3-none-any.whl/setuptools-46.1.3.dist-info/METADATA
.deps/setuptools-46.1.3-py3-none-any.whl/setuptools-46.1.3.dist-info/RECORD
.deps/setuptools-46.1.3-py3-none-any.whl/setuptools-46.1.3.dist-info/WHEEL
.deps/setuptools-46.1.3-py3-none-any.whl/setuptools-46.1.3.dist-info/dependency_links.txt
.deps/setuptools-46.1.3-py3-none-any.whl/setuptools-46.1.3.dist-info/entry_points.txt
.deps/setuptools-46.1.3-py3-none-any.whl/setuptools-46.1.3.dist-info/top_level.txt
.deps/setuptools-46.1.3-py3-none-any.whl/setuptools-46.1.3.dist-info/zip-safe
...
.deps/setuptools-46.1.3-py3-none-any.whl/setuptools/windows_support.py
PEX-INFO
__main__.py
jsirois@gill /tmp/to_delete $
```

Pex will only give your application to the dependencies embedded inside your PEX under `.deps/`. You get dependencies in their by specifying `pex [requirements]` or `pex --requirements=[requirements.txt file]` or a combination of the two.

**Comment by jsirois** [comment]
@taranlu-houzz I'm going to close this as answered, but please speak up if you're still running into issues after this explanation.
