### ISSUE TITLE
`--platform` incorrectly reads the `abi` when using the unabbreviated platform string format

### ISSUE THREAD

**Issue by Eric-Arellano** [pantsbuild/pex#953]
> ▶ pex tensorflow --platform=manylinux2010_x86_64-cp-37-37m
> ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
> ERROR: No matching distribution found for tensorflow
pid: 82372 -> /usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/bin/python3.7 /var/folders/sx/pdpbqz4x5cscn9hhfpbsbqvm0000gn/T/tmpo3j06cp5 --disable-pip-version-check --isolated --exists-action i -q --cache-dir /Users/eric/.pex download --dest /var/folders/sx/pdpbqz4x5cscn9hhfpbsbqvm0000gn/T/tmp9ym4s833/resolved_dists/manylinux2010_x86_64-cp-37-cp3737m --platform manylinux2010_x86_64 --implementation cp --python-version 37 --abi cp3737m --only-binary :all: tensorflow raised Executing /usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/bin/python3.7 /var/folders/sx/pdpbqz4x5cscn9hhfpbsbqvm0000gn/T/tmpo3j06cp5 --disable-pip-version-check --isolated --exists-action i -q --cache-dir /Users/eric/.pex download --dest /var/folders/sx/pdpbqz4x5cscn9hhfpbsbqvm0000gn/T/tmp9ym4s833/resolved_dists/manylinux2010_x86_64-cp-37-cp3737m --platform manylinux2010_x86_64 --implementation cp --python-version 37 --abi cp3737m --only-binary :all: tensorflow failed with 1
```

Of note: `--abi cp3737m`

--

This command does work when using the abbreviated tag `manylinux2010_x86_64-cp-37-m`.

**Comment by jsirois** [comment]
The platform tag passed in the example is bad:
```
$ pex --help
...
  PEX environment options:
...
    --platform=PLATFORMS
                        The platform for which to build the PEX. This option
                        can be passed multiple times to create a multi-
                        platform pex. To use wheels for specific
                        interpreter/platform tags, you can append them to the
                        platform with hyphens like: PLATFORM-IMPL-PYVER-ABI
                        (e.g. "linux_x86_64-cp-27-cp27mu",
                        "macosx_10.12_x86_64-cp-36-cp36m") PLATFORM is the
                        host platform e.g. "linux-x86_64",
                        "macosx-10.12-x86_64", etc". IMPL is the python
                        implementation abbreviation (e.g. "cp", "pp", "jp").
                        PYVER is a two-digit string representing the python
                        version (e.g. "27", "36"). ABI is the ABI tag (e.g.
                        "cp36m", "cp27mu", "abi3", "none"). Default: current
                        platform.
```

This corrected platform "works":
```
$ pex tensorflow --platform=manylinux2010_x86_64-cp-37-cp37m
ERROR: Could not find a version that satisfies the requirement wrapt>=1.11.1 (from tensorflow) (from versions: none)
ERROR: No matching distribution found for wrapt>=1.11.1 (from tensorflow)
pid: 49091 -> /usr/bin/python3.8 /home/jsirois/.pex/pip.pex/49a647f5ed9e81dc8f85560600c53fbb4dfc60f0 --disable-pip-version-check --isolated --no-python-version-warning -q --cache-dir /home/jsirois/.pex download --dest /tmp/tmpfbjz3nuf/resolved_dists/manylinux2010_x86_64-cp-37-cp37m --platform manylinux2010_x86_64 --implementation cp --python-version 37 --abi cp37m --only-binary :all: tensorflow raised Executing /usr/bin/python3.8 /home/jsirois/.pex/pip.pex/49a647f5ed9e81dc8f85560600c53fbb4dfc60f0 --disable-pip-version-check --isolated --no-python-version-warning -q --cache-dir /home/jsirois/.pex download --dest /tmp/tmpfbjz3nuf/resolved_dists/manylinux2010_x86_64-cp-37-cp37m --platform manylinux2010_x86_64 --implementation cp --python-version 37 --abi cp37m --only-binary :all: tensorflow failed with 1
```

But you really ought to probably just use `pex tensorflow --platform=linux_x86_64-cp-37-cp37m` since the Pex CLI defaults to supporting manylinux2014, which supports all prior manylinux per the specs for manylinux:
```
$ pex --help
...
  Resolver options:
...
    --manylinux=MANYLINUX, --no-manylinux=MANYLINUX, --no-use-manylinux=MANYLINUX
                        Whether to allow resolution of manylinux wheels for
                        linux target platforms; Default: allow manylinux
                        wheels compatible with manylinux2014
...
```
That also "works":
```
$ pex tensorflow --platform=linux_x86_64-cp-37-cp37m
ERROR: Could not find a version that satisfies the requirement termcolor>=1.1.0 (from tensorflow) (from versions: none)
ERROR: No matching distribution found for termcolor>=1.1.0 (from tensorflow)
pid: 49816 -> /usr/bin/python3.8 /home/jsirois/.pex/pip.pex/49a647f5ed9e81dc8f85560600c53fbb4dfc60f0 --disable-pip-version-check --isolated --no-python-version-warning -q --cache-dir /home/jsirois/.pex download --dest /tmp/tmp57cuu8m5/resolved_dists/linux_x86_64-cp-37-cp37m --platform manylinux2014_x86_64 --platform linux_x86_64 --implementation cp --python-version 37 --abi cp37m --only-binary :all: tensorflow raised Executing /usr/bin/python3.8 /home/jsirois/.pex/pip.pex/49a647f5ed9e81dc8f85560600c53fbb4dfc60f0 --disable-pip-version-check --isolated --no-python-version-warning -q --cache-dir /home/jsirois/.pex download --dest /tmp/tmp57cuu8m5/resolved_dists/linux_x86_64-cp-37-cp37m --platform manylinux2014_x86_64 --platform linux_x86_64 --implementation cp --python-version 37 --abi cp37m --only-binary :all: tensorflow failed with 1
```

Since ABI strings are essentially freeform, the best Pex could do here would be to:
1. Scrape pip logs for `No matching distribution found for tensorflow`.
2. Add heuristics to suggest fixes, one set being checking for platforms "close" to known typical values.

The above would be fragile and a large new feature to support moving forward - not attractive. The existing help docs are good and specifying a foreign platform is a bit advanced. I'm not sure this needs more machinery.

**Comment by jsirois** [comment]
I'm going to close this as answered, but speak up if you have ideas.

**Comment by Eric-Arellano** [comment]
Ah. Good catch and thank you for the thorough explanation!

Preferring `linux` over `manylinux` is new to me. I intuitively thought the opposite. It could be very helpful to add a sentence to the help string for `--platform` to point to `--manylinux`. Something like:

> For linux platforms, usually you should use the platform `linux` instead of `manylinux1` et al. Instead, use the option `--manylinux` to configure which manylinux version should be used (if any).

**Comment by jsirois** [comment]
It would take more than a sentence. This needs its whole own README since guidance changes depending on custom `--find-links` / `--indexes` and how the wheels housed there were built.
