### ISSUE TITLE
`--interpreter-constraint` causes the `current` platform to always be used

### ISSUE THREAD

**Issue by Eric-Arellano** [pantsbuild/pex#957]
From a macOS machine, without constraints:

```bash
▶ pex --platform=linux-x86_64-cp-37-cp37m --output-file test.pex cryptography && unzip -l test.pex | grep 'macosx' | wc -l
       0
```

With constraints:

```bash
▶ pex --platform=linux-x86_64-cp-37-cp37m --interpreter-constraint 'CPython>=3.6' --output-file test.pex cryptography && unzip -l test.pex | grep 'macosx' | wc -l
     151
```

This is a problem for Pants, which always sets `--interpreter-constraint`, meaning it is never possible with Pants to create a binary without `current` as a platform.

**Comment by jsirois** [comment]
Pants shouldn't do this. The only reasonable interpretation of interpreter constraints is a local PEX build.

**Comment by jsirois** [comment]
Basically --platform implies remote / don't build. Everything else (except --no-build) implies pick a local interpreter.
