### ISSUE TITLE
Ignore directory when building pex

### ISSUE THREAD

**Issue by dgkatz** [pantsbuild/pex#963]
I am using pex to package a python web application like so:
`pex -v -r requirements.txt -c gunicorn -D . -o $(PEXFILE)`
The `-D .` option will add all files in the project into the pex, but I have a use case where I want some directories not to be included in the pex.
Is there a way to tell pex to ignore certain directories when building?

**Comment by jsirois** [comment]
@dgkatz there is not currently besides using [Pants](https://pants.readme.io/docs/python-binary-goal) to create your PEXes. Pex does support creating binaries from setup.py projects however; so if your web application has one of those you can say: `pex -c gunicorn -o $(PEXFILE) .` where the current dir (`.`) has a `setup.py` file.

**Comment by jsirois** [comment]
@dgkatz I'm going to close this as answered, but speak up if you have more questions.

**Comment by dejbug** [comment]
One could of course unzip the `*.pex` and clean it up but it would be so very nice if there were a `.pexignore` .

**Comment by jsirois** [comment]
Perhaps easier, The 2.1.139 release added support for specifying individual modules and package trees to add: https://github.com/pantsbuild/pex/releases/tag/v2.1.139

The use case appears to have been similar, but the poster of that issue motivated why using `setup.py` / `pyproject.toml` to handle file selection was not acceptable: https://github.com/pantsbuild/pex/issues/2134

**Comment by dejbug** [comment]
Definitely. Anyting that gives one more control about the packaging process is very much appreciated. Thank you for the pointers!
