### ISSUE TITLE
Add support for closing over a fixed environment in PEX files.

### ISSUE THREAD

**Issue by jsirois** [pantsbuild/pex#987]
PEX files are in a class of applications that are main-delegators. PEX provides a `__main__` to Python that does some setup work and then hands off to a user main specified via `-c` or `-e` when building a PEX or else `PEX_SCRIPT` or `PEX_MODULE` at runtime.

The `gunicorn` console script provided by `gunicorn` is another main-delegator app. It expects an entry point of a certain signature in user code to hand off to after doing some setup work.

Its awkward to create PEXes of delegator-apps since there is currently no way to seal the entry point the delegator app should use into the PEX file itself without writing a small shim main python file.

Consider adding support for `--program-args` and `--program-env` to seal in fixed program arguments and environment to PEX-INFO metadata that is used to setup the PEX file user main when PEX `__main__` hands off to it.

Using the `gunicorn` example, that would allow creating a self-contained gunicorn app like so:
```
pex gunicorn==20.0.4 my_app==1.0.0. -c gunicorn --program-args my_app.entry:point -o my-gunicorn.pex
```
Executing `./gunicorn.pex` would then start a gunicorn whose entry point is `my_app.entry:point`.

This facility could transform how https://github.com/wickman/lambdex is used. Instead of running lambdex against a pre-existing PEX file, it could be re-worked to offer a main-delegator.

**Comment by silverguo** [comment]
@jsirois I finally get started on this, 

For `Support for storing this new field in PEX-INFO`, I didn't figure out how this will be used ? If adding `program_args` here, do we need to also make some changes here ?https://github.com/pantsbuild/pex/blob/da71661b35f1935d296b49f8ac375481760ae400/pex/pex_info.py#L68-L74

**Comment by jriddy** [comment]
What would the semantics of a `--program-env` argument be? Would these be default values to inject into the environment of the running process, or would they override whatever was specified in the containing environment?

**Comment by jsirois** [comment]
@jriddy I think default makes sense. I.E. `A=b ./my.pex` should override any default value sealed into `my.pex` for the `A` env var.
