### ISSUE TITLE
Implement bdist_pex

### ISSUE THREAD

**Issue by wickman** [pantsbuild/pex#99]
bdist_pex would be a natural way to build applications for production, especially if you just dump pex options into setup.cfg.

**Comment by msabramo** [comment]
Was just thinking the same thing, as I want to build a pex in our CI pipeline and the other things I build like sdist, wheel, and platter all automatically grab the version number and output a file with the version number in it. With pex, it seems I would have to get the version number and pass it to pex. But if there was a `python setup.py bdist_pex`, then it would be just like building an sdist or wheel and very natural.

**Comment by wickman** [comment]
There is also an implementation here: https://github.com/pantsbuild/pex/compare/master...wickman:wickman/99

**Comment by msabramo** [comment]
@wickman: OK, thanks! I sent a few PRs to your branch -- https://github.com/wickman/pex/pulls/msabramo

**Comment by wickman** [comment]
Now on 1.1.0.dev0
