### ISSUE TITLE
pex ignores --no-wheel/--no-use-wheel

### ISSUE THREAD

**Issue by AndrewHoos** [pantsbuild/pex#993]
If you run this command:
`python2 -m pex --no-use-wheel -r pex-requirements.txt -o python`

Then you unzip the pex it will have wheels inside of it.

**Comment by stuhood** [comment]
@AndrewHoos : Hey Andrew! My understanding of that option is that (similar to with `pip`) it controls whether PEX will fetch wheels from PyPI and your indexes, rather than whether it will use them at runtime.

Do you have a need to avoid wheels at runtime?

**Comment by AndrewHoos** [comment]
The more nuance level of frustration I am in right now is that if a create a `pex` with `virtualenv` it will not run on different versions of macOS. Because the scandir wheel gets resolved to `scandir-1.10.0-cp27-cp27m-macosx_10_<version>_x86_64`. If I try to use platform pip can't find the package `filelock` because pex specified python-version 2.7 which makes it very unhappy. 

I don't care how I resolve it, but it seems like I should be able to make a `pex` bundle that includes just `virtualenv` (and dependencies) and runs on the last 2-3 years of macOS.

**Comment by stuhood** [comment]
Mm. One of PEX's goals is to avoid actually compiling or otherwise running `setup.py` at runtime. So it attempts to ship containing wheels for all platforms you've targeted with the PEX.

You can target more platforms with the PEX that you build by passing it more arguments specifying target platforms:
```
    --platform=PLATFORMS
                        The platform for which to build the PEX. This option
                        can be passed multiple times to create a multi-
                        platform pex. To use wheels for specific
                        interpreter/platform tags, you can append them to the
                        platform with hyphens like: PLATFORM-IMPL-PYVER-ABI
                        (e.g. "linux_x86_64-cp-27-cp27mu",
                        "macosx_10.12_x86_64-cp-36-cp36m") PLATFORM is the
                        host platform e.g. "linux-x86_64",
                        "macosx-10.12-x86_64", etc". IMPL is the python
                        implementation abbreviation (e.g. "cp", "pp", "jp").
                        PYVER is a two-digit string representing the python
                        version (e.g. "27", "36"). ABI is the ABI tag (e.g.
                        "cp36m", "cp27mu", "abi3", "none"). Default: current
                        platform.
```

**Comment by AndrewHoos** [comment]
Right, but pip fails to download packages if you use the `--platform` flag:

```
python2 -m pex -r pex-requirements.txt -o python -i https://pypi.apple.com/simple  --platform macosx_10.15_x86_64-cp-27-cp27m 
WARNING: Refusing to set -H / --header option(s) because multiple index URLs are configured.
ERROR: Could not find a version that satisfies the requirement filelock<4,>=3.0.0 (from virtualenv==20.0.15->-r pex-requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for filelock<4,>=3.0.0 (from virtualenv==20.0.15->-r pex-requirements.txt (line 1))
pid: 14929 -> /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Users/ahoos/.pex/pip.pex/6bd62cbe8c9f1ae82b35f976967538908799cbd6 --disable-pip-version-check --isolated --no-python-version-warning -q --cache-dir /Users/ahoos/.pex download --dest /var/folders/5m/m11gnvbd7q55lxl2cjmszlsr0000gn/T/tmpPmzOnu/macosx_10_15_x86_64-cp-27-cp27m --index-url https://pypi.org/simple --extra-index-url https://pypi.apple.com/simple --header Cache-Control:max-age=3600 --retries 5 --timeout 15 --platform macosx_10_15_x86_64 --implementation cp --python-version 27 --abi cp27m --only-binary :all: --requirement pex-requirements.txt raised Executing /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Users/ahoos/.pex/pip.pex/6bd62cbe8c9f1ae82b35f976967538908799cbd6 --disable-pip-version-check --isolated --no-python-version-warning -q --cache-dir /Users/ahoos/.pex download --dest /var/folders/5m/m11gnvbd7q55lxl2cjmszlsr0000gn/T/tmpPmzOnu/macosx_10_15_x86_64-cp-27-cp27m --index-url https://pypi.org/simple --extra-index-url https://pypi.apple.com/simple --header Cache-Control:max-age=3600 --retries 5 --timeout 15 --platform macosx_10_15_x86_64 --implementation cp --python-version 27 --abi cp27m --only-binary :all: --requirement pex-requirements.txt failed with 1
```

**Comment by AndrewHoos** [comment]
It seems like the help for --wheel/--no-wheel might be improved to clarify what it does. 

Whether to use prebuilt wheels or force wheels to be rebuilt; Default: allow 
                        prebuilt wheels

**Comment by jsirois** [comment]
@AndrewHoos since the current language is confusing to you and that looks like a reasonable translation, would you be willing to submit a PR?

For the record, the current text:
```
--wheel, --no-wheel, --no-use-wheel
                        Whether to allow wheel distributions; Default: allow
                        wheels
```
That language is correct since a wheel distribution is by definition a zipped up wheel file which PEX contains 0 of. It is indeed confusing to unzip a PEX and see what looks like wheels. There are none though! Each path in a PEX zip that looks wheelish is just exactly a site-packages directory with 1 distribution installed. The only reason the directory prefix has the same name as a wheel file is for internal book-keeping.

**Comment by jsirois** [comment]
@AndrewHoos I'm going to close this as answered and count on you to send up an option help text adjustment PR if you're still dissatisfied with the current state of things.
