### ISSUE TITLE
Feature Request : Syntax for --platform to refer to the current platform

### ISSUE THREAD

**Issue by mschaef-da** [pantsbuild/pex#997]
I'm working on a project where I'm using an OS X development machine to cross build PEX files that need to run both on OS X and on Linux. To do this, I am using `--platform` to define a new platform list for the build that contains both the OS X platform string and the target platform:

`--platform macosx_10.15-x86_64-cp-37-cp37m  --platform manylinux2010-x86_64-cp-37-cp37m`

This works, but it requires explicitly specifying (and knowing) the current platform string. What would be useful to avoid this is a syntax for the `--platform` option that uses the normal defaulting logic to compute the current platform string and adds that to the platform list.

`--platform host-platform --platform manylinux2010-x86_64-cp-37-cp37m`

Alternatively, a programmatic way to query for the current platform string would also work:

`--platform $(find-python-platform-string) --platform manylinux2010-x86_64-cp-37-cp37m`

**Comment by jsirois** [comment]
Aha - Pex does support this but the feature is not documented. You can use `--platform current`. I'll leave this issue open and close it with a CLI help string improvement though to make this clear.

Also though, you can mix interpreter selection strategies as well. So you could acheive the same end in many ways:
1. `--platform current --platform manylinux2010-x86_64-cp-37-cp37m`
2. `--python python37 --platform manylinux2010-x86_64-cp-37-cp37m`
3. `--python /path/to/specific/mac/interpreter --platform manylinux2010-x86_64-cp-37-cp37m`
4. `--interpreter-constraint CPython==3.7.* --platform manylinux2010-x86_64-cp-37-cp37m`

The advantage of 2-4 is they allow better control over which local interpreter to use. With `--platform current` you get the 1st on your $PATH which may not be a 37 interpreter depending on OS upgrades, etc.

**Comment by jsirois** [comment]
@mschaef-da hopefully this makes things clearer - `current` is explained and an example drawn from the current interpreter is included allowing you to run pex on target platforms to find out their platform string in a backhanded way: https://github.com/pantsbuild/pex/pull/1001

**Comment by mschaef-da** [comment]
Thank you! Very much appreciated.
